### PR TITLE
Scarer: Add plain scarer that shows "scary" queries

### PR DESCRIPTION
**Pull request by pfirsichbluete**
(I accidentally closed PR https://github.com/duckduckgo/zeroclickinfo-spice/pull/1588 hence reopening again here)

**What does your Instant Answer do?**

Pops up a dialog saying “BOOO!” after 5 seconds. Then optionally forwards to a “scary” query like “no internet access”.

**What problem does your Instant Answer solve (Why is it better than organic links)?**

organic links cannot wait 5 seconds.

**What is the data source for your Instant Answer? (Provide a link if possible)**

Ther is no datasource.

**Why did you choose this data source?**

n/a

**Are there any other alternative (better) data sources?**

n/a

**What are some example queries that trigger this Instant Answer?**

`scare me`

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**

easter-egg-hunters

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**

Yes:
https://duck.co/ideas/idea/312/if-you-put-in-scary-in-the-bar-after-5-seconds

**Which existing Instant Answers will this one supersede/overlap with?**

None

**Are you having any problems? Do you need our help with anything?**

No.

**What are the terms of use for the API? Will DuckDuckGo need specific authorization (e.g. an API key)? Are there any costs associated with API usage?**

No.

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**

scarer_workflow
## Checklist

```
[X] Added metadata and attribution information
[X] Wrote test file and added to t/ directory
[X] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[X] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
[X] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 10

    - Windows 7
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 8
        [] IE 9
        [] IE 10

    - Windows XP
        [] IE 8

    - Mac OSX
        [] Google Chrome
        [] Firefox
        [] Opera
        [] Safari

    - iOS (iPhone)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - iOS (iPad)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - Android
        [] Firefox
        [] Native Browser
        [] Google Chrome
        [] Opera

Tested on Firefox, Chromium, and Opera (each on GNU/Linux).
```

### CODE REVIEW

**Comment by moollaza** [comment]
@pfirsichbluete thanks a lot for contributing, we really appreciate it! We'll be sure to review this shortly and give you some feedback!

**Comment by jagtalon** [comment]
@pfirsichbluete I'm hesitant on this because I don't think we have `alert` or `confirm` boxes anywhere on the site but we do have things like this from Timer (thanks to @mattr555):

screen shot 2015-04-08 at 3 43 22 am

If we're gonna go with this, I think we'll have to go with something like that. Also, we'd have to check that there's **no remainder** so that it's limited to triggering only to 'scare me' and 'show me something scary'.

CC @abeyang @chrismorast

**Comment by jagtalon** [comment]
@pfirsichbluete I'd like an easter egg like this, but I'll put it on hold for now until we hear from @abeyang and @chrismorast. We want easter eggs but it should still be in the same design and spirit as the rest of the site.

**Comment by pfirsichbluete** [comment]
> @pfirsichbluete I'm hesitant on this because I don't think we have alert or confirm boxes anywhere on the site but we do have things like this from Timer (thanks to @mattr555):

@jagtalon Updated Pull-Request to avoid `alert`/`confirm` boxes, and go with the `Timer` design.

scarer

> [...] Also, we'd have to check that there's no remainder so that it's limited to triggering only to 'scare me' and 'show me something scary'.

Done. Pull-Request updated accordingly.

**Comment by jagtalon** [comment]
@pfirsichbluete thanks--will notify the design team.

**Comment by moollaza** [comment]
@pfirsichbluete we had a discussion amongst most of the team about this IA recently. We all agreed the idea is great and we love "easter egg" Instant Answers. We also agreed that any easter eggs we launch need to be really amazing. They typically garner a lot of attention if they're good, and if they're not, it can reflect poorly on us. I'm sure you're aware that Google is known for having some great easter eggs, and we'd love to have some that are even better.

We love the idea for this, but we feel that it needs to be improved a lot before we're ready to launch something like this. The other big thing to consider is that we have a global audience and we want something for this that particularly translates well for everyone else, meaning perhaps we should show any English words, but find something else that anyone/everyone could find genuinely scary or surprising.

We're all going to be brainstorming about better implementations of the IA and we'd love to hear any thoughts or suggestions you have as well. We want this IA to be awesome and to set the bar high for any other Easter Egg PR's that follow.

For now I'm going to close this and once we've agreed on something awesome, we can revisit. How does that sound? Sorry that we can't use this right now, I really hope you understand where we're coming from though.

As always, thanks a ton for taking the time to contribute, we *really* appreciate it!

**Pull request closed without merging**
