### PR TITLE
Currency: Should accept plural forms of currency names #1419

### PR DESCRIPTION
**Pull request by laouji**
This is a response to duckduckgo/zeroclickinfo-spice#1419

### Changes made:
- [x] Updated the regex to allow for an optional s character after currency names
- [x] Added a few irregular plural forms to the currencylist data file

```
[x] Added metadata and attribution information
[x] Wrote test file and added to t/ directory
[x] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[x] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
[] Tested cross-browser compatibility (no but I only changed the backend)

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 10

    - Windows 7
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 8
        [] IE 9
        [] IE 10

    - Windows XP
        [] IE 7
        [] IE 8

    - Mac OSX
        [x] Google Chrome
        [] Firefox
        [] Opera
        [] Safari

    - iOS (iPhone)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - iOS (iPad)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - Android
        [] Firefox
        [] Native Browser
        [] Google Chrome
        [] Opera
```

### CODE REVIEW

**Comment by MrChrisW** [comment]
@laouji Thanks for tacking this! Two requests: 

1. Can we only allow the extra `s` on words longer then 3 chars (e.g not 3 letter currency codes) (or some other workaround) to avoid the ability to match queries like: `5 auds to idrs`, `10 usds to dops` as these are incorrect currency codes?

2. Add another `undef` test case using something like `1 british house to australian dollars` just to ensure we're only triggering on actual plural currencies (which I know we are :laughing: )

**Comment by MrChrisW** [comment]
@laouji Have you had an opportunity to review my feedback? Feel free to let me know if you have any questions.

**Comment by laouji** [comment]
Hi. Thanks for the feedback. I've been pretty busy with my day job and haven't quite cracked out a good regex to handle request #1 yet.

At the moment I'm thinking of adding a condition to check if the currency marker matched is 3 letters or longer and to allow the optional plural if it is.

**Comment by laouji** [comment]
Err I mean 4 letters or longer.

**Comment by jagtalon** [comment]
@MrChrisW I think this is good for now--maybe we can put the 4 letters or longer in an issue. What do you think?

**Comment by MrChrisW** [comment]
@jagtalon Sure lets do that :+1:  Thanks for all your help @laouji

**Comment by laouji** [comment]
Ok I will push the extra tests I added later today and then you can take it from there.

**Comment by MrChrisW** [comment]
@laouji :+1:

**Comment by laouji** [comment]
@MrChrisW I pushed the tests I wrote in response to your recommendation. :sparkles:

**Comment by jagtalon** [comment]
:+1:

**Pull request merged**
