### PR TITLE
IsItUp - added in new triggers. what is ? ip for example

### PR DESCRIPTION
**Pull request by adentranter**
Added in a new trigger for this spice.
Example
What is google.com ip
or
whats google.com ip

Having it using the IsItUp splice allows you to not only see that the domain is online but returns a IP in a clickable link.

### CODE REVIEW

**Comment by MrChrisW** [comment]
@adentranter This type of query "what is <domain> ip" may be more suited to the DNS Instant Answer. https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/DNS.pm

**Comment by adentranter** [comment]
True; Well i can add it into that spice if need be??

After reviewing what the DNS spice does, i agree.

... me being a noob at github; should i close and comment this issue? and then create another pull request?

**Comment by MrChrisW** [comment]
Sure, feel free to close this PR and open a new one making changes to DNS.pm triggering. 

Ping me when you've created the new PR and I'll review and merge!

**Comment by moollaza** [comment]
@adentranter @MrChrisW 

>This type of query "what is ip" may be more suited to the DNS Instant Answer. 

I was just going to say that! Thanks for helping to improve our IAs @adentranter. I look forward to your new PR :smile:

**Comment by MrChrisW** [comment]
@moollaza :laughing: 

@adentranter How are you going with adding the query to the DNS IA? No rush, just feel free to let me know if you have any questions.

**Comment by adentranter** [comment]
@MrChrisW I have finished the change; but haven't managed to sit down and heavily test it ( which most likely means I will find improvements/bugs with my fix. )

Ill get a chance to send a new PR this Friday.

I will let you know if I have any problems - Ive been learning Perl along side starting to contribute to duckduckgo :D

**Comment by MrChrisW** [comment]
@adentranter Great.

When you update triggers it's best to also update the [*test file*](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/t/DNS.t) also to include the new trigger, these test files serve as a way to continually and automatically test IA triggers. You can run the `prove -Ilib t/TestName.t` command to run the tests. More [information on duck.co](https://duck.co/duckduckhack/test_files).

Perl is a great language to learn, it's regex capabilities rock! :guitar:  Some awesome resources (you probably have these bookmarked already :laughing: ): 
* http://perldoc.perl.org/index.html
* http://www.perlmonks.org/
* https://duckduckgo.com/?q=perl (had to include this lol)

Looking forward to reviewing your next PR :+1:

**Pull request closed without merging**
