### PR TITLE
Increases snippet length to 150 chars - #2547

### LINKED ISSUE #2547: Dogo News: Increase snippet length OR decrease tile height
There's a lot of blank space at the bottom of the tiles for this IA.

We should increase the snippet text length to fill out the space or reduce the tile height.

------
IA Page:  http://duck.co/ia/view/dogo_news
/cc @dogomedia @anuragaryan

### PR DESCRIPTION
**Pull request by anuragaryan**
Fixes #2547 . This commit increase the snippet text length to 150 chars.

IA Page: https://duck.co/ia/view/dogo_news

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@anuragaryan Thanks! This LGTM :+1:

**Comment by anuragaryan** [comment]
:smile:

**Comment by anuragaryan** [comment]
@moollaza If you don't mind, I've two questions.
1. By when will my change reflect on the real website?
2. Can I use the codio account access I got with DDG for my other projects too?

**Comment by alohaas** [comment]
@anuragaryan ,thanks again for improving the Dogo News! 
You can see your change live here – [search Dogo News](ttps://duckduckgo.com/?q=dogo+news&t=ffab&ia=kidsnews). You’ve done a really good job here and we'd like you to help make DuckDuckGo even better for yourself and others interested in Dogo News.

When you're ready to move on, please: 

- Create a new Instant Answer for searches you do related to Dogo News or News in general.

OR

- Test live News Instant Answers (or those in development) for bugs and suggest improvements

Detailed instructions explaining how you can help are available at the top of this [page](https://github.com/duckduckgo/duckduckgo/wiki/Creating-or-Improving-Instant-Answers).

Thanks again!

**Comment by anuragaryan** [comment]
@alohaas will do :+1:

**Pull request merged**
