### PR TITLE
New SwiftDocs Instant Answer

### LINKED ISSUE #275: Create SwiftDocs Instant Answer
## Background

[http://swiftdoc.org/](http://swiftdoc.org/) has some excellent documentation on Swift types and protocols. We can absolutely use this data to answer queries like "swift array".

eb96761b2088e9392921006e2d154e5cd7206f1f_1_690x359
### Objective

For it to answer queries pertaining to protocols and types in Swift.
#### Example Queries
- [swift foreach](https://duckduckgo.com/?q=swift+foreach)
### What to do:
1. Comment here if you'd like to handle this task. 
2. Review any Related Discussions, Issues, and Pull Requests (below).
3. [Setup your Dev Environment](http://docs.duckduckhack.com/welcome/setup-dev-environment.html) (first-timers only)
4. Refer to the [Fathead documentation](http://docs.duckduckhack.com/resources/fathead-overview.html) and [other Fatheads](https://duck.co/ia?repo=fathead) as examples
5. [Submit a Pull Request](http://docs.duckduckhack.com/submitting/pull-request.html) with your completed changes
### Who to contact for help:

Please contact @jagtalon  or see [other contact info](http://docs.duckduckhack.com/resources/get-in-touch.html).

---

**Related Discussions, Issues, and Pull Requests:** 

Forum Topic: https://forum.duckduckhack.com/t/create-swiftdoc-instant-answer/242

### PR DESCRIPTION
**Pull request by soleo**
###### Description of changes

The purpose of this pull request is to use a Spice instead of Fathead to do swift related queries. The spice uses http://api.swiftdoc.org as the data source. If this IA turns out to be not good enough, we could consider using https://github.com/SwiftDocOrg/swiftdoc-parser to get  a better result.
###### Which issues (if any) does this fix?

Fixes https://github.com/duckduckgo/zeroclickinfo-fathead/issues/275
Fixes https://github.com/duckduckgo/zeroclickinfo-fathead/pull/271
###### People to notify (@mention interested parties)

@jagtalon 

---

IA Page: https://duck.co/ia/view/swift_docs_search
Forum Topic: https://forum.duckduckhack.com/t/create-swiftdoc-instant-answer/242
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jagtalon

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by soleo** [comment]
IA Page: http://duck.co/ia/view/swiftdocsspice

**Comment by soleo** [comment]
Search keyword: ``swift flatmap``
screen shot 2016-08-13 at 9 14 52 pm

More Details on  ``swift flatmap``
screen shot 2016-08-13 at 9 13 53 pm

**Comment by jagtalon** [comment]
Thank you, @soleo! Checking it out. :raised_hands:

**Comment by soleo** [comment]
Ideally I should have used ``text_item`` template, however in that template, the content is not recognizing the markdown syntax. Is there any way we could patch the {{ellipsis}} to be able to support markdown syntax and convert to html? @jagtalon

**Comment by jagtalon** [comment]
@soleo 

- Searching something like "swift foreach" gives a lot of results when I think all we need is SequenceType.forEach: https://v.usetapes.com/2O9DWIgolo

- Searching for "swift Array" yields a lot of "unknown"s when it should just give the Array type:

screen shot 2016-08-15 at 3 47 33 pm

> Is there any way we could patch the {{ellipsis}} to be able to support markdown syntax and convert to html

I'm not sure about this one yet--I'll look into it!

**Comment by soleo** [comment]
@jagtalon looks like the API is much less mature than I originally thought. I saw some javascript snippets from their site. I might be able to use the same sorting method they used on https://swiftdoc.org to improve the result.

**Comment by jagtalon** [comment]
@soleo thank you! Hit me up on slack if you need any help.

**Comment by moollaza** [comment]
@soleo thanks for all the work here! I'm closing this PR as it has gone stale and we decided on a different approach for Apple Swift/Obj-C results

**Pull request closed without merging**
