### PR TITLE
timer: fix mobile start button enabling

### PR DESCRIPTION
**Pull request by mattr555**
I just noticed this, the start button doesn't enable on mobile! 

cc @jagtalon @moollaza, would like to get this out fast :)

### CODE REVIEW

**Comment by moollaza** [comment]
@mattr555 thanks for this. I just tested the live site on my Android and it works and I used browserstack for iPhone 6 and it works as well. Just wondering what phone you have that isn't working?

**Comment by moollaza** [comment]
LGTM :+1:

**Comment by mattr555** [comment]
@moollaza Hmm, it seemed to be an issue with the third-party keyboard I was using (Fleksy) on my iPhone 5S. The stock keyboard worked fine.

**Comment by moollaza** [comment]
haha I use Fleksy as well! Actually I'm constantly switching between Fleksy, Swiftype and Minuum (longest running). I can't find a keyboard I like...

**Pull request merged**
