### PR TITLE
PoliticalPolls: Bug fix for #2348

### LINKED ISSUE #2348: Political Polls: Triggering needs to be reigned in -- triggers on anything with "poll"
Looks like just about any query containing "poll" is triggering this IA. We definitely need to reign this in!

Examples:
- [poll dance](https://duckduckgo.com/?q=poll+dance&t=ffab&ia=polls)
- [jobs poll](https://duckduckgo.com/?q=jobs+poll&t=ffab&ia=polls)
- [poll poll](https://duckduckgo.com/?q=poll+poll&t=ffab&ia=polls)

/cc @alexander95015 

---

IA Page:  http://duck.co/ia/view/political_polls

### PR DESCRIPTION
**Pull request by alexandernext**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.
- [ ] New Instant Answer: **`New {IA Name} Instant Answer`**
- [ X ] Improvement
  - [ X ] Bug fix: **`{PoliticalPolls}: Fix {#2348}`**
  - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
  - [ ] Other (Role, Template, Test, Documentation, etc.): **`{SpiceRole/Templates/Tests/Docs}: {Short Description}`**
###### Description of changes

Constrains IA to only trigger on "election poll" or "election polls".
###### Which issues (if any) does this fix?

Fixes #2348  - it stops the IA from triggering on unrelated queries by limiting the trigger to "election poll(s)" instead of "poll(s)".
###### People to notify (@mention interested parties)

@moollaza

---

Instant Answer Page: https://duck.co/ia/view/political_polls
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @alexandernext (new handle for @alexander95015)

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@alexandernext thanks for updating this IA! Unfortunately it looks like your branch has some conflicts -- can you please resolve them with something like `git pull upstream master` or `git rebase`?

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=election polls)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/political_polls_mobile.png?yoMgOVvkbO)

**Comment by moollaza** [comment]
@alexandernext Thanks! This LGTM :+1:

**Comment by alexandernext** [comment]
@moollaza If the issue is with the remainder having specific states in them, we could probably use the `state` parameter for the API. http://elections.huffingtonpost.com/pollster/api

**Comment by moollaza** [comment]
> we could probably use the state parameter for the API. http://elections.huffingtonpost.com/pollster/api

That would be good for the queries like "election polls in <state>", but I'm more concerned with all the others, like the ones that specify "2015" or "2017", or "election polls map", "election polls by state", "elections polls canada" etc. None of those are relevant to this IA but all of them will trigger it. The problem is that we don't have a good set of specific queries that indicate intent to see these specific polls, other than a query like "Huffington Post elections polls".

**Comment by alexandernext** [comment]
I think these are just a sampling of the latest polls, so perhaps a more generic list of keywords and then avoid triggering if there's any remainder?

**Comment by moollaza** [comment]
> I think these are just a sampling of the latest polls, so perhaps a more generic list of keywords and then avoid triggering if there's any remainder?

Yeah, any query looking for specific polls shouldn't show this, unless we know we're going to show something relevant to the query

**Comment by moollaza** [comment]
This PR is being closed due to inactivity. If you're still interested in finishing, please let me know and I'll gladly re-open it for you!

**Pull request closed without merging**
