### PR TITLE
quandl home values: fixed indiana bug

### PR DESCRIPTION
**Pull request by brianrisk**
The problem was that the abbreviation for "Indiana" is "IN", so "home values in California" was triggering on the "in".

### CODE REVIEW

**Comment by brianrisk** [comment]
@moollaza this addresses this bug:
https://github.com/duckduckgo/zeroclickinfo-spice/issues/2090

**Comment by moollaza** [comment]
@brianrisk could we update the Perl logic to better handle this so we can still allow queries for Indiana?

something like `s/\bin\b(\w+)/$1/` perhaps?

**Comment by brianrisk** [comment]
@zaahir, sorry for the confusion.  I'm only getting rid of the "in" abbreviation.  "home values in Indiana" will still trigger the IA.

**Comment by jagtalon** [comment]
@brianrisk looks good, although it would be good to update the tests as well.

**Comment by brianrisk** [comment]
@jagtalon Good suggestion -- Done!

**Comment by moollaza** [comment]
LGTM :+1:

**Pull request merged**
