### PR TITLE
SeatGeek - Standard Date Badge

### PR DESCRIPTION
**Pull request by sdougbrown**
Requires an internal PR.

This uses a standard date object to display a date badge via some new internal styling, rather than duplicating the same CSS and styling across all of these different folders.

cc @bsstoner @abeyang @moollaza @jagtalon @MariagraziaAlastra

### CODE REVIEW

**Comment by jagtalon** [comment]
@sdougbrown nice--lots of cruft removed. Testing it.

**Comment by bsstoner** [comment]
:+1:

**Comment by bsstoner** [comment]
There's an alignment issue on mobile, but seems unrelated, already happening in prod.
screen shot 2015-05-15 at 3 31 31 pm

**Comment by abeyang** [comment]
Hi, for the month, I think we have to use the 3-letter abbreviation.

Also, can someone throw this on a dev server somewhere for me to test / spot-check?

**Pull request merged**
