### PR TITLE
Movie: Check movie year against searched year

### LINKED ISSUE #1339: Movies disambiguation with year.
If someone types in the year of the movie release, just show that single result when multiple results are available.

img_5872

https://duck.co/ia/view/movie

### PR DESCRIPTION
**Pull request by MrChrisW**
Fixes #1339

Ping pong @jagtalon 

**Example:**
image
image

__________________________________________
~~Note: There may be a relevancy issue, example search for "Babe 2006" https://duckduckgo.com/?q=Babe+2006+rotten+tomatoes~~ Fixed

### CODE REVIEW

**Comment by jagtalon** [comment]
@MrChrisW Nice--what about queries like "RoboCop (2014 film) rotten tomatoes"?

It looks like `trim` doesn't work on IE 8 either: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim

**Comment by jagtalon** [comment]
Also would like some indentation in there. :)

**Comment by MrChrisW** [comment]
@jagtalon The main duckduckhack JS contains the `String.prototype.trim` polyfill so using trim shouldn't be an issue.

**Comment by MrChrisW** [comment]
@jagtalon That's a wonderful query *"RoboCop (2014 film) rotten tomatoes"* :laughing: Thanks for the curve ball :soccer: 

Few options when comparing the query to the movie title.

+ Strip everything within round brackets `/ *\([^)]*\) */g`
  + Probably not the best option as someone could search a movie that contains brackets in the title. Example: [(500) Days of Summer](http://www.imdb.com/title/tt1022603/)

+ Strip keywords `film`, `movie` and round brackets.
 + Movies can contain these keywords and this isn't very maintainable :frowning:

**Comment by jagtalon** [comment]
@MrChrisW Maybe check if there's `\d{4}` inside the brackets? Would that work?

**Comment by MrChrisW** [comment]
@jagtalon Best I can think of is below. This will allow the query `RoboCop (2014) rotten tomatoes.

````javascript
 if (query.match(/\(.+?\)/g)) { #match parenthesis
     query = query.replace(/\(|\)/g, ''); #remove parenthesis
 }
`

However `RoboCop (2014 film) rotten tomatoes` is a little more difficult as you're dealing with arbatery keywords `film` `movie` etc.

**Comment by MrChrisW** [comment]
Ping @jagtalon

**Comment by jagtalon** [comment]
@MrChrisW got it! :+1:

**Pull request merged**
