### PR TITLE
Currency Discussion: Coinbase

### PR DESCRIPTION
**Pull request by pjhampton**
# DO NOT MERGE

## Description of new Instant Answer, or changes

An internal talking point for switching the currency upstream data provider.

## People to notify

@moollaza 

---

Instant Answer Page: https://duck.co/ia/view/currency

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by daxtheduck** [comment]
## [Currency Conversion](https://duck.co/ia/view/currency)

**Description**: Currency Convertor provided by XE.com

**Example Query**: [convert 499 usd to cad](https://beta.duckduckgo.com/?q=convert%20499%20usd%20to%20cad), [cad to usd](https://beta.duckduckgo.com/?q=cad%20to%20usd), [cny?](https://beta.duckduckgo.com/?q=cny?)

**Tab Name**: Currency

**Source**:  

*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/currency)*

---
*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/currency)*

**Comment by daxtheduck** [comment]
## [Currency Conversion](https://duck.co/ia/view/currency)

**Description**: Currency Convertor provided by XE.com

**Example Query**: [convert 499 usd to cad](https://beta.duckduckgo.com/?q=convert%20499%20usd%20to%20cad), [cad to usd](https://beta.duckduckgo.com/?q=cad%20to%20usd), [cny?](https://beta.duckduckgo.com/?q=cny?)

**Tab Name**: Currency

**Source**:  

*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/currency)*

---
*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/currency)*

**Comment by moollaza** [comment]
Closing for now. Likely won't need this 👍

**Pull request closed without merging**
