### PR TITLE
First attempt at an instant answer for Tor nodes.

### PR DESCRIPTION
**Pull request by mogigoma**
# Spice Pull Request Template

Using this template will help us better understand your Instant Answer and assist you when necessary.  Simply copy and paste the markdown below into the description of your GitHub pull request and complete as appropriate.

**What does your Instant Answer do?**

Returns information on a Tor node.

**What problem does your Instant Answer solve (Why is it better than organic links)?**

It provides terse information immediately, with links to more verbose displays included.

**What is the data source for your Instant Answer? (Provide a link if possible)**

https://onionoo.torproject.org/protocol.html

**Why did you choose this data source?**

It's the standard REST API for Tor.

**Are there any other alternative (better) data sources?**

Nope.

**What are some example queries that trigger this Instant Answer?**

"tor node 198.96.155.3",
"tor bridge BCEDF6C193AA687AE471B8A22EBF6BC57C2D285E",
"tor bridge node 3E0908F131AC417C48DDD835D78FB6887F4CD126",
"tor exit 198.96.155.3",
"tor exit node BCEDF6C193AA687AE471B8A22EBF6BC57C2D285E",
"tor relay 3E0908F131AC417C48DDD835D78FB6887F4CD126",
"tor relay node 198.96.155.3";

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**

System administrators, power users, security professionals.

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**

Not specifically, other ideas involve Tor but I've not seen any about node information.

**Which existing Instant Answers will this one supersede/overlap with?**

None.

**Are you having any problems? Do you need our help with anything?**

Not currently, thanks.

**What are the terms of use for the API? Will DuckDuckGo need specific authorization (e.g. an API key)? Are there any costs associated with API usage?**

It's open, no limits AFAIK.

**Where did you hear about DuckDuckHack? (For first time contributors)**

Twitter.

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**

tor-relay
tor-bridge

## Checklist
Please place an 'X' where appropriate.

```
[X] Added metadata and attribution information
[X] Wrote test file and added to t/ directory
[X] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[X] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
[] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Linux
        [x] Firefox
```

### CODE REVIEW

**Comment by MrChrisW** [comment]
@mogigoma Thanks for the contribution. 
There was a similar IA in development (*that has since closed*) back in September see #1012, this may provide some design tips.

**Comment by mogigoma** [comment]
As suggested, I have looked through PR #1012 for design comments, and addressed them in this branch. If there are any more suggestions, please let me know.

**Added more triggers**

Full list is now:

"tor node"
"tor node status"
"tor bridge"
"tor bridge status"
"tor bridge node"
"tor bridge node status"
"tor exit"
"tor exit status"
"tor exit node"
"tor exit node status"
"tor relay"
"tor relay status"
"tor relay node"
"tor relay node status"
"onion node"
"onion node status"
"onion bridge"
"onion bridge status"
"onion bridge node"
"onion bridge node status"
"onion exit"
"onion exit status"
"onion exit node"
"onion exit node status"
"onion relay"
"onion relay status"
"onion relay node"
"onion relay node status"

Note that we intentionally do not trigger on "tor status" or "onion status" in the hope that someday an instant answer can be made for those triggers (probably internally so it can access the IP of the client) that will inform users as to whether they are accessing DDG via Tor.

**Templates**

The remainder of the query can take two forms: a unique identifier (fingerprint, IPv4 address, IPv6 address) or search text. In the latter case, when multiple results can be returned, we will use a brief 'tiled' view. If we receive a single result, then a more detailed view will be used.

tor-single
tor-multiple
tor-multiple-details

I asked a Tor developer what he'd like to see in an Instant Answer, and used those fields for the single result template. There are many more, but the moreAt link to Atlas will show all the omitted fields. Basically, we've aiming to show a node's identity (fingerprint, nickname, contact, country, IP), status (status, first seen, last seen), and overall role (type, flags).

**Endpoint encryption**

There is no HTTP endpoint, attempting to access the API over HTTP redirects you to HTTPS. Forcing encryption is not surprising, since it's Tor-related.

**Relative timestamps**

I've used relative timestamps in the tile view, but full timestamps in the table. Feels like a fair compromise.

**Comment by MrChrisW** [comment]
@mogigoma Thanks for taking the time to look into the other PR. I've checked out your PR locally :+1: 

*My notes:*
+ The main detail should be using the record template as you were before to keep the styling normalized and avoid recreating the entire table. I understand you've done this so you can have both views (multiple and single results). However I believe there's another way to achieve this without recreating the records template in your handlebars file. I'm thinking like this [example](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/people_in_space/people_in_space.js#L76-L97) 

+ Strip 'mailto:' from contacts, seems some nodes have placed that in the contact field. 

+ The dates should be "prettify" [example](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/whois/whois.js#L117-L126)

+ Your test file is failing and needs updating.

Most of these notes relate to elements of the design. Design could change substantially before this PR is finished so you may want to await more feedback before changing things :grinning:  It's great to have this IA back in development :+1:

**Comment by mogigoma** [comment]
I've addressed the non-template recommendations for now. Will wait to see if there's more feedback before touching the templating, as advised. I looked at the people in space example, but if I hit the trigger I get tiles, but those tiles don't expand. If I click on a tile, it does a DDG search for what looks like their entire bio as a sentence.

**Comment by MrChrisW** [comment]
@mogigoma Great. Sorry if I wasn't very clear when linking the 'people in space' example. I was suggesting switching between the `text` template and the `records` template depending on how many nodes are returned. However it's probably best to wait for feedback surrounding the design before we proceed. Thanks for all your work! :+1:

**Comment by jdorweiler** [comment]
@mogigoma I'd switch the detail view back to use the record template.  I like the flag icons and color text.  Can you use those in the record template?  I've never tried that but I think it can work. 

Do you have any more examples that return multiple results?  I tried `tor node unclaimed` but the api didn't return any results.

**Comment by jagtalon** [comment]
@jdorweiler can you put it up on a server for us?

**Comment by mogigoma** [comment]
I've switched to the record template and shuffled the code around to put more into normalize().

@jdorweiler I can't make colour or images show up in the record template, their HTML gets escaped by the template. For more examples, try things like "tor node unnamed" or even "tor node a", both of which will returned the arbitrarily-chosen maximum of 25 nodes.

@jagtalon I have a server running on Codio at http://parody-giraffe.codio.io:5000/ which I'll leave up for now.

I would like the bottom of the record template to have a link to the Tor Atlas that is specific to the node being viewed, but I can't seem to make that work. Assistance with that feature would be appreciated. I suspect I am setting the wrong key (url) or missing a flag to enable it.

**Comment by jdorweiler** [comment]
@mogigoma if you set the record template inside of the options block then the more at link will work. 
selection_328

**Comment by mogigoma** [comment]
@jdorweiler I have done so, but the moreAt link is still for the query, as opposed to for the node. Is there a way to indicate the node's url field be used?

**Comment by jdorweiler** [comment]
I'm not sure where the record template is escaping the html.  I think it would look better with the color/flags on the detail view so I'll take a look at that and see if I can add that in.

**Comment by jdorweiler** [comment]
@mogigoma I see what you mean about the link.  I think the detail views normally don't have a moreAt link in them.  Here's an example of the Quixey IA https://duckduckgo.com/?q=flight+apps&ia=apps&iai=43840158
It uses the buttons to lead to the specific page.
@jagtalon do you know anything about having a moreAt link in the detail view like this?  Maybe it should just be a button.?
selection_329

**Comment by jdorweiler** [comment]
@chrismorast @abeyang  What do you think about a custom template for the detail view?  I don't think the record template looks that great for this.

**Comment by jagtalon** [comment]
@jdorweiler I feel that there's too much information in here, too.

- Is the fingerprint BCEDF6C193AA687AE471B8A22EBF6BC57C2D285E even useful? From the way it's presented it looks like it's the most important one.

- Will a list suffice? I like how it's presented in https://atlas.torproject.org/#search/gurgle

screen shot 2015-01-20 at 10 13 06 am

**Comment by jagtalon** [comment]
@jdorweiler Maybe we can even get rid of the detail view and just link to the page itself like https://duckduckgo.com/?q=people+in+space&ia=answer

**Comment by jdorweiler** [comment]
I agree.  It's a lot of information to display in a record view.  
@mogigoma what's the most useful information that we need to show?  Could we just skip the detail view all together and have the tile link back to the torproject page.

**Comment by abeyang** [comment]
Hi, jumping into this conversation here. As someone who's not too familiar with Tor, hope you don't mind me asking a few questions:

- How important is the fingerprint? Can we replace it and use the nickname as the prominent title?
- What's the significance of "first seen" (or even "last seen")? Wouldn't **uptime** be more useful?
- Would we even want to see servers/relays/etc that are **not** online?

Thanks. Again, a Tor Newb here, so I apologize if some of these questions are too elementary.

**Comment by mogigoma** [comment]
Sorry I've been silent. Here's some responses to various comments...

@jdorweiler If we're skipping the detail view, I think the fingerprint, nickname, status, presence, and country are all valuable to someone performing a search.

@abeyang The fingerprint is important since many, many nodes are unnamed and the fingerprint is their primary identifier. The downside, of course, is how long it is. Regarding first/last seen, I agree that uptime would be more valuable for online nodes, but I think that last seen is valuable for offline nodes. Seeing nodes that are offline is valuable, since the order that the nodes are displayed indicates the 'consensus weight' (importance, as I understand it) of a node, and a node that has brief downtime may be the one that someone is searching for.

@jagtalon Regarding getting rid of the detail view, that's entirely possible. To make the detail view I just asked a Tor developer what they would like to see and added those fields. I have no attachment to it.

**Comment by abeyang** [comment]
Thanks, @mogigoma . When you have time, can you throw it on a server again? Your previous link isn't working anymore... I have some ideas, but would like to see the current state as it is.

**Comment by mogigoma** [comment]
@abeyang It's back up at http://parody-giraffe.codio.io:5000/

@jagtalon With regard to getting rid of the detail view, I think getting rid of it for the tiles makes sense, but when there's a single match I'm of the opinion that displaying the most important details directly is valuable.

**Comment by abeyang** [comment]
@mogigoma it's not working for me... I still see this:
http://cl.ly/image/2y022q1I3x19

**Comment by mogigoma** [comment]
@abeyang It's back up, now. Got someone external to test as well. Have it running via Codio and I get booted occasionally, so can't say how long it'll stay up.

**Comment by abeyang** [comment]
Thanks @mogigoma . BTW, how important is the type (relay/bridge)? And do we get bandwidth results within the API? I imagine that to be helpful -- but correct me if I'm wrong!

**Comment by mogigoma** [comment]
@abeyang I think the type is important, since all nodes are one of those two types, and the type determines some amount of available information. Regarding the bandwidth info, I can add that. Here's an example of the minimum info we can expect on any node (a bridge): https://onionoo.torproject.org/details?fingerprint=3E0908F131AC417C48DDD835D78FB6887F4CD126

**Comment by abeyang** [comment]
@mogigoma here's my stab at this with the tiles. I agree with the others that clicking on it should go directly to the site, rather than pulling out a detail pane. I've tried to showcase what different options would look like (no country, no bandwidth, no nickname):

tor-v1

What do you think?

**Comment by jagtalon** [comment]
@abeyang that looks pretty sweet!

**Comment by mogigoma** [comment]
@abeyang That looks very nice, I especially like the coloured up/down indicators. I'll get a new version out for review be the end of the weekend.

**Comment by mogigoma** [comment]
I've made the tiled results look as close to @abeyang's demo as I could, though I'm not great with CSS so there's probably touchup required.

I've reverted back to the old non-record template for the single result, since that gives colour and the country icon, which are both nice.

Unfortunately, I can't for the life of me get the tiles themselves to link anywhere. I have a `url` attribute in the object returned by `normalize()`, but I can't get it to trigger. Suggestions?

**Comment by jagtalon** [comment]
@mogigoma hey thanks for this checking it out

**Comment by jagtalon** [comment]
@mogigoma still checking but here are some comments. Check out the code for people in space for the flags thing :) https://duckduckgo.com/?q=people+in+space

https://github.com/duckduckgo/zeroclickinfo-spice/tree/master/share/spice/people_in_space

**Comment by jagtalon** [comment]
screen_shot_2015-02-04_at_12_16_56_pm

**Comment by jagtalon** [comment]
@mogigoma @abeyang actually, yeah, the PeopleInSpace IA is perfect for this. So for this view:

screen shot 2015-02-04 at 12 27 31 pm

You should switch to the "base" template so that it looks nicer. Check out how PeopleInSpace switches between templates. https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/people_in_space/people_in_space.js#L89

Thanks!

**Comment by jagtalon** [comment]
@mogigoma: @moollaza pointed out to me that it should probably be the `text`/`info` group instead like https://duckduckgo.com/?q=whois+duckduckgo.com&ia=whois. 

In it, you can use a thing called a `record` template which means that you no longer have to write your own HTML. See how WhoIs does it in https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/whois/whois.js#L102.

For more information, check out the documentation: https://duck.co/duckduckhack/spice_templates_overview#record-template

**Comment by moollaza** [comment]
ping! @mogigoma are you still interested in finishing this up?

**Comment by mogigoma** [comment]
@moollaza Yes, I got busy and this fell off my radar. Will try and finish up my WIP and push tonight.

**Comment by jagtalon** [comment]
@mogigoma sounds good!

**Comment by mogigoma** [comment]
I've made edits to change the template and styling. Below are two screenshots:

screenshot from 2015-02-19 23 20 11

screenshot from 2015-02-19 23 20 40

I am extremely time-limited going forward, so expect delayed responses. Note that I still cannot get the tiles to link anywhere.

**Comment by jagtalon** [comment]
@mogigoma nice! Checking it out!

**Comment by abeyang** [comment]
@mogigoma looking good! Can we add these css tweaks:

```css
.zci--tor_node .tile--tor_node {
  margin-top: 0;
}

.zci--tor_node .tile__body.has-foot {
  padding-top: 0.7em;
}

.tile--tor_node .tile__title {
  font-size: 1.52em;
  padding-top: 0;
  height: auto;
}

.tile--tor_node .tile__content {
  font-size: 1.11em;
  color: #999;
  margin-top: 16px;
}

.tile--tor_node .tile__icon {
  border: 1px solid #ddd;
  border-radius: 10px;
  margin-top: 1px;

  /* remove bg-color and padding completely */
  background-color: transparent;
  padding: 0;
}

.zci--tor_node .tile__foot {
  height: 2.2em;
}

.zci--tor_node .one-line span {
  font-size: 1.11em;
}

.zci--tor_node .one-line .online {
  color: #5b9e4d;
}
```

It should look closer to this after you're done:
screen shot 2015-02-20 at 1 55 22 pm

BTW, what's up with the up/down arrows? Shouldn't the "down" arrow (with text) be red?

**Comment by mogigoma** [comment]
@abeyang I fixed the up/down arrow bug, and entirely replaced my CSS file with your suggestion. I then added formatting for the bandwidth back in and added a float to the uptime so that they're on the same line.

screenshot from 2015-02-20 16 21 46

**Comment by abeyang** [comment]
Hmm, it looks a little squished, and I'll need to give you an updated border color (doesn't look good on black). Will get back to you on that! /cc @jagtalon

**Comment by moollaza** [comment]
@mogigoma @abeyang this looks like it's just about done, I'm super excited!

@abeyang it looks like for the currency IA we have a separate div that sets a "border" via background colour which has a low opacity, making it work for both light and dark backgrounds. I think we might be able to do that here, or better yet, add that to our global CSS so we can replicate it elsewhere:

```css
.currency--border {
display: inline-block;
width: 36px;
height: 36px;
top: 10%;
left: 0px;
right: 0px;
margin-left: auto;
margin-right: auto;
background-color: rgba(50, 50, 50, 0.2);
border-radius: 50%;
position: absolute;
}
```

https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/currency/item.handlebars#L6

**Comment by abeyang** [comment]
Hi @mogigoma, so sorry for getting back so late. We're so close here, just a few more css tweaks and I think we're good:

```css
/* add more padding between content and footer */
.tile__body.has-foot {
  padding-bottom: 3.4em;
}

/* make tiles slightly wider */
.zci--tor_node .tile--tor_node {
  width: 18em;
}
```

@moollaza agreed -- let's get this into a global class, and we'll re-apply to the flags.

**Comment by mogigoma** [comment]
I added the CSS fixes, here's what the result looked like for me:

capture

**Comment by moollaza** [comment]
LGTM :+1:

**Comment by moollaza** [comment]
@mogigoma Thanks again for taking the time to contribute! We really appreciate it. Apologies that this took so long to get merged, most IAs don't usually take this long and we're constantly trying to improve our process to ensure these move along quickly and smoothly.

Feel free to stick around and comment/help on other PR's & Issues or even submit more Instant Answers!

**Comment by moollaza** [comment]
@mogigoma congrats! It's live: https://duckduckgo.com/?q=tor+node+198.96.155.3&ia=tornode

Sorry for the late notification, it actually went live last week

Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's & Issues or even submit more Instant Answers!

**Pull request merged**
