### PR TITLE
wrap jsonp callback for apps

### PR DESCRIPTION
**Pull request by b2ddg**
Change apps IA to use wrap_jsonp_callback. 

@bsstoner @moollaza

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by bsstoner** [comment]
This seems to suggest the problem with the JSONP wrapping was on their end? :+1: I'm cool with switching to this.

**Comment by b2ddg** [comment]
I think so, switching it here fixed the issues I was seeing.

**Comment by bsstoner** [comment]
:+1:

**Comment by moollaza** [comment]
@b2ddg @bsstoner I got an email from Quixey earlier today -- they noticed that they broken their callback function are were working on a fix.

We should be fine to keep it this way :+1:

**Comment by b2ddg** [comment]
sweet, thanks for the update @moollaza.

**Pull request merged**
