### PR TITLE
New Pwned Spice

### PR DESCRIPTION
**Pull request by b2ddg**
Needs coordination with https://github.com/duckduckgo/duckduckgo/pull/157

**What does your Instant Answer do?**
This IA searches haveibeenpwned.com for email accounts exposed in data breaches

**What problem does your Instant Answer solve (Why is it better than organic links)?**
This information isn't readily apparent from organic links. The text dumps have been nicely parsed and made available through this api.

**What is the data source for your Instant Answer? (Provide a link if possible)**
haveibeenpwned.com

**Why did you choose this data source?**
It's a definitive source and well made api.

**Are there any other alternative (better) data sources?**
no

**What are some example queries that trigger this Instant Answer?**
pwned test@hotmail.com
have i been pwned test@hotmail.com

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
people on the internet

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
https://duck.co/ideas/idea/4799/check-if-an-e-mail-has-been-compromised-in-a-hack

**Which existing Instant Answers will this one supersede/overlap with?**
none

**Are you having any problems? Do you need our help with anything?**
no

**What are the terms of use for the API? Will DuckDuckGo need specific authorization (e.g. an API key)? Are there any costs associated with API usage?**
no

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
screen shot 2015-11-06 at 3 55 29 pm

## Checklist
Please place an 'X' where appropriate.

```
[x] Added metadata and attribution information
[] Wrote test file and added to t/ directory
[x] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[x] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
[x] Tested cross-browser compatibility

 Please let us know which browsers/devices you've tested on:
        
    - Mac OSX
        - [x] Google Chrome
        - [x] Firefox

    - iOS (iPhone)
        - [x] Safari Mobile

```

-----
IA Page: https://duck.co/ia/view/pwned

### CODE REVIEW

**Comment by moollaza** [comment]
@b2ddg this is looking awesome. I've made a PR against your branch here: https://github.com/duckduckgo/zeroclickinfo-spice/pull/2283 -- take a look and merge it if you'd like. Then I'll merge this :+1:

**Comment by b2ddg** [comment]
@moollaza do we need to update duckpan to handle fallbacks before merging this?

**Comment by moollaza** [comment]
> @moollaza do we need to update duckpan to handle fallbacks before merging this?

We shouldn't -- I'll very its OK and merge :+1:

**Comment by moollaza** [comment]
@b2ddg this LGTM :+1:

**Pull request merged**
