### PR TITLE
bbc - using moment.js, removed unnecessary helpers

### PR DESCRIPTION
**Pull request by iambibhas**
Saw this IA could use some moment.js love, so using that. Sadly can't remove the `duration()` function as moment.js' `humanize()` function doesn't return accurate duration.

### CODE REVIEW

**Comment by moollaza** [comment]
>Sadly can't remove the duration() function as moment.js' humanize() function doesn't return accurate duration.

Care to elaborate on that? Is it a bug in Moment.js?

**Comment by iambibhas** [comment]
> Is it a bug in Moment.js?

See here - https://github.com/moment/moment/issues/348

It's apparently a feature to not support accurate humanization.

**Comment by moollaza** [comment]
@iambibhas can we do what was described in https://github.com/moment/moment/issues/348#issuecomment-6535794?

I defined a [modification](https://github.com/duckduckgo/zeroclickinfo-spice/blob/ed05efa4152f627dd3e54821bca2eb563d105192/share/spice/tor_node/tor_node.js#L77) to the language in a similar fashion for the Tor Node IA because of a similar problem.

**Comment by moollaza** [comment]
I guess its about as much code either way. This is fine for now :+1:

**Pull request merged**
