### PR TITLE
Standardise fact IA's

### PR DESCRIPTION
**Pull request by MrChrisW**
Fixing #1496

- [x] ~~Sales Tax~~- See #1497
- [x] Expatisan
- [x] Annual Rainfall
- [x] URL Shorten 

#### Screenshots
**Rainfall**
selection_186
_______

**Expatisan**
selection_188
selection_187

### CODE REVIEW

**Comment by moollaza** [comment]
@MrChrisW these are looking good. For Annual Rainfall, I'm not sure we need to say the measurement is in millimeters if the unit is there in the answers above.

@abeyang any thoughts?

**Comment by abeyang** [comment]
Agreed with @moollaza . Can we also get rid of "Expatistan's scale" for cost of living? Thanks!

**Comment by MrChrisW** [comment]
Updated. @moollaza Are you sure most Americans know what `mm` stands for? :laughing: *(no offence)*

@abeyang Updated!

[View online](http://duckpan.mrchris.me/?q=cost+of+living+philadelphia&ia=answer)

selection_196

[View online](http://duckpan.mrchris.me/?q=rainfall+afghanistan&ia=weather)
selection_197

**Comment by moollaza** [comment]
@MrChrisW very nicely done! LGTM :+1: 

@abeyang would like your signoff please!

**Comment by abeyang** [comment]
Good to go! :+1:

**Pull request merged**
