### PR TITLE
New Systemetapi Spice

### PR DESCRIPTION
**Pull request by ihatetoregister**
## Type of Change

- [X] New Instant Answer
    - [ ] Cheat Sheet
- [ ] Improvement
    - [ ] Bug fix
    - [ ] Enhancement
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.)

## Description of new Instant Answer, or changes

This IA will be able to look up beverages from the [government owned chain of liquor stores in Sweden](https://en.wikipedia.org/wiki/Systembolaget) called [Systembolaget](http://www.systembolaget.se/) via an [external API](http://systemetapi.se/). 

## People to notify

---

IA Page: https://duck.co/ia/view/systemetapi

Forum Topic: https://forum.duckduckhack.com/t/how-to-set-ia-to-in-development/1104

### CODE REVIEW

**Comment by daxtheduck** [comment]
@ihatetoregister Thanks for the pull request! Unfortunately, we're only accepting contributions and improvements to a limited portion of the search space.
            
The staff and community are currently focused on making DuckDuckGo the [best search engine for programmers](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53). To ensure we're making as much progress as possible, **we are only accepting Instant Answers and updates related to the programming mission**.
    
If this is not related to the Programming Mission, it will likely be closed but you can:
    
1. Help us prevent further confusion by telling us where you found out about DuckDuckHack or where we could've alerted you earlier.
2. Keep this code handy! We'll be expanding into other search topics in the future!
3. Join us at our new home: https://forum.duckduckhack.com/

If this is related to the Programming Mission, it will be reviewed by staff and the community as soon as possible!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@ihatetoregister unfortunately we can't accept this right now as we're currently focused on our Programming Mission, and only accepting Pull Requests related to that.

I'm sorry for the inconvenience. Can you help us prevent any further confusion by telling us where you found out about DuckDuckHack or where we could've alerted you earlier?

Again, apologies we can't accept this. However there are open issues for IA's that need to be created or improved if you're interested in helping us (and other programmers) out!

Please see https://forum.duckduckhack.com/t/duckduckhack-getting-started/53 for a list of open issues and more information about the Mission!

**Comment by ihatetoregister** [comment]
I just playing around and wanted to get around this message in duckpan:

```
Loading Instant Answers...
[NOTICE] These instant answers were not loaded:
[NOTICE] \{
    DDG::Spice::Systemetapi   "Could not retrieve metadata - please ensure the Instant Answer page is in development status or later."
}
```

The IA page is now in dev status but unfortunately this does still does not seem to work :(

**Pull request closed without merging**
