### PR TITLE
Color Picker continuation

### LINKED ISSUE #1495: Finish Up the Colour Picker IA
The PR has been abandoned by the original contributor, but our design team has posted an amazing mockup of how it should look.

https://github.com/duckduckgo/zeroclickinfo-spice/pull/1351

Any takers?

/cc @mattr555 -- I thought you might be interested

### PR DESCRIPTION
**Pull request by mattr555**
Continues from #1351; fixes #1495

- [x] Implemented @chrismorast's design:
screenshot - 02082015 - 02 56 53 pm
687474703a2f2f692e696d6775722e636f6d2f483658504c51512e706e67
- [x] shortcode input (like `#aaa`) works
- [x] use the number input on mobile (that's a third party keyboard):
687474703a2f2f692e696d6775722e636f6d2f47575850736d372e706e67
- [x] correct dismissing of keyboard on mobile
- [x] moved assets out of subdirectory (depending on duckduckgo/p5-app-duckpan#136)
- [x] IE8 `filter`
- [x] test for specifying own color
- [x] my attribution
- [x] "One thing I noticed in the palette selector is that the colors are incorrect. How is that being generated?" <-- I think this has to do with [this](https://en.wikipedia.org/wiki/CMYK_color_model#mediaviewer/File:CIE1931xy_gamut_comparison.svg); some colors cannot be represented in all of RGB, CMYK, and HSV.
- [x] Event handlers could be consolidated.

Sorry for the huge screenshots! cc @moollaza @jagtalon @MrChrisW @chrisharrill

### CODE REVIEW

**Comment by MrChrisW** [comment]
@mattr555 Awesome! I'll be testing shortly :smile:

One thing I noticed was the use of `patten` for the input field, unfortunately I don't believe this activates the keypad on Android like it does on iOS (I'll need to confirm), I believe the more standard way is using the`tel` or `number` tag. [More information](http://blog.teamtreehouse.com/using-html5-input-types-to-enhance-the-mobile-browsing-experience.)

Can't wait to try this out!

**Comment by moollaza** [comment]
@mattr555 nicely done! This is looking great :+1:

**Comment by chrismorast** [comment]
Nice work @mattr555 ! Thanks for tackling this one.
I have a few minor adjustments that I'll post tomorrow AM.

**Comment by MrChrisW** [comment]
@mattr555 Hope you don't mind, I just reduced those screenshots a little :wink:

**Comment by chrismorast** [comment]
Okay, here's the feedback. After writing it out I realized that some of it's not not really minor. 
Let me know how achievable these are:

1. Match corner radii on all elements. If we can't add a corner radius to everything, let's try none.
screen shot 2015-02-10 at 3 18 58 pm

2. Can we add a little padding to the left side of the fields?
screen shot 2015-02-10 at 3 21 33 pm

3. Can we right align the elements on the right side? This might mean we stretch the fields to fit.
screen shot 2015-02-10 at 3 26 08 pm

4. Can we try to vertically align elements to some sort of a grid. I'm attaching a screenshot of what I had with guidelines to show the matches. Also referencing where margins would be the same (matching the color bars to represent the margins that match). If it's too difficult I'm open to letting it slide a bit :)
screen shot 2015-02-10 at 3 34 59 pm
screen shot 2015-02-10 at 3 43 12 pm

**Comment by mattr555** [comment]
@chrismorast Thanks for these! The changes seem pretty doable, I'll let you know if I run into any problems.

In the meantime, I resolved the other problems in the top post. Two more questions though:

+ How should we integrate this with the [current color IA](https://duckduckgo.com/?q=%23123456&ia=answer)? Maybe add a link to the picker?
+ There's no regex guard, is that an issue?

**Comment by mattr555** [comment]
@chrismorast How'd I do? :)

screenshot - 02172015 - 12 19 12 pm
mobile

**Comment by chrismorast** [comment]
That looks so much better @mattr555 ! However, the grid is still off a little. Let me put together a screenshot for reference.

**Comment by chrismorast** [comment]
So here are some quick fixes and I think it can be ready. 
Before:
screen shot 2015-02-24 at 11 44 46 am

After:
screen shot 2015-02-24 at 11 45 33 am

Mobile Before:
screen shot 2015-02-24 at 11 52 26 am

Mobile After:
screen shot 2015-02-24 at 11 49 30 am

Once it's up I can tweak the CSS to try and fit everything into the original grid I had;
screen shot 2015-02-24 at 11 53 48 am

One thing we'll have to figure out is the trigger space. cc @moollaza 
We have another IA that has quite a bit of overlap but is a more simplified version. I can see a use case for both though. Perhaps we link this to that IA as well.

**Comment by moollaza** [comment]
@chrismorast for now this one is limited to queries with `color picker` in it, so "color picker" and "color picker #ccc" will both trigger this.

I think we can definitely add a link to the ColorCodes Goodie that would re-query and open this IA.

**Comment by chrismorast** [comment]
That sounds like a good plan @moollaza

**Comment by mattr555** [comment]
@chrismorast @moollaza Yeah, that's probably the best plan.

screenshot - 02282015 - 11 42 04 am

mobile

:ship:

**Comment by chrismorast** [comment]
:+1: - I think this is ready to go. Really nice work @mattr555 ! Thanks for tackling this doozy :)

**Comment by moollaza** [comment]
@mattr555 @chrismorast nicely done guys! This looks great. I'll do some final testing and merge :+1:

**Comment by moollaza** [comment]
@mattr555 noticed a few things:

- Colour selector for the large area can drag beyond bottom and right border:
2015-03-03_11h27_30
2015-03-03_11h27_42

- The two selection areas (color and hue) are able to be highlighted if you drag over them. Let's disable that ;)

- Can we make the `pallet_inputs` (for the related colours) into `<span>` so they're highlightable (but still not modifiable)

**Comment by mattr555** [comment]
@moollaza Thanks! I got every point except your fourth. I'm not really sure how to accomplish this, so patches welcome :smile:

Shall I make a PR for the color goodie to add a link to the picker?

**Comment by moollaza** [comment]
>Thanks! I got every point except your fourth. I'm not really sure how to accomplish this, so patches welcome :smile:

@mattr555 looks like you fixed No.4, did you mean the 3rd item? Allowing the drag to go outside the selector space?

---

If you can't easily implement the extended dragging it's no big deal. We can create an issue for the community. Hopefully we can rope a newcomer in with an interesting task like that :smiley:

**Comment by mattr555** [comment]
@moollaza you may want to count again :P

:shipit:?

**Comment by moollaza** [comment]
Hahaha, whoops, I definitely didn't scroll up far enough! 

>Shall I make a PR for the color goodie to add a link to the picker?

Yes please do!

**Comment by moollaza** [comment]
@mattr555 @chrismorast LGTM :+1:

**Comment by mattr555** [comment]
:tada:

Check out duckduckgo/zeroclickinfo-goodies#1041.

**Pull request merged**
