### PR TITLE
Keybase - Refactor into icon group template

### LINKED ISSUE #1864: Gravatar, Keybase, Zodiac, Twitter : Switch to Icon template group
To Be Converted:

- [x] Gravatar (assigned to @altern8tif)
- [x] Keybase
- [ ] Zodiac (images assets: http://cl.ly/19171G2D2H21)
- [x] Twitter

---

We now have the [Icon template group](https://duck.co/duckduckhack/templates_overview#icon-template-group), which allows us to easily re-create the looks of these IA's without the need for any custom templates.

The icon template can display 3 lines of text if you specify the `title`, `subtitle` and `altsubtitle` accordingly.

The `subtitle` and `altsubtitle` can be a single string, or an `array` of `string`'s or `objects`. If an array is provided, the template will automatically separate the elements. To create separated links, an array of objects can be provided like so:

```js
normalize: function(item){
    subtitle: [{
        href: "https://website.com"
        text: "My Website"
    }, {
        href: "https://other.site.com",
        text: "Other Site"
    }, {
        'This 3rd element is plain text!"
    }]
```

This would produce:

```html
<a href="https://websitecom">My Website</a>
<span class="sep"></span>
<a href="https://other.site.com">Other Site</a>
<span class="sep"></span>
This 3rd element is plain text!
```

All of this is covered in detail in the [documentation](https://duck.co/duckduckhack/templates_overview#icon-template-group)

### PR DESCRIPTION
**Pull request by altern8tif**
Fixes #1864

### CODE REVIEW

**Comment by altern8tif** [comment]
However, clicking the title brings it back to the search results page instead of the relevant keybase profile.

Is there a way to use the `sourceUrl` `meta` property instead of manually having to reference it in code?

**Comment by moollaza** [comment]
@altern8tif if you specify a `url` property in your `normalize` it will server as the href for the `title` link -- I think that solves your problem?

**Comment by altern8tif** [comment]
@moollaza Thanks! That addresses the issue...

**Comment by moollaza** [comment]
LGTM :+1:

**Comment by moollaza** [comment]
@altern8tif thanks again :smile:

**Pull request merged**
