### PR TITLE
NumberRole: Updating from the goodie repo

### PR DESCRIPTION
**Pull request by mintsoft**
## Description of new Instant Answer, or changes
Fixes: https://github.com/duckduckgo/zeroclickinfo-spice/issues/3109#issuecomment-287474392

I've added a test to Currency to prove the role is hooked up

## People to notify
@moollaza 

---

Instant Answer Page: http://duck.co/ia/view/currency

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
Deployed to Beta...

**Comment by moollaza** [comment]
@mintsoft and magically it all works!

https://beta.duckduckgo.com/?q=convert+499+234+usd+to+cad&ia=currency

**Comment by mintsoft** [comment]
@moollaza It's nice when that happens

**Pull request merged**
