### PR TITLE
Currency: Triggering for Symbol before amount

### LINKED ISSUE #3165: Currency Conversion: Enable Triggering for symbol before amount
### Description

Based on [user feedback](https://github.com/duckduckgo/zeroclickinfo-spice/issues/3139), we have found that `<amount> <symbol> to <symbol>` triggers like in **Screenshot 1**. But doesn't trigger when the query is `<symbol> <amount> to <symbol>` as seen in **Screenshot 2**. 

### Screenshot 1
screen shot 2017-03-02 at 12 05 14 pm

### Screenshot 2
screen shot 2017-03-02 at 12 05 31 pm

In this issue, we need someone to alter the [Currency Conversion IA](http://duck.co/ia/view/currency) to support this type of query. 

## Get Started
- [x] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: http://duck.co/ia/view/currency

### PR DESCRIPTION
**Pull request by BillyBarbaro**
## Description of new Instant Answer, or changes
This PR modifies the regex in Currency Spice to match on queries where the user puts the currency before the amount they wish to convert.  Other changes include:

1. Changed the existing regex to use group names so it was a little easier to read.
2. Modified 1 existing unit test who's expected value was changed by this addition.  (See discussion in the below issue)
3. Removed the alt_amount variable since it was no longer used as a result of 2.
4. Added unit tests to cover the new triggers.

## Related Issues and Discussions
Fixes #3165 

## People to notify
@pjhampton 
@moollaza 

---

Instant Answer Page: https://duck.co/ia/view/currency

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@BillyBarbaro sorry for the long delay here! This one slipped by us. I just merged another currency PR so there's a conflict here. Would you be able to resolve that so I can get this deployed to Beta for testing and merge?

Thanks!

**Comment by BillyBarbaro** [comment]
Sure.  I'll go in and have a look at it.  Hopefully things haven't changed too much!

**Comment by BillyBarbaro** [comment]
@moollaza There's the change.  All units tests are passing!  Tried to do a little to make the module more readable (as I mentioned above).  Let me know what you think.

**Comment by moollaza** [comment]
@BillyBarbaro Thanks! This LGTM 👍

**Comment by bsstoner** [comment]
This was released to production 🚀

**Pull request merged**
