### PR TITLE
Fix missing comma

### PR DESCRIPTION
**Pull request by kewde**
I missed one, woops!

@MrChrisW 

https://duck.co/ia/view/cryptocurrency

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by MrChrisW** [comment]
@kewde Thanks. I should have picked that up on review.

**Comment by kewde** [comment]
Any idea when it gets deployed? Eagerly waiting to see it go live :)

**Comment by mintsoft** [comment]
@kewde It's usually within a few days, normally @moollaza will chime in when it's deployed :+1:

**Comment by moollaza** [comment]
@kewde thanks again for fixing the Cryptocurency Spice! You’ve done a really good job here and we'd like you to help our community tackle the next big challenge - our mission to become the best search engine for programmers: https://duck.co/blog/post/297/help-for-programmers.

When you're ready to move on, please: 

- Create a new Instant Answer to increase our Programming IA coverage

OR

- Test live programming Instant Answers (or those in development) for bugs and suggest improvements 

Detailed instructions explaining how you can help are available at the top of this [page](https://github.com/duckduckgo/duckduckgo/wiki/Programming-IA-Coverage).

Thanks again!

**Comment by moollaza** [comment]
> @kewde It's usually within a few days, normally @moollaza will chime in when it's deployed

Sorry for not replying, this went live a long time ago!

**Pull request merged**
