### PR TITLE
Product Hunt : Fixes #2595 

### LINKED ISSUE #2595: ProductHunt: Tiles have inconsistent height
It looks like we need to set the `tileTitle` variant to `"2line"` so that the card height is consistent.

------
IA Page:  http://duck.co/ia/view/product_hunt 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sevastos

### PR DESCRIPTION
**Pull request by rasikapohankar**
Added tileSnippet to variants for making the tile height consistent. Fixes #2595.
IA Page: https://duck.co/ia/view/product_hunt

### CODE REVIEW

**Comment by daxtheduck** [comment]
@rasikapohankar Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by mattr555** [comment]
@rasikapohankar There's a lot of whitespace under the snippet:

image

Could we change it to `tileTitle: '2line-small'` and `tileSnippet: 'small'`? I think that looks better:

image

**Comment by rasikapohankar** [comment]
@mattr555: Yes I'll change the tileSnippet to small. When we set tileTitle to 2line-small there is more space below the title and when it is only 2line, there's less space. Why is that?

**Comment by mattr555** [comment]
@rasikapohankar I'm not really sure. It also seems like on `2line-small` the text is actually larger than `2line`! @moollaza any thoughts?

At any rate, this looks good, merging :+1:

**Comment by moollaza** [comment]
@rasikapohankar thanks for tackling this! 

> It also seems like on 2line-small the text is actually larger than 2line! @moollaza any thoughts?

@mattr555 that's because `2line-small` isn't actually one of the accepted classed so it's not applying any of the rules I think.

FWIW these are the supported classes:

```
tileTitle: {
    '1line': "tile__title--1",
    '1line-large': "tile__title--1lg",
    '2line': "tile__title--2",
    '3line': "tile__title--3",
    '4line': "tile__title--4",
    '3line-small': "tile__title--3sm",
    '3line-large': "tile__title--3lg"
}
```

The changes made should be good :+1:

**Comment by rasikapohankar** [comment]
@mattr555 @moollaza : Just curious, does it take time for the new things merged to be updated in production?

**Comment by MrChrisW** [comment]
Hey @rasikapohankar, the change will become active once a [new release](https://github.com/duckduckgo/zeroclickinfo-spice/releases) is created generally this happens once every week. :+1:

**Comment by rasikapohankar** [comment]
@MrChrisW : Thanks!

**Pull request merged**
