### PR TITLE
CourseBuffet Instant answer

### PR DESCRIPTION
**Pull request by rubydubee**
**What does your instant answer do?**
Displays relevant free online college courses

**What problem does your instant answer solve (Why is it better than organic links)?**
There are over 1200 free college courses available but they are created by over 200 universities and spread over a dozen platforms. A user can go to each provider’s site or go to a site that aggregates courses. Both of these methods are time consuming. The aggregation sites cut down on the time a little bit but the user is still faced with lots of courses to look at with little direction and has to figure out which courses are directly comparable and which order to take courses. 
CourseBuffet is better. We look at each course individually and then classify it under a subject, generic title and level/year that is roughly equivalent to what the course would be at a US university. This enables users to know which courses are directly comparable even if their title is different. No more time consuming searching and guessing! This also allows them to get a good idea of what order to take courses even if they are taking courses from multiple providers/platforms.

**What is the data source for your instant answer? (Provide a link if possible)**
CourseBuffet(http://www.coursebuffet.com) - We(CourseBuffet) receive the data from providers(MOOCs) then we use our own classification system to create our own database. This means a human looks at every course and analyses it. This gives users the most relevant results.

**Why did you choose this data source?**
Our database produces better results and saves users’ time and lessens their confusion.

**Are there any other alternative (better) data sources?**
No - There are other sites that aggregate courses from different MOOCs, but does not properly classify it.

**What are some example queries that trigger this instant answer?**
"computer science course", "Human Physiology", "udacity computer science"

**Which communities will this instant answer be especially useful for? (gamers, book lovers, etc)**
People trying college education for the first time and people who are lifelong learners

**Is this instant answer connected to a DuckDuckHack [instant answer idea](https://duck.co/ideas)?**
Not that we could find. We were approached by DDG to create this instant answer

**Which existing instant answers will this one supersede/overlap with?**
None that we could find

**Are you having any problems? Do you need our help with anything?**
In development environment, it seems like the `text` template is not behaving properly on Firefox and IE, the link to the individual tile does not go anywhere, It works on Chrome/Safari/Opera. I tried running the `github_search` answer on my dev server and it had the same issue, any help on this will be great!

****Note:** Please attach a screenshot for new instant answer pull requests, and for pull requests which modify the look/design of existing instant answers.
screen shot 2014-07-05 at 1 21 10 pm
## Checklist

Please place an 'X' where appropriate.

```
[X] Added metadata and attribution information
[X] Wrote test file and added to t/ directory
[] Verified that instant answer adheres to design guidelines(https://github.com/duckduckgo/duckduckgo-documentation/blob/master/duckduckhack/styleguides/design_styleguide.md)
[X] Tested cross-browser compatibility
Notes: 
1. The Design Guidelines seem out of date, but I haven't added any special style elements of my own, it looks consistent with the DDG design.
2. Having issue while testing on the development environment as mentioned before, so not marking Firefox/IE as tested.

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        [X] Google Chrome   
        [] Firefox         
        [X] Opera           
        [] IE 10           

    - Windows 7
        [X] Google Chrome   
        [] Firefox         
        [X] Opera           
        [] IE 8            
        [] IE 9            
        [] IE 10           

    - Windows XP
        [] IE 7            
        [] IE 8            

    - Mac OSX
        [X] Google Chrome   
        [] Firefox         
        [X] Opera           
        [X] Safari          

    - iOS (iPhone)
        [X] Safari Mobile   
        [] Google Chrome   
        [] Opera           

    - iOS (iPad)
        [] Safari Mobile   
        [] Google Chrome   
        [] Opera            

    - Android
        [] Firefox         
        [X] Native Browser  
        [] Google Chrome   
        [] Opera
```

### CODE REVIEW

**Comment by jagtalon** [comment]
@rubydubee A few comments!

- Is the CSS still being used?
- I think it's better to use the "media" template like in bbc.js:

```javascript
templates: {
    group: "media",
    item_detail: false,
    detail: false,
    options: {
        variant: 'video',
        moreAt: true
    }
}
```

because it gets messed up on mobile (see the gap between image and title):
screen shot 2015-01-06 at 11 14 14 am

How it would look after applying the code above:
screen shot 2015-01-06 at 11 13 58 am

CC @abeyang

**Comment by jagtalon** [comment]
Thanks again!

**Comment by jagtalon** [comment]
@rubydubee our designer @abeyang says this is good. Please update to a media template and it should be ok to merge.

**Comment by rubydubee** [comment]
great! will do.

**Comment by jagtalon** [comment]
That's awesome! Excited for this.

**Comment by rubydubee** [comment]
@jagtalon updated the code with the exact media template, the css is only needed for title, because by default, the title is getting wrapped into one line and I wanted to have at least 2 lines. let me know if that's fine?

**Comment by rubydubee** [comment]
one question: can we also add 2 more keywords: "course online" and "courses online"?  the autocomplete dropdown mostly show results like "computer science courses online" when i start typing "computer science course".

**Comment by jagtalon** [comment]
@rubydubee 

- I think that's fine--I don't see the need for `!important` though.
- You absolutely can. Please add those to the tests though.

**Comment by rubydubee** [comment]
@jagtalon 
* added those 2 triggers with tests.
* removed !important

**Comment by jagtalon** [comment]
:+1:

**Comment by rubydubee** [comment]
Great, thanks! When will it go live? :)

**Comment by zekiel** [comment]
@rubydubee  Should be 2-3 days, depending on the open source activity. Congrats and thanks again for this!

**Comment by jagtalon** [comment]
@rubydubee @zekiel it's live! https://duckduckgo.com/?q=computer+science+online+courses&ia=onlinecourses

**Comment by jkanarek** [comment]
Does the API provide schedule info? It looks like some of these courses are very time dependent (i.e. https://www.coursera.org/course/acctcostanalysis) while others are ongoing? It's be great to show dates when these are time restricted and ongoing when these are recorded already.

**Comment by rubydubee** [comment]
@jkanarek I do have start dates for the courses, but it needs to stay up to date with the course providers. I am working on making it stable and auto update the course schedules. Will add it to the answer once i have it.

**Pull request merged**
