### PR TITLE
IndegoPHL: Move to text template + footer, shrink tile size

### PR DESCRIPTION
**Pull request by moollaza**
- Move to built-in `text` template
- Shrink tile sizeto 11.5 x 11.5em (144x144px)

to @abeyang 

/cc @AcriCAA @marianosimone @jagtalon 

@marianosimone can you please make the same changes to the BayAreaBikeSharing PR -- seeing as it also doesn't have the need for extra footer space as it doesn't have update times

-----

Result:

1____projects_zeroclickinfo-spice__perl__and_bike_share_phl_at_duckduckgo

### CODE REVIEW

**Comment by marianosimone** [comment]
@moollaza nice improvement! (keeping it simple :D)

The only problem I see with this is that we are not taking advantage of the extra space to fit 3 lines for the title:

lines

@moollaza @jagtalon any way to fix that?

PS1: It really seems like we could use having shared CSS for this kind of stuff :D
PS2: Shouldn't we take some of this CSS cleanups to the NY one as well?

**Comment by moollaza** [comment]
>The only problem I see with this is that we are not taking advantage of the extra space to fit 3 lines for the title:

Good catch. That’s a simple fix, we can use the template variants to adjust for a 3rd line:

```
variants: {
    titleTitle: "3line"
}
```

I'll adjust that soon.

---

>PS1: It really seems like we could use having shared CSS for this kind of stuff :D

I think this would be possible if we create a placeholder `BikeSharing.pm package` -- I don't remember if DuckPAN supports the shared assets though. If you're interested, you can take a look at Sports IAs but for now I don't mind the duplication. It’s not a ton of code, but obviously simplifying is best.

> PS2: Shouldn't we take some of this CSS cleanups to the NY one as well?

No reason not to :) I just wanted to ping you about BayArea because you had a PR open so I figured we could get that in and I can merge. If you'd like to tackle both in 1 PR I can merge Bay Area now.

**Comment by marianosimone** [comment]
@moollaza using `tileTitle` prop works great (warning, you said `titleTitle`, so don't copy&paste it ;)

**Comment by moollaza** [comment]
> @moollaza using tileTitle prop works great (warning, you said titleTitle, so don't copy&paste it ;)

whoops! I've adjusted my previous comment

**Comment by AcriCAA** [comment]
Sorry guys, I've been traveling. @moollaza need me to make any changes or
do you got it on your end?

**Comment by moollaza** [comment]
>Sorry guys, I've been traveling. @moollaza need me to make any changes or do you got it on your end?

@AcriCAA no worries, I've got it all covered :+1:

**Comment by moollaza** [comment]
I've now moved to a 3-line title. This required bumping the height `0.2ems` to `11.7em`


bike_share_philadelphia_at_duckduckgo

**Comment by moollaza** [comment]
Spoke to Abe final adjustments are in:

bike_share_philadelphia_at_duckduckgo

**Pull request merged**
