### PR TITLE
MetaCPAN: Fixes #3060 - strip second form of query from Javascript query var if

### LINKED ISSUE #3060: MetaCPAN: colon(s) in module name break "More at MetaCPAN" link
To reproduce

- search for any module with :: - example `cpan MIDI::Tab` 
- click on "More at MetaCPAN" link
- Note the query string has been double encoded - `%3A` for the colon has become `%253A` - breaking the search on MetaCPAN after clicking through.

link presented for MetaCPAN with above search example
`https://metacpan.org/search?size=50&search_type=modules&q=MIDI%253A%253ATab%252FMIDI%2520Tab`

------
IA Page:  http://duck.co/ia/view/meta_cpan 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sahildua2305

### PR DESCRIPTION
**Pull request by deserted**
## Description of new Instant Answer, or changes
Fix up Javascript query var to contain correct module name for link to MetaCPAN, also moves no results check to earliest point.

## Related Issues and Discussions
Fixes #3060 

## People to notify
@sahildua2305 @GuiltyDolphin 

---

Instant Answer Page: https://duck.co/ia/view/meta_cpan

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by sahildua2305** [comment]
@tagawa can you please deploy this to beta?

**Comment by tagawa** [comment]
Sure @sahildua2305 - it's now on beta: https://beta.duckduckgo.com/?q=cpan+MIDI%3A%3ATab&ia=software

Looks like a good fix to me (thank you again @deserted)

**Comment by deserted** [comment]
cheers @tagawa :)

**Comment by moollaza** [comment]
@deserted @tagawa @sahildua2305 Thanks! This LGTM :+1:

**Comment by deserted** [comment]
this change is working on beta, but still not on live, is it still waiting for deployment or is this due to differences in beta and live environments? just want to confirm before I open an issue against behaviour on live

**Pull request merged**
