### PR TITLE
Lastfm (TopTracks): Port to new spice api

### PR DESCRIPTION
**Pull request by killerfish**
@jagtalon I didnt include the css changes as with #1301, so lmk know your thoughts, comparing this. Also we need a better sign for ~ (it represents listeners, the play button was for playcount). Also should we limit result to 20? or what value?
toptracks

### CODE REVIEW

**Comment by jagtalon** [comment]
@killerfish Can "United States" be in the "Showing 49 Tracks" line?

**Comment by jagtalon** [comment]
@moollaza @killerfish I just remembered that we weren't allowed to use the images! Dang, I really like this design. Maybe we should contact them again.

**Comment by jagtalon** [comment]
I think we can do a list view here and would still work without images. Will get back to you soon!

**Comment by jagtalon** [comment]
Closing for now for reasons described in https://github.com/duckduckgo/zeroclickinfo-spice/pull/1300#issuecomment-71098300

**Comment by jagtalon** [comment]
@killerfish since we can't do images, would you be interested in making this something like whois?

https://duckduckgo.com/?q=whois+duckduckgo.com&ia=whois

screen shot 2015-02-19 at 12 56 32 pm

**Comment by killerfish** [comment]
Its just we cant use images yes? ill check out this one plus something i had in mind

**Comment by jagtalon** [comment]
@killerfish yeah unfortunately we can't use images. :/

**Comment by jagtalon** [comment]
@killerfish so would you be interested in making it look like WhoIs? :)

**Comment by killerfish** [comment]
Sure!

**Comment by killerfish** [comment]
@jagtalon isnt there are a way we could represent all tracks without using the list view? It just doesnt seem fit right with me (there is a long list of tracks, i'd want to atleast include half, which just look odd with list view).

**Comment by moollaza** [comment]
@killerfish we actually just added in a new Template group called `list` which is designed to be used with the record_template. It will allow the initial display height to be controlled and adds a "show more" button so it will expand. How long is the list of songs?

**Comment by killerfish** [comment]
@moollaza 49 (in this example) :D

**Comment by moollaza** [comment]
@killerfish oh wow. How about we limit it to show the first 10/15/20 (whatever looks best). I think being able to see the top 10 tracks is most important. If you really need to see the 48th top track, you can click through to the Last.FM ;)

**Comment by killerfish** [comment]
@moollaza do we have list view documented?

**Comment by moollaza** [comment]
@killerfish unfortunately, not yet but here's an example: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1088#issuecomment-89651349

Your `data` obj needs `list` property (like `record_data` for an infobox), which should be an array of objects. You then need to provide a template to `list_content` which will take each object in the `list` array as its context and render an `<li>` filled with the output from your `list_content` template.

**Comment by jagtalon** [comment]
Hey, @killerfish! Still interested in doing the list view? :neckbeard:

**Comment by moollaza** [comment]
Closing. This is stale. Happy to reopen

**Pull request closed without merging**
