### PR TITLE
Add new Instant Answer: Coderwall

### PR DESCRIPTION
**Pull request by motersen**
**What does your Instant Answer do?**
Display information about a coderwall.com user

**What problem does your Instant Answer solve (Why is it better than organic links)?**
It helps to ensure a specific user is found (by displaying location) and provides a direct link to the user's profile

**What is the data source for your Instant Answer? (Provide a link if possible)**
[Coderwall API](https://coderwall.com/api)

**Why did you choose this data source?**
It is the only one that i know of.

**Are there any other alternative (better) data sources?**
No

**What are some example queries that trigger this Instant Answer?**
`coderwall jagtalon`, `motersen coderwall`

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
programmers

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
[Yes](https://duck.co/ideas/idea/760/coderwall-instant-answer)

**Which existing Instant Answers will this one supersede/overlap with?**
None that i know of.

**Are you having any problems? Do you need our help with anything?**
I initially wanted to limit the display to three badges by setting `to` in `{{#each}}` to a variable determined in `normalize`. But I could not get it working.

**What are the terms of use for the API? Will DuckDuckGo need specific authorization (e.g. an API key)? Are there any costs associated with API usage?**
No API key needed, no terms of use known. Therefore: no costs.

**Where did you hear about DuckDuckHack? (For first time contributors)**
DuckDuckGo

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
[coderwall jagtalon](http://i.imgur.com/7Llh3lL.png)

## Checklist
Please place an 'X' where appropriate.

```
[X] Added metadata and attribution information
[X] Wrote test file and added to t/ directory
[] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[X] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
[] Tested cross-browser compatibility

### CODE REVIEW

**Comment by jagtalon** [comment]
@motersen @mattr555 @moollaza I wonder if we can go with a Twitter-style template here?

screen shot 2015-01-01 at 2 30 35 pm

**Comment by motersen** [comment]
@jagtalon Good Idea! Initially I wanted to go for something like this too but sadly coderwall does not provide any way to obtain profile pictures (that I know of). Neither trough the API nor with any generic url.
What about something like this?
cw_3c0fe8

**Comment by jagtalon** [comment]
@motersen Yeah this can be tricky--will just consult a designer to see what we can do with the info that we have!

**Comment by jkanarek** [comment]
@motersen The Coderwall endpoint has been updated to allow support for photo thumbnail and the about snippet, check out https://coderwall.com/josh.json/?full=true for an example. 

It'd also be cool to add links to their twitter profile and their github info as well as title and company.

**Comment by jagtalon** [comment]
@jkanarek sweet! Thanks

**Comment by zekiel** [comment]
@motersen Now that they have images available, we can use the current twitter design for this: https://github.com/duckduckgo/zeroclickinfo-spice/tree/master/share/spice/twitter

**Comment by jagtalon** [comment]
@motersen I think I like the about more than the badges in https://github.com/duckduckgo/zeroclickinfo-spice/pull/1360#issuecomment-68495624. @moollaza @abeyang what do you think?

**Comment by abeyang** [comment]
@jagtalon  Yup, let's go with the twitter template for this, as @zekiel mentioned.

**Comment by moollaza** [comment]
ping! @motersen would you be interested in switching this to mimic the Twitter desing?

**Comment by motersen** [comment]
@jagtalon @moollaza Sorry for being inactive so long.
@jkanarek @zekiel Thanks for your updates and suggestions! I'll change this to twitter design soon.

**Comment by jagtalon** [comment]
@motersen no worries--looking forward to it!

**Comment by moollaza** [comment]
@motersen it's no problem at all, just making sure all our PRs are moving along and our devs are happy :smiley:

**Comment by moollaza** [comment]
@motersen hey there, just checking in again are you still interested in finishing this one up? Or would you like us to have someone else from the community make the final additions?

We're happy either way, I'd just like to see this one go live!

**Comment by moollaza** [comment]
ping! @motersen just checking in -- are you still interested in finishing this one up?

**Comment by moollaza** [comment]
Closing. @motersen if you'd like to finish this up later, please let us know and we'll happily re-open the PR.

**Comment by motersen** [comment]
I'm really sorry for delaying this for so long @moollaza . Well, I finally found the time to (hopefully) finish it.
I've tried to mimic the twitter-spice design & feel but please make suggestions or corrections as I'm not so sure about the CSS and layout anyway.
I have included profile pictures. I've noticed that some profile pictures, like [jagtalon's](https://coderwall-assets-0.s3.amazonaws.com/uploads/user/avatar/28555/8eb5461f8bbecfbe25145b719ad8720b.jpeg),
have a white frame. Initially I cropped that away with `object-fit:none` but most pictures seem to be complete and I wasn't sure about compatibility anyway.
If the API supplies github or twitter accounts, links to those are displayed next to the location.
Instead of badges the IA displays up to 140 characters of the description (about), as suggested by @jagtalon. I think this looks much cleaner and keeps the IA box rather small as it should be.
@jkanarek I have not included the title and company fields as they are rarely used and often mentioned in the description.
So here is how it looks like:
cw-f5c9d9ad99f6-eyesno
cw-f5c9d9ad99f6-jagtalon

I'm looking forward to your feedback!

**Comment by moollaza** [comment]
@motersen sorry for the delay! I just tried to re-open the PR but GitHub won't let me -- have you deleted your branch? Could you make a new PR or re-create the branch you used for this?

**Comment by moollaza** [comment]
We also now have a brand new `Icon` template group which can be used here to build exactly this layout without the need for any CSS or custom templates.

If you re-open the PR, I'd be happy to convert this to use the new template which should simplify things a lot!

**Comment by motersen** [comment]
@moollaza Unfortunately I can't reopen this PR either. The problem seems to be that I force-pushed my updates to keep the commit history tidy. This seems to be a known problem isaacs/github#361. I had to open a new PR now: #1914

I'd be happy if you could undertake the template conversion. I have spend most of the time for this on design and it's neither what I like best nor what I'm best at :wink:

**Pull request closed without merging**
