### PR TITLE
unescape html entities in alternative to IA

### LINKED ISSUE #1305: AlternativeTo: Should decode entities
screen shot 2014-12-02 at 1 42 31 pm

https://duck.co/ia/view/alternative_to

### PR DESCRIPTION
**Pull request by marianosimone**
this is a tmp fix until some utility for unescaping is in place

fixes #1305

---
IA Page: https://duck.co/ia/view/alternative_to
Maintainer: @vikashvverma

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@marianosimone thanks for this! The DDG util library is actually open source -- would you like to add this code over there?

https://github.com/duckduckgo/duckduckgo-utils/blob/master/util.js

I think @jagtalon and I implemented a fix for this in a similar fashion that takes advantage of the DOM for the Couprex IA: https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/couprex/couprex.js#L8

**Comment by marianosimone** [comment]
@moollaza I'd love to! Let me get back to that ASAP.

One question, though.... which path would you follow. I think the fix at Couprex IA is more complete and straightforward, but maybe not as safe when dealing with untrusted data and a bit more hacky (as it creates new DOM elements and manipulates them).

**Comment by vikashvverma** [comment]
@moollaza I agree with @marianosimone. `Couprex IA` deals with untrusted data by creating DOM and then getting the content.

**Comment by moollaza** [comment]
@marianosimone @vikashvverma 

According to MDN, the `document.implementation` approach is actually a "safe" way: https://developer.mozilla.org/en-US/Add-ons/Code_snippets/HTML_to_DOM

@jagtalon where to you find out about this approach?

**Comment by marianosimone** [comment]
@moollaza awesome find! anyhow, we can follow up [here](https://github.com/duckduckgo/duckduckgo-utils/issues/8) and change this PR to just use the util

**Comment by jagtalon** [comment]
@moollaza @MariagraziaAlastra yes, I think that's the right place!

**Comment by marianosimone** [comment]
@jagtalon @moollaza that one got merged :D you know how long it takes until that gets released? I'll update this PR as soon as that's live

**Comment by moollaza** [comment]
> you know how long it takes until that gets released?

@andrey-p do you know when the changes to DDG Utils will go live? I assume the next time Brian does a release?

**Comment by andrey-p** [comment]
@moollaza @marianosimone Sorry about the late reply - there was a release yesterday so this should now be ready to use!

**Comment by marianosimone** [comment]
@moollaza @andrey-p thanks! Seems to be working fine :D

**Comment by moollaza** [comment]
@marianosimone This LGTM :+1:

Thanks again for taking the time to contribute! We really appreciate it :smiley:

We finally solved the entities bug, 2 years later ;)

**Pull request merged**
