### PR TITLE
Reviving old branch - Ideas/wikinews

### PR DESCRIPTION
**Pull request by iambibhas**
I took one of the branches mentioned in #1535 and worked on it a little. Updated the frontend to latest format and added handlebar template. This is how it looks - 

wikinews

I'm looking for feedback on if what I did was right, if not what to do to improve. Then I can work on the other branches.

### CODE REVIEW

**Comment by iambibhas** [comment]
Looks like travis is failing while building `SpiceBundle/OpenSourceDuckDuckGo`.

**Comment by moollaza** [comment]
@iambibhas this is great start. But I would say the best way to handle this is to produce a tile view similar to our current [News IA](https://duckduckgo.com/?q=drake+news&ia=news).

We actually have a News template which you can use, but it's not documented quite yet...However our News Spice is open source and you can see the code here: https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/news/news.js

The most important piece is that we're using the `news_item` template, which requires the following properties to be defined:

```json
source: "Hip-Hop Wired",
excerpt: "<b>Drake</b> is currently blowing his money at Florence Griffith Joyner speeds in Dubai, and he's invited the world to join him-sort of.",
syndicate: "Yahoo",
date: "1426184717",
url: "http://hiphopwired.com/2015/03/12/drake-is-running-a-muck-in-dubai-photos/",
relative_time: "5 hours ago",
title: "<b>Drake</b> Is Running A Muck In Dubai [PHOTOS]"
```
> That's a sample API response which our internal News API provides to us

So if you add in a `normalize` function that defines those properties and passes them to the `news_item` template, you should be able to achieve an identical look to our News IA!

**Comment by iambibhas** [comment]
That sounds like a plan. But I dont think I can get an excerpt out of the wikinews api. So it'd be just the title and the timestamp. I'll check again if there is a way.

**Comment by iambibhas** [comment]
Also, can you please point me at how to change the `spice to` if there is a `remainder`? Then I can turn this into a search based IA too. Just like the news one. Right now it just shows the latest 10 news items.

**Comment by moollaza** [comment]
>Also, can you please point me at how to change the spice to if there is a remainder?

@iambibhas checkout https://duck.co/duckduckhack/spice_basic_tutorial#define-the-api-call -- most Spice IA's do this so there's plenty of examples in the repo :)

**Comment by moollaza** [comment]
>I dont think I can get an excerpt out of the wikinews api.

That would be pretty disappointing. If that's the case, then I would suggest you simplify things and use the `text` template with a footer that indicates the source and time to mimic the look of the News IA.

A design similar to the HackerNews Spice would work: https://duckduckgo.com/?q=hacker+news+perl&ia=social

**Comment by iambibhas** [comment]
`text` template group works fine.

wikinews

BTW, I pulled the master branch to this branch when I saw an error that it couldn't find the text template(I provided name instead of group of the template). Was that a good thing or should I revert back?

**Comment by moollaza** [comment]
>BTW, I pulled the master branch to this branch when I saw an error that it couldn't find the text template(I provided name instead of group of the template). Was that a good thing or should I revert back?

I'm not quite sure what you mean, but specifying `group: 'text'` should be good -- or simply `item: 'text_item'` -- you'll need to disable the `item_detail` though, so that clicking opens the link, rather than a detail pane.

**Comment by iambibhas** [comment]
Yeah, I did that. and it's working perfectly. But I pulled updates from master branch to this branch. so now there is a commit with all the updates since the last time this branch was created from master.

**Comment by iambibhas** [comment]
Any idea how to fix this travis error? It's really bothering me.

**Comment by moollaza** [comment]
@iambibhas I think the branch you're using has an outdated dist.ini file -- please rebase the branch on master.

**Comment by iambibhas** [comment]
@moollaza did a rebase, then pull and push. Is what happened above expected? I try to stay away from rebase if possible. So not sure if it's expected.

**Comment by moollaza** [comment]
Hmm might be better to cherry-pick your commits onto a clean fork/branch. I "think" this PR is OK, (could confirm with a diff between master and HEAD) but it's always a little concerning to see that a PR of 4000+ commits modifies 932 files :fearful:

**Comment by iambibhas** [comment]
@moollaza I think because this branch is a year old, this happened. Whichever way you try to update ideas/wikinews with changes from master, this will happen. and the PR is against the `ideas/wikinews` branch of the upstream, not the master. So if you merge it, then merging it back with master should be cleaner. 

I could just take this spice and it's file and make the changes to the master itself and send a PR. And then you can just delete the stale branch.

**Comment by iambibhas** [comment]
If I create a PR against the master branch, then this is what happens thanks to the rebase

**Comment by moollaza** [comment]
>I could just take this spice and it's file and make the changes to the master itself and send a PR. And then you can just delete the stale branch.

Perfect!

>I guess, from now on, whenever working on a stale branch, it'd be a good idea to rebase master first and send PR against the master branch directly.

Sounds good!

**Comment by iambibhas** [comment]
Opened #1642. Should close this PR.

**Pull request closed without merging**
