### PR TITLE
Quandl::Fundamentals - updated UI and using moment

### PR DESCRIPTION
**Pull request by iambibhas**
Moved from `base` to `text` group.

Before 

After

### CODE REVIEW

**Comment by moollaza** [comment]
@iambibhas thanks! The Quandl design is actually intended to have the lower-positioned subtitle. It's borrowed from our Stocks design (https://duckduckgo.com/?q=aapl&ia=stock) which we're going to build a template for very soon, so the design should remain as it is.

The moment.js updates are great though. Please remove the design fixes and we can merge this.

**Comment by iambibhas** [comment]
@moollaza oh. didn't realize that. Sorry. :| I'll remove the design changes.

**Comment by moollaza** [comment]
>oh. didn't realize that. Sorry. :| I'll remove the design changes.

@iambibhas it's no problem :) -- thanks for updating!

**Comment by iambibhas** [comment]
Current design -

screenshot from 2015-08-29 23 00 25

**Comment by moollaza** [comment]
LGTM :+1: 

Thanks a lot @iambibhas

**Pull request merged**
