### PR TITLE
Change forecast endpoint to darksky.net

### PR DESCRIPTION
**Pull request by b2ddg**
Updating the forecast.io endpoint to darksky.net.

@tommytommytommy 
cc @bsstoner 
https://github.com/duckduckgo/zeroclickinfo-spice/issues/3008

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by nilnilnil** [comment]
Do we have a testing methodology for these types of changes? Not 100% sure they're necessary; but curious.

**Comment by nilnilnil** [comment]
👍 from my PoV though.

**Comment by b2ddg** [comment]
@nilnilnil I think it should get picked up by the example query monitors @kablamo set up. We could include something like the monitor as part of the unit testing before merge.

**Comment by tommytommytommy** [comment]
👍 I deployed it locally and it looks good. Going to hold off merging until we hear back about API access.

**Comment by tommytommytommy** [comment]
Also @b2ddg is going to update the Rain API simultaneously because it uses the same endpoint (just adding here so we don't forget).

**Pull request merged**
