### PR TITLE
Updated rx_info instant answer to use new media group

### PR DESCRIPTION
**Pull request by medicosconsultants**
---

https://duck.co/ia/view/rx_info

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@medicosconsultants thanks for the PR! It looks like there's a lot hapenning in here :smile: Please provide an explanation of the changes and rationale so everyone understands what's going on here!

**Comment by moollaza** [comment]
@medicosconsultants as well, it looks like the tests are now failing (https://travis-ci.org/duckduckgo/zeroclickinfo-spice/builds/115414988) -- please update them to pass and then we can deploy this to beta.duckduckgo.com for testing@

**Comment by jdorweiler** [comment]
@medicosconsultants are you still working on this?

**Comment by moollaza** [comment]
This PR is being closed due to inactivity. If you're still interested in finishing, please let me know and I'll gladly re-open it for you!

**Pull request closed without merging**
