### PR TITLE
currency.css: Hovering / clicking on mobile has ugly underline.

### PR DESCRIPTION
**Pull request by jagtalon**
screen shot 2015-02-26 at 2 23 54 pm

screen recording 2015-02-26 at 02 18 pm

### CODE REVIEW

**Comment by moollaza** [comment]
Looks like our CSS is causing this..

2015-02-26_14h31_30

@sdougbrown should we disable for this IA or adjust the DDG CSS?

**Comment by moollaza** [comment]
Whoops, I thought this was an issue, not a PR. Well that certainly fixed it. I'm not sure if we're going to need to adjust this elsewhere though...

**Comment by moollaza** [comment]
LGTM :+1:

**Comment by jagtalon** [comment]
@moollaza sorry I kinda have a weird layout for currency--I should probably refactor it somehow

**Pull request merged**
