### PR TITLE
New Spice: ProductHunt

### PR DESCRIPTION
**Pull request by sevastos**
**What does your Instant Answer do?**
Searches ProductHunt's submissions.

**What problem does your Instant Answer solve (Why is it better than organic links)?**
Searching for products and being able to go to PH's comments and the product's website.

**What is the data source for your Instant Answer? (Provide a link if possible)**
Official search API powered by Algolia [src](https://github.com/producthunt/producthunt-api/wiki/Product-Hunt-APIs#algolia-search-api)

**Why did you choose this data source?**
Supports keyword search and Algolia is used on HN's spice as well.

**Are there any other alternative (better) data sources?**
There is a Rest API, but it doesn't support keyword search.

**What are some example queries that trigger this Instant Answer?**
produchunt duck

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
People interested in startups, tech & apps.

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
Yes. https://duck.co/ideas/idea/4880/product-hunt

**Which existing Instant Answers will this one supersede/overlap with?**
None existing.

**Are you having any problems? Do you need our help with anything?**
All good.

**What are the terms of use for the API? Will DuckDuckGo need specific authorization (e.g. an API key)? Are there any costs associated with API usage?**
Producthunt provides a public API key for free.

**Where did you hear about DuckDuckHack? (For first time contributors)**
While digging through duckduckgo site.

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
Screenshot of ProductHunt spice

## Checklist
Please place an 'X' where appropriate.

[X] Added metadata and attribution information
[X] Wrote test file and added to t/ directory
[X] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[X] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
[X] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 10

    - Windows 7
        [X] Google Chrome
        [X] Firefox
        [] Opera
        [] IE 8
        [X] IE 9
        [] IE 10

    - Windows XP
        [] IE 7
        [] IE 8

    - Mac OSX
        [X] Google Chrome
        [X] Firefox
        [] Opera
        [X] Safari

    - iOS (iPhone)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - iOS (iPad)
        [X] Safari Mobile
        [X] Google Chrome
        [] Opera

    - Android
        [] Firefox
        [] Native Browser
        [X] Google Chrome
        [] Opera

### CODE REVIEW

**Comment by jagtalon** [comment]
@sevastos sweet! we're going to be taking a look at it soon!

**Comment by moollaza** [comment]
@sevastos thanks a lot for contributing, this is an awesome Instant Answer! The templates make this look really good and the code is really straightforward. Great job!

I'll test this a bit more but I'm pretty happy with it right now. @abeyang can we get a design sign-off? My only thought is that the footer could use a little more padding between the url and the votes.

**Comment by sevastos** [comment]
@moollaza great, thanks. Indeed the domain should have `margin-bottom: 0.25em;` I missed it, good catch. Unless @abeyang wants otherwise, I'll push that change.

**Comment by abeyang** [comment]
@sevastos looking good! Here are some css tweaks -- please remove the `<a>` tag from the html for comments, as the entire tile is clickable and should be going to the same place.

``` css
.tile--producthunt .tile__title {
	font-weight: 400;
	margin-top: -0.2em;
	margin-bottom: 0; /* remove margin-bottom */
}

.tile--producthunt .tile__content {
	margin-top: 7px;
	margin-bottom: 10px;
}

.tile--producthunt .tile__domain {
	color: #aaa;
}

.tile--producthunt .tile__body.has-foot {
	padding-bottom: 0.7em;
}

/* actually let's remove the <a> altogether */
.tile--producthunt a {
	color: #666;
}
```

Your end result should look something like this:
screen shot 2015-02-06 at 1 52 21 pm

Thanks! LMK if you have any questions!

**Comment by sevastos** [comment]
@abeyang thanks for the feedback :)
I updated the styling, however I have a slight objection about the comments link.
 
 For consistency and due to the similarity of the cases, I used HN's spice ([example](https://duckduckgo.com/?q=hn duck)) as a base for the design.
 In both HN and ProductHunt the comments usually worth half the submission's value imo, so I usually open both the submission url and the comments at the same time, so it's pretty handy to have both urls there.

There was an issue with the middle click for opening to new tab which I just fixed and probably messed your experience with it, but let me know what you decide.

Also, in order have consistency I could apply the design adjustments on both (HN & PH) spices unless somebody minds.

**Comment by moollaza** [comment]
@sevastos I agree the the separate comments link is useful. In the case of Reddit the tile link goes to the comments, but for HN and PH the item and the discussion aren't usually the same (e.g. an HN thread points to a website, but the comments are always on HN)

@abeyang Maybe we should keep the `<a>` but update the colour so that it's grey instead of blue?

------

>Also, in order have consistency I could apply the design adjustments on both (HN & PH) spices unless somebody minds.

That would be great! Whatever we decide here should be applied to HN as well

**Comment by moollaza** [comment]
@sevastos apologies for the delay, I just gave this another look and it it still needs a couple adjustments because right now the `tile__foot` is being cut off.

We haven't documented these yet (coming soon!) but we have many `variants` available for the `title` and `footer`. Let's add them in like so:
```js
options: {
    ...
},
variants: {
    tileTitle: "2line-small",
    tileFooter: "2line"
}
```

The you can update the css to look like this:

```css
.tile--producthunt  .tile__body.has-foot {
    height: 14em;
}

.tile--producthunt .tile__domain {
    color: #aaa;
    margin-bottom: 0.25em;
}

.tile--producthunt .tile__votes {
    color: #333;
}

.tile--producthunt a {
    color: #666;
}

.dark-header .tile--producthunt a {
    color: #999;
}
```

and this IA should be good to go!

**Comment by abeyang** [comment]
@sevastos my bad, didn't realize the links are going to separate places. Can we try this: let's leave the **comment link** as the regular blue (as it's doing for the HN tiles), but on *mouse-over*, can we **underline the title**? LMK if you need css help with this.. just want to try to see if that helps distinguish between tile clicks and comment clicks. Thanks!

**Comment by sevastos** [comment]
@moollaza thanks, your changes fixed it.

@abeyang sure, here is the result using:
```css
.tile--producthunt:hover .tile__title {
    text-decoration: underline;
}
```
While hovering tile only:
while hovering tile only
While hovering the comments link:
while hovering comments link
Was that what you were having in mind?

I think it looks a bit crowded with the underlining. To remove the underline of the title while hovering the comments link will require javascript (unless I missed something) which ideally is used to the minimum for speed.

Currently bolding the tile border works semantically like an underlining for the whole tile, but I understand your concern about making it more distinct. I tried to check some other IAs for similar situation and their solution but didn't find anything helpful in my limited search.

**Comment by moollaza** [comment]
@sevastos mind pushing your updates to the PR?

**Comment by sevastos** [comment]
Sure, pushed, let me know if you want the link underlining included.

**Comment by moollaza** [comment]
@sevastos yes, please, we'd like to play around with it.

**Comment by moollaza** [comment]
thanks!

**Comment by sevastos** [comment]
Cheers :+1:

**Comment by moollaza** [comment]
@sevastos looks like you might be missing some CSS? https://ddh8.duckduckgo.com/?q=producthunt+remote&ia=products

**Comment by sevastos** [comment]
I have everything pushed, locally works fine for the same search. Looking into it now...

**Comment by sevastos** [comment]
It seems on ddh8 the .tile__foot--2 is not added correctly per the item variants.

**Comment by moollaza** [comment]
>It seems on ddh8 the .tile__foot--2 is not added correctly per the item variants.

Yes, I noticed that as well. Trying to fix it...

**Comment by sevastos** [comment]
The variants are missing from product_hunt.js on ddh8 but you can see them present on this PR.

I'm not sure how your staging machines work, but I did a rebase and forced-push so if the staging machine is trying to merge this PR with the previous version it could have conflicts, so a clean checkout of the branch would be a solution if that is the case.

**Comment by moollaza** [comment]
All fixed: 
https://ddh8.duckduckgo.com/?q=producthunt+remote&ia=products

**Comment by moollaza** [comment]
I just needed to re-build the minified JS

**Comment by abeyang** [comment]
Hi @sevastos , I agree with you -- let's remove the underline from the on-hover. In addition, can you **shrink the tile width to 16em** (it's currently 17em)?

Finally, can we change the tab name? We now have two Products tabs.. maybe change this to ProductHunt?

Other than that, I think this is ready to be merged!

**Comment by sevastos** [comment]
@abeyang done :)

**Comment by moollaza** [comment]
Updated: https://ddh8.duckduckgo.com/?q=producthunt+remote&ia=producthunt

**Comment by abeyang** [comment]
Looks good! :+1:

**Comment by moollaza** [comment]
@sevastos congrats! It's live: https://duckduckgo.com/?q=producthunt+remote&ia=producthunt

Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's & Issues or even submit more Instant Answers!

**Comment by sevastos** [comment]
Nice! @moollaza and @abeyang thanks for helping out! I have some ideas for other IAs and hopefully will get on them soon.
Cheers

**Pull request merged**
