### PR TITLE
Twitter: Improve triggering - Skip words

### LINKED ISSUE #1454: Don't trigger twitter IA for [dictionary match single words]
e.g. 

https://duckduckgo.com/?q=twitter+analytics&t=ffab&ia=social

https://duck.co/ia/view/twitter

### PR DESCRIPTION
**Pull request by MrChrisW**
Fix #1454 (Don't trigger twitter IA for [dictionary match single words])

---

Changes
- Updated to slurp "skip words" from file skipwords.txt.
- Added words: _analytics, company, about_

---

Recommend addtional words to skip; suggestions welcome :smile:

### CODE REVIEW

**Comment by MrChrisW** [comment]
This could be handled internally by the duckduckgo endpoint tw.js.

**Comment by moollaza** [comment]
@jagtalon are you familiar with `tw.js`? Do we have any relevancy code in there?

**Comment by jagtalon** [comment]
@moollaza @MrChrisW no relevancy code--literally just a proxy for the Twitter endpoint. This should be good. :)

**Comment by jagtalon** [comment]
@MrChrisW Update the tests?

**Comment by zekiel** [comment]
//cc @puskin94

**Comment by puskin94** [comment]
@zekiel thanks for the cc ! Why the triggers are regex rather words match?
Like @ or twitter ( like now )

**Comment by MrChrisW** [comment]
@jagtalon What tests? :wink: (there's no test file)...

Who can I blame for this?... You!!! #180 :laughing: :laughing:

**Comment by MrChrisW** [comment]
@puskin94 The triggers are using regexp to match a `@` followed by some text `([a-z0-9_]+)$` instead of triggering on just @. 

@jagtalon This should be good to go!

**Comment by jagtalon** [comment]
@MrChrisW uuuuh ... yes. :) I forgot the test file.

**Comment by jagtalon** [comment]
:+1:

**Pull request merged**
