### PR TITLE
Better approach to checking for single food item match

### PR DESCRIPTION
**Pull request by moollaza**
## Description of new Instant Answer, or changes
- More robust approach to checking for named food item searches
- Update tests accordingly
- Alpha-sorted food item lists

## People to notify
@fraed 

---

Instant Answer Page: https://duck.co/ia/view/nutrition

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
Deploying to Beta

**Comment by moollaza** [comment]
Will wait until tomorrow to test as our API access is unavailable right now 👍

**Comment by moollaza** [comment]
I've tested this on beta and using out trigger testing tool to ensure it won't over trigger. Everything looks good now 👍

**Comment by bsstoner** [comment]
This was released to production 🚀

**Pull request merged**
