### PR TITLE
MetaCPAN: Attempt to extract module name when additional words are in query

### PR DESCRIPTION
**Pull request by jbarrett**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer: **`New {IA Name} Instant Answer`**
- [x] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [x] Enhancement: **`MetaCPAN: Attempt to extract module name when additional words are in query`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{SpiceRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

When additional query words are provided alongside an apparent module name, this change will extract the module name and ignore other terms.

###### Which issues (if any) does this fix?

Improvement for #2877 though probably not a complete fix.

###### People to notify (@mention interested parties)

@GuiltyDolphin @sahildua2305 

---

Instant Answer Page: https://duck.co/ia/view/meta_cpan

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): **N/A**

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by jbarrett** [comment]
App-DuckPAN has some problems with URL encoding and '::' which the metacpan API does not like, so I have deployed this here : https://john.duckduckgo.com/?q=cpan+text%3A%3Atrim+install&ia=software

**Comment by GuiltyDolphin** [comment]
@jbarrett Looking pretty good.

Could we normalize the subtitle so instead of displaying `Software for cpan text::trim install` we displayed `Software for cpan Text::Trim` (or `Software for cpan text::trim`), seeing as we are *completely* ignoring everything else?

**Comment by jbarrett** [comment]
Genuinely not sure I have control over that without using a custom template.

**Comment by sahildua2305** [comment]
Looks good to me! :+1:

**Comment by GuiltyDolphin** [comment]
@jbarrett Uhh, not sure; not super pressing though (@moollaza is it enough to provide a subtitle?).

@sahildua2305 Alrighty! @jbarrett Thanks :)

**Comment by moollaza** [comment]
> @jbarrett Uhh, not sure; not super pressing though (@moollaza is it enough to provide a subtitle?).

@GuiltyDolphin @sahildua2305 

Yeah we can improve this a little to canonicalize it. We can move one of the footer items (whichever is most important) into the subtitle and keep the footer with two items, or make it two lines:

>**WWW::DuckDuckGo**
> Version: 0.016
>
>This distribution gives you an easy access to the DuckDuckGo Zero Click Info API. It tries to...
>
>Author: MOOLLAZA
> Updated: 08 May 2015


We should also do the date handling with Moment.js and switch to a format of `May 8th, 2015`

**Comment by jbarrett** [comment]
Thanks @moollaza! I believe I switched to moment.js from the js datetime builtins, so it should just be a matter of changing the format string.

@sahildua2305 You are now the maintainer of [meta_cpan](https://duck.co/ia/view/meta_cpan). Thanks for stepping up!

**Pull request merged**
