### PR TITLE
Timer: added more triggers

### PR DESCRIPTION
**Pull request by puskin94**
@moollaza Hei, As you suggested here https://github.com/duckduckgo/zeroclickinfo-spice/issues/1618 I updated the triggers.

### CODE REVIEW

**Comment by moollaza** [comment]
@puskin94 LGTM :+1:

**Comment by moollaza** [comment]
Oh, please add a test or two to ensure this all works correctly!

**Comment by puskin94** [comment]
@moollaza Hei, I updated the test file too!

**Comment by moollaza** [comment]
LGTM :+1: 

Thanks @puskin94

**Comment by puskin94** [comment]
@moollaza It's a pleasure ;)

**Pull request merged**
