### PR TITLE
GitHub: Swap Stars in infobox with SSH URL

### LINKED ISSUE #3333: GitHub Suggestion: Swap `Stars` and `SSH URL` in the GitHub infobox
### Description

Often when I'm searching for a repo, I have to click on the dropdown arrow on the infobox to show all the details, specifically `Stars`. On some repos that have a longer description you can see the `Stars` info, but [on others](https://duckduckgo.com/?q=git+hub+awesome&t=osx&ia=software) you can't see the stars info. 

I think that the SSH URL entry and the Stars entry should be switched, I'm not sure if that's the best choice, so please let me know if it should be a different change.

If anyone wants, I can make a PR.

## Steps to recreate

[This](https://duckduckgo.com/?q=git+hub+awesome&t=osx&ia=software) doesn't shows the star count, but [this](https://duckduckgo.com/?q=bootstrap+repo&ia=software) does.

---

Instant Answer Page: https://duck.co/ia/view/github

### PR DESCRIPTION
**Pull request by perryprog**
## Description of new Instant Answer, or changes

See #3333 

## Related Issues and Discussions

Fixes #3333 

## People to notify

@pjhampton 

---

Instant Answer Page: https://duck.co/ia/view/github

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by pjhampton** [comment]
Restarting tests...
Anybody want to review this? @duckduckgo/duckduckhack-contributors

**Comment by kirkins** [comment]
@pjhampton I wanted to check this out and test it but when I run `duckpan server github` and query I get this:

untitled

When I do the same thing with other IAs I don't have that problem.

**Comment by perryprog** [comment]
@kirkins :p thanks, I never ended up testing up because I figured it was basic enough to work. I'm actually kinda confused why that happened... any ideas?

**Comment by kirkins** [comment]
@perryprog no idea why it happens. I don't think it's specific to your branch.

I had the same problem on your branch and the master branch on DuckDuckGo's version.

Does it work for you if you try testing with duckpan?

**Comment by perryprog** [comment]
@kirkins I'm not on the computer that has DuckPan set up on it, and I'll have to do some setup to get it working again. Good to know it's not my fault 😉

**Comment by moollaza** [comment]
@perryprog Thanks! This LGTM :+1:

**Comment by bsstoner** [comment]
This should be in production now 🚀

**Pull request merged**
