### PR TITLE
Added a few more informations about a comic

### PR DESCRIPTION
**Pull request by gamehelp16**
Added comic title, number and date for the sake of more information
Also changed the CSS a bit

Screenshot (old):
spice-xkcd

Screenshot (new):
ddh-xkcd

### CODE REVIEW

**Comment by gamehelp16** [comment]
@jagtalon so, should I edit the code so it displays the title only?
@mattr555 sorry, I'm not that familiar with github, how can I do that?

**Comment by MrChrisW** [comment]
@jagtalon Definitely agree with conserving vertical space :grinning: 

I feel like the comic number is irrelevant information, especially if the search includes the number `xkcd 1411`. 

I think the date on the other hand can be classified as useful information. How about only showing it on desktop? using `!is_mobile`? or is that a no no?

@gamehelp16 
Follow these steps to update your local fork with the upstream repository: 
https://help.github.com/articles/syncing-a-fork/

You may run into some merge conflicts (don't panic!) (*this happens if the same file that you're working on has recently been modified in the upstream repo you're merging*) this guide will help you: 
https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/

Let me know if you get stuck and I'll be happy to help!

**Comment by jagtalon** [comment]
@MrChrisW sounds like a good compromise--the date could be useful there, and I'm not opposed to `is_mobile` (@gamehelp16 this is a global variable that's available to you), but you can also use `detail_mobile` https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/forecast/forecast.js#L283.

**Comment by gamehelp16** [comment]
@MrChrisW thanks for the useful links :D
@jagtalon it's a javascript variable, right? So I can just use the variable without doing anything else, right?

So, what I need to do is remove the comic number (actually I added that so people who searched for `xkcd` or `xkcd random` can know what number the comic is), and hide the comic date if the user is on mobile?

**Comment by jagtalon** [comment]
@gamehelp16 Yeah, that's right! Although for now I guess you could just remove the comic # for now and we can merge this in (I realize that the comic # can be useful, but it's just taking too much space and we have to make compromises.)

**Comment by gamehelp16** [comment]
I have done `cd zeroclickinfo-spice`, but when trying to do `git fetch upstream` I got this error:

fatal: 'upstream' does not appear to be a git repository                                                        
fatal: Could not read from remote repository.                                                                   
                                                                                                                
Please make sure you have the correct access rights                                                             
and the repository exists.

What should I do? Thanks in advance

**Comment by jdorweiler** [comment]
@gamehelp16 sounds like you need to set the upstream to the `duckduckgo/zeroclickinfo-spice` repo.  This should help https://help.github.com/articles/configuring-a-remote-for-a-fork/

**Comment by jagtalon** [comment]
@gamehelp16 Looks like the display is a bit messed up:

screen shot 2015-01-09 at 2 35 25 pm

Here's the current one:

screen shot 2015-01-09 at 2 36 04 pm

**Comment by gamehelp16** [comment]
The display should be fine now :)

**Comment by jagtalon** [comment]
:+1:

**Comment by gamehelp16** [comment]
Thanks for merging ;D

**Comment by jagtalon** [comment]
@gamehelp16 it's live! https://duckduckgo.com/?q=xkcd&ia=comics

**Comment by jkanarek** [comment]
@abeyang @chrismorast is there a better control besides the button for "explain"? We don't use that anywhere else and it is throwing me off.

**Comment by gamehelp16** [comment]
Yay, thanks! :D

Although it seems that I failed to hide the date on mobile

**Comment by moollaza** [comment]
FWIW the display is looking a little odd still:

2015-01-18_21h35_37

I think we should remove the margin from the image, so it's no longer horizontally-centered and we might want to force the prev/explain/next buttons to be beside eachother with a constant spacing.

Alternatively we might want to but the prev/next buttons beside the image and have the explain link below.

cc// @abeyang @chrismorast

**Comment by chrismorast** [comment]
It looks like the mobile changes that were made were also applied to desktop.

**Comment by gamehelp16** [comment]
Is this my "job" btw? Is there anything I should do?

**Comment by chrismorast** [comment]
Sorry @gamehelp16 , not your job unless you'd like to tackle it. Meant to be a message for @moollaza :)

**Comment by moollaza** [comment]
@gamehelp16 would you be interested in doing it? If not I'll tackle it.

@chrismorast I noticed the "Explain" link is missing from your mockup -- can we fit it in somehwere? To the right of "Next" perhaps?

**Comment by gamehelp16** [comment]
Okay, I think I will just let @moollaza tackle it :)

**Comment by moollaza** [comment]
done :)

https://github.com/duckduckgo/zeroclickinfo-spice/pull/1445

**Pull request merged**
