### PR TITLE
New Mo Spice

### PR DESCRIPTION
**Pull request by fivesquared**
## People to notify

---

Instant Answer Page: https://duck.co/ia/view/Mo

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by fivesquared** [comment]
https://duck.co/ia/view/Mo

**Comment by pjhampton** [comment]
Hey @fivesquared

I have put this on hold for now. Can you please update with a description and then we'll get it deployed to beta.

**Comment by fivesquared** [comment]
Updated for pull #3253 with passing tests (had buggy test script). Thanks

**Pull request closed without merging**
