### PR TITLE
New Cryptocurrency Marketcap Spice

### PR DESCRIPTION
**Pull request by alidryan**
# New Cryptocurrency Marketcap Spice.

## Description

For the main cryptocurrencies, displays :
  -  Price
  -  Price change (24h)
  -  Market cap
  -  Available Supply
  -  Rank
  -  Image of the currency

(data from coinmarketcap API)

---

Instant Answer Page: https://duck.co/ia/view/cryptocurrency_marketcap

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@Alidryan thanks for submitting this. It looks like your tests are failing though. Once passing, we'll be able to deploy this to Beta for further testing.

**Comment by Alidryan** [comment]
@moollaza Oh yeah sorry I didn't realise that, they are passing now.

**Comment by pjhampton** [comment]
Hey @alidryan 

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, this is non-essential and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to include your work.

**Pull request closed without merging**
