### PR TITLE
Remove: Translate IA

### PR DESCRIPTION
**Pull request by MrChrisW**
Fixing #1510

**What's happened here?**

delete lib/DDG/Spice/Translate/Detect.pm
delete lib/DDG/Spice/Translate/DetectPhrase.pm
delete lib/DDG/Spice/Translate/FromTo.pm
delete lib/DDG/Spice/Translate/FromToPhrase.pm
delete share/spice/translate/README.md
delete share/spice/translate/detect/translate_detect.js
delete share/spice/translate/detect_phrase/translate_detect_phrase.js
delete share/spice/translate/from_to/translate_from_to.js
delete share/spice/translate/from_to_phrase/translate_from_to_phrase.js
delete share/spice/translate/translate.js
delete share/spice/translate/translate_from_to.handlebars
delete share/spice/translate/translate_from_to_phrase.handlebars
delete t/Translate.t

### CODE REVIEW

**Comment by MrChrisW** [comment]
@moollaza Not sure why this won't allow auto merge...

**Comment by moollaza** [comment]
hmm I'm not too sure either @MrChrisW . It looks like you removed it, then reverted then removed it again. 

Also, did you remove the files with `rm` or `git rm`? The latter is the one you want :)

**Comment by MrChrisW** [comment]
@moollaza First I did a `git rm` on all files. Pushed, created PR. "Cannot Automatically Merge"

So I reverted, ran the removal again and pushed, same issue.

**Comment by MrChrisW** [comment]
@moollaza I'll branch again, create a new PR and see what happens :+1:

**Comment by moollaza** [comment]
@MrChrisW hmm that's really odd. I'm curious to see what happens!

**Comment by MrChrisW** [comment]
Completing in #1519

**Pull request closed without merging**
