### PR TITLE
GoWatchIt: Update assets.

### PR DESCRIPTION
**Pull request by jagtalon**
- Added Sundance
- Added Best Buy
- Added Walmart
- Added Target

### CODE REVIEW

**Comment by jagtalon** [comment]
screen shot 2015-02-02 at 3 02 50 pm

screen shot 2015-02-02 at 3 03 19 pm

**Comment by moollaza** [comment]
@jagtalon looks like a lot of the "modified" images are identical -- did they actually change>

**Comment by jagtalon** [comment]
@moollaza yeah I think @abeyang moved the text a little bit to the center. :D

**Comment by jagtalon** [comment]
@moollaza the swipe view should show the changes pretty well

**Comment by abeyang** [comment]
Ack @jagtalon -- I've updated the best buy icons -- can we use these instead (re-introduced the 5-degree tilt):

bestbuy
bestbuy 2x

**Comment by jagtalon** [comment]
@abeyang cool thanks abe will add that in

**Comment by jagtalon** [comment]
@moollaza @abeyang done! https://ddh9.duckduckgo.com/?q=watch+boyhood&ia=watch

**Comment by jagtalon** [comment]
@abeyang curious how you make these icons btw. Do you do it from scratch?

**Comment by abeyang** [comment]
@jagtalon yes. Every single one, painstakingly (and somewhat-lovingly) done. :sweat:

**Comment by jagtalon** [comment]
@abeyang damn well thanks for all the work!

**Comment by moollaza** [comment]
LGTM :+1:

**Pull request merged**
