### PR TITLE
Anime: Switch to Kitsu API

### LINKED ISSUE #3082: Anime: No longer works after change from Hummingbird to Kitsu
The change in domain and API broke this Spice and no triggers work.

------
IA Page:  http://duck.co/ia/view/anime 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @iambibhas

### PR DESCRIPTION
**Pull request by synthtech**
## Description of new Instant Answer, or changes

Updates the old Hummingbird api call to use Kitsu's new api.

## Related Issues and Discussions

Fixes #3082 

---

Instant Answer Page: https://duck.co/ia/view/anime

### CODE REVIEW

**Comment by daxtheduck** [comment]
@synthtech Thanks for the pull request! Unfortunately, we're only accepting contributions and improvements to a limited portion of the search space.
            
The staff and community are currently focused on making DuckDuckGo the [best search engine for programmers](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53). To ensure we're making as much progress as possible, **we are only accepting Instant Answers and updates related to the programming mission**.
    
If this is not related to the Programming Mission, it will likely be closed but you can:
    
1. Help us prevent further confusion by telling us where you found out about DuckDuckHack or where we could've alerted you earlier.
2. Keep this code handy! We'll be expanding into other search topics in the future!
3. Join us at our new home: https://forum.duckduckhack.com/

If this is related to the Programming Mission, it will be reviewed by staff and the community as soon as possible!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by Kcchouette** [comment]
hello @iambibhas 
When the merge of this PR is planned, please?

**Comment by moollaza** [comment]
@synthtech Thanks! This LGTM :+1:

**Comment by moollaza** [comment]
This is now live on Beta: https://beta.duckduckgo.com/?q=anime+naruto&ia=anime&iai=1

**Pull request merged**
