### PR TITLE
Astrobin, Gifs, Images: update to new image property names

### PR DESCRIPTION
**Pull request by andrey-p**
This goes hand in hand with an internal PR.

### CODE REVIEW

**Comment by jagtalon** [comment]
@andrey-p Sweet! Feel free to ping any of the community leaders who have commit access when it's ready https://duck.co/duckduckhack/submission_and_review#review-process. Tagging as `On Hold` for now.

**Comment by jagtalon** [comment]
@moollaza since it's the same, probably doesn't need the `Design` tag?

**Comment by jagtalon** [comment]
@moollaza a bit confused about the `Internal` tag--what it means to me is that nobody else can merge this except for DDG staff which shouldn't be the case once this is live right?

**Comment by moollaza** [comment]
@jagtalon I use it to signify that there's related internal changes.

**Comment by moollaza** [comment]
Whoops, didn't mean to remove the On-Hold -- marked as WIP for now though, because there's still internal work being done,

**Comment by jagtalon** [comment]
@moollaza cool thanks that makes sense. :)

**Comment by bsstoner** [comment]
:+1:

**Pull request merged**
