### PR TITLE
Continue Missing Kids

### PR DESCRIPTION
**Pull request by moollaza**
Continue #2274 

- Cache regex outside `normalize` fn
- Use Moment.js for date handling
- Add support for providing state in query, i.e. "Missing kids in Arizona"

/cc @brianrisk 

Result:

missing_kids_pa_at_duckduckgo

-----
IA Page: https://duck.co/ia/view/missing_kids

### CODE REVIEW

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=Missing kids)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/missing_kids_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=Missing kids)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/missing_kids_mobile.png)

**Comment by moollaza** [comment]
Updated: 
missing_kids_wa_at_duckduckgo

**Comment by moollaza** [comment]
@abeyang is this OK to move ahead, or do you have any suggestions?

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=Missing kids)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/missing_kids_mobile.png)

**Comment by brianrisk** [comment]
@moollaza This looks really good.  I like the parenthetical information for how much time has passed since their missing date.

**Comment by moollaza** [comment]
Hmm mobile needs some help. Otherwise I'm pretty happy with this too @brianrisk

**Comment by moollaza** [comment]
- using full state name in metabar
- small adjustment to CSS for proper mobile tile height

Result:

missing_kids_in_tn_at_duckduckgo

**Pull request merged**
