### PR TITLE
Currency: Fix input step

### LINKED ISSUE #3413: Currency Conversion Bug: Non-integer values have title attribute falsely indicating error
### Description
The currency converter works fine with non-integers, so the title text giving errors for values with 1 decimal place is a bit off.

## Steps to recreate
Search for [10.1 gbp to eur](https://duckduckgo.com/?q=10.1+gbp+to+eur) and hover over the box on the right. Title text is "Please select a valid value. The two nearest values are 10 and 11.". Change the value of the box on the left to 10.2. That box will then also have the title text. (The right box changes to 11.02 regardless, so it still works.)

## People to notify
none

---

Instant Answer Page: https://duck.co/ia/view/currency

### PR DESCRIPTION
**Pull request by nalinbhardwaj**
## Description of new Instant Answer, or changes

Fixes bug where firefox only treated integers as valid.

## Related Issues and Discussions

Fixes #3413 

## People to notify

@pjhampton 

---

Instant Answer Page: https://duck.co/ia/view/currency

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
Deploying to Beta

**Comment by jc86035** [comment]
Hi. On the beta website the right-side box has the decimals stuck on whatever number was first calculated and should probably go to the nearest integer. To reproduce: Search "499 usd to cad" etc.; push either button on right side once; push either button on left side once; push either button on right side once. Tested in Firefox 55.

**Comment by pjhampton** [comment]
@jc86035 this is a different instance now. We pushed an experimental PR to fix some issues that were appearing yesterday 👍

**Comment by moollaza** [comment]
Closing as this is being discussed/fixed in #3415

**Comment by nalinbhardwaj** [comment]
Hey @moollaza this doesn't appear to be fixed?
Are you sure you meant to close this?

**Comment by moollaza** [comment]
@nalinbhardwaj sorry, my mistake. Would you mind opening another PR?

**Comment by nalinbhardwaj** [comment]
@moollaza restored the branch, I guess you should be able to reopen the PR?

**Comment by nalinbhardwaj** [comment]
@pjhampton / @moollaza ping for merge

**Comment by moollaza** [comment]
@nalinbhardwaj Thanks! This LGTM :+1:

**Pull request merged**
