### PR TITLE
A Javascript bug because of Octopart: JS Error

### PR DESCRIPTION
**Pull request by SibuStephen**
Removed `toFixed()` function  as the use for that function was inappropriate for that particular section, along with that Initialized a variable with zero, to avoid future Null exceptions.

### CODE REVIEW

**Comment by daxtheduck** [comment]
@SibuStephen Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by moollaza** [comment]
@SibuStephen thanks for submitting this. Please be sure to mention something like "fixes #2218" in your description so we know what this is about. Also, it automatically closes the issue when this is merged :+1: 

Regarding your fix, I don't see why `item` was renamed to `items` or why it needs to be initialized to `0`?

It seems like the problem is that we're not checking if `item.avg_prive_v2` is actually defined?

We can more easily fix this bug with a solution like this:

```js
var item = item.item;
if (!tem.avg_price_v2[0]){
    return null;
}
```

**Comment by SibuStephen** [comment]
@moollaza  i will check with it and soon will submit a PR for this.

**Comment by moollaza** [comment]
@SibuStephen I see you already submitted a new PR. FWIW, there's really no need, you can just add more commits to your branch and push them here. If you really want you can `git squash` you commits so all the changes are reduced to a single commit. We don't really care about the commit log being messy though, as long as the final result is good.

**Pull request closed without merging**
