### PR TITLE
fixing isitup issue #2499

### PR DESCRIPTION
**Pull request by Sayanc93**
fixes issue #2499

### CODE REVIEW

**Comment by daxtheduck** [comment]
@Sayanc93 Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@Sayanc93 this doesn't really fix the problem -- queries like "is it working" would still trigger.

The issue is that we're not making sure we have a domain in the query. "Is duckduckgo.com up?" is a valid query, but your changes would prevent it from working.

if the candidate domain name is `it` we should be ignoring the query.

---

Also, the tests are failing because you removed the triggers that are used in the test. Please remember to check that tests pass and update them accordingly. When modifying the functionality you should add a test that proves the changes work.

**Comment by Sayanc93** [comment]
My bad @moollaza I'll update the PR

**Comment by Sayanc93** [comment]
My bad @moollaza, I think i didn't understand the requirement. I did the required and updated the file and added a test. Does this change resolve your issue now?

**Comment by jagtalon** [comment]
@Sayanc93 looks like it's not working for things like "is facebook up?" (we might want to add that to the test as well)

screen shot 2016-02-22 at 6 58 37 am
screen shot 2016-02-22 at 6 58 43 am

As @moollaza said, 

> We may also want to put a minimum character count (5?) for candidate domains that don't have a TLD (i.e. missing ".com"). This would allow "is facebook down" but prevent "is it down".

Thank you!

**Comment by Sayanc93** [comment]
Hey @jagtalon i believe a query such as 'is facebook.com up? or 'is bbc.com up?' might have triggered the spice instead

**Comment by Sayanc93** [comment]
also if i add something like your request..how will the program know in 'is facebook up?' facebook is a site or facebook is a random word and not trigger an api call

**Comment by jagtalon** [comment]
@Sayanc93 it would have, although it currently works without the ".com" as well: https://duckduckgo.com/?q=is+facebook+down%3F&ia=answer

What it used to do was to check if the query has a TLD (like .com), and if it doesn't it makes an assumption that it's a .com and makes an API request.

**Comment by jagtalon** [comment]
Hope I explained it properly--tell me if you need any help! :)

**Comment by Sayanc93** [comment]
@jagtalon - I understand...but a useless api call for it.com which will return nothing..is acceptable? then i can modify my code..i made it only trigger on TLDs with com,net,etc.. like facebook.com duckduckgo.com, this removed useless api calls for queries like is sky up? is earth down? and stuff like that

**Comment by jagtalon** [comment]
@Sayanc93 that's acceptable, although you do have a valid point about those queries. I imagine those kinds of queries are scarce though compared to the usefulness of quickly typing "is github up?" :)

Thank you!

**Comment by moollaza** [comment]
@Sayanc93 limiting the IA to certain TLD's using the regex is too restrictive -- the simplest fix here is to check if the query is simply "is it up" and if so bail out.

We could try and use a heuristic like words with less than X characters and no TLD are ignored. That would keep queries like "is facebook up? and "is github online".

**Comment by Sayanc93** [comment]
I made it bail out on 'it'...i suppose is fox(fox.com) up or is ni(national instruments) up are valid use cases for queries so heuristic on 5 characters would be too harsh i think?
If you guys agree, I think this can be merged now

**Comment by Sayanc93** [comment]
I modified the code to meet the requirement as mentioned in the issue. This spice will now bail out if the query has a website with no TLD and is less than 5 characters as mentioned by @moollaza. Let me know if this still needs work :) But it doesn't I think you can merge this now.

**Comment by Sayanc93** [comment]
can this be merged?

**Comment by moollaza** [comment]
Thanks! This LGTM :+1:

**Pull request merged**
