### PR TITLE
Detail Pane Structure Changes

### PR DESCRIPTION
**Pull request by sdougbrown**
We're changing the 'detail' pane to make it easier to work with, and much easier to craft a great mobile experience.

This updates a number of spices to bring them in line with some of the new standards/requirements.

Requires an internal PR.

to @bsstoner

### CODE REVIEW

**Comment by bsstoner** [comment]
@russellholt @moollaza is there someone who can help review this with us and weigh in on the API changes?

**Comment by russellholt** [comment]
LGTM

**Comment by moollaza** [comment]
@bsstoner what's the status on this? Should we merge? or close?

**Comment by jdorweiler** [comment]
@bsstoner are you still working on this?

**Pull request closed without merging**
