### PR TITLE
MetaCPAN: Fixes #3051 - Fix up references in JS for MetaCPAN API

### LINKED ISSUE #3051: MetaCPAN: Description and author displaying only the first letter, release date says: Invalid Date
Instant answer is not displaying correctly the description of modules, only the first letter. Also the author is not displayed, only de first letter, and the latest release date says Invalid Date

Example search: perl plack pod

------
IA Page:  http://duck.co/ia/view/meta_cpan 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sahildua2305

### PR DESCRIPTION
**Pull request by deserted**
## Description of new Instant Answer, or changes
- Corrected references in meta_cpan.js to the returned data format for the MetaCPAN API
- Added exclusion rule to query regex to prevent a query with a space preceding hyphen - example: `cpan Mojolicious - plugins`

## Related Issues and Discussions
Fixes #3051 

## People to notify

---

Instant Answer Page: https://duck.co/ia/view/meta_cpan

…ce first object in array for Author, description and date with named key only

### CODE REVIEW

**Comment by daxtheduck** [comment]
@deserted Thanks for the pull request! Unfortunately, we're only accepting contributions and improvements to a limited portion of the search space.
            
The staff and community are currently focused on making DuckDuckGo the [best search engine for programmers](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53). To ensure we're making as much progress as possible, **we are only accepting Instant Answers and updates related to the programming mission**.
    
If this is not related to the Programming Mission, it will likely be closed but you can:
    
1. Help us prevent further confusion by telling us where you found out about DuckDuckHack or where we could've alerted you earlier.
2. Keep this code handy! We'll be expanding into other search topics in the future!
3. Join us at our new home: https://forum.duckduckhack.com/

If this is related to the Programming Mission, it will be reviewed by staff and the community as soon as possible!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by sahildua2305** [comment]
Thanks for the PR @deserted!

Can we deploy this to beta, @tagawa ?

**Comment by tagawa** [comment]
Thank you @deserted (and for the ping @sahildua2305). This is now on the beta server for testing: https://beta.duckduckgo.com/?q=cpan+midi&ia=software

**Comment by deserted** [comment]
Hi @tagawa testing on beta today this fix seems to have been rolled back on beta, any reason?

**Comment by tagawa** [comment]
@deserted Thanks for letting me know. Not sure what happened there but I redeployed and it seems better now: https://beta.duckduckgo.com/?q=cpan+midi&ia=software

**Comment by deserted** [comment]
@tagawa awesome thanks for that :) anyone I should be pinging to get this reviewed?

**Comment by moollaza** [comment]
@deserted Thanks! This LGTM :+1: Nicely done 💯

**Comment by tagawa** [comment]
This seems to be live now - thank you @deserted! https://duckduckgo.com/?q=cpan+Mojolicious+-+plugins&ia=software

**Comment by deserted** [comment]
yup looks like it's working, have also submitted #3063 to resolve the issue with linking to MetaCPAN through the "More at MetaCPAN" link

**Pull request merged**
