### PR TITLE
Quandl: Refactor

### PR DESCRIPTION
**Pull request by MrChrisW**
Improvements to Quandl Spices. 

## World Bank
+ ~~Refactor JavaScript~~
+ ~~Refactor/Improve Perl code~~
+ [x] Remove top comments

## Home Values
+ [x] Refactor JavaScript
+ ~~Refactor/Improve Perl code~~
+ [x] Remove top comments

## Fundamentals
+ [x] Refactor JavaScript
+ [x] Refactor/Improve Perl code
+ [x] Remove top comments

Please excuse the first few commits as I did begin to refactor/improve the template until reading [comment](https://github.com/duckduckgo/zeroclickinfo-spice/pull/1787#issuecomment-94162924) :+1: Those changes have been reverted. @moollaza Please make a template soon, the CSS code is freaking me out :laughing: 

Merge will be required after #1787 is merged into master (I've left the date functions as is). @iambibhas :smile:

### CODE REVIEW

**Comment by MrChrisW** [comment]
@moollaza I'm happy with these improvements :+1: should be good to merge.

**Comment by moollaza** [comment]
@MrChrisW LGTM :+1: 

/cc @brianrisk

**Comment by MrChrisW** [comment]
Thanks @moollaza :smile: :+1:

**Comment by brianrisk** [comment]
This is so cool.  Thank you @MrChrisW!

**Comment by MrChrisW** [comment]
No problem! Thanks for the awesome IA's @brianrisk

**Pull request merged**
