### PR TITLE
Re-enable Amazon ratings

### PR DESCRIPTION
**Pull request by tommytommytommy**
https://duck.co/ia/view/products

Work-in-progress, just putting up the PR to get started on testing adding back ratings/reviews...
cc: @moollaza

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
So far, this LGTM 👍

**Comment by tommytommytommy** [comment]
@moollaza I made a small change to guard all of the ratings/reviews code based on the experiment variable (so that it doesn't run if we're not in the experiment, and also so that we don't show the stars template when we're outside the experiment). Otherwise, everything is the same. Thanks for the review!

**Comment by moollaza** [comment]
@tommytommytommy Thanks! This LGTM :+1:

**Pull request merged**
