### PR TITLE
GfyCat Instant Answer

### PR DESCRIPTION
**Pull request by GreenBeard**
What does your Instant Answer do?

What problem does your Instant Answer solve (Why is it better than organic links)?

What is the data source for your Instant Answer? (Provide a link if possible)

Why did you choose this data source?

It is the api provided for GfyCat for their videos and I wanted to show information about their videos.

Are there any other alternative (better) data sources?

No, GfyCat is the default one and there is not likely to be any better data sources.

What are some example queries that trigger this Instant Answer?

'gfycat scarygrizzledcomet', 'gfy cat scarygrizzledcomet', 'gfy scarygrizzledcomet', 'scarygrizzledcomet gfy cat', 'gfycat understatedwateryfreshwatereel', etc.

Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)

Gamers, Redditors and others who like to use GfyCat for posting small short videos in a multi-browser supported way. GfyCat can also convert gifs to webm and mp4 which is very helpful.

Is this Instant Answer connected to a DuckDuckHack Instant Answer idea?

No, I thought to do it myself and as far as I know there is no Instant Answer idea.

Which existing Instant Answers will this one supersede/overlap with?

None, that I am aware of. Maybe the default videos one although it doesn't show links to GfyCat videos.

Are you having any problems? Do you need our help with anything?

Nope.

What are the terms of use for the API? Will DuckDuckGo need specific authorization (e.g. an API key)? Are there any costs associated with API usage?

The API is free to use and there isn't any terms for using it here is a link to the api page: http://gfycat.com/api

Link to full terms: http://gfycat.com/terms

Only terms possibly applying to this Instant Answer:
Commercial Use
Commercial embedding is allowed but Gfycat reserves the right to change this policy at any time or change the nature of embedded content if warranted or deemed necessary. Gfycat considers commercial use as anyone expecting to earn more than $500 per month.

Where did you hear about DuckDuckHack? (For first time contributors)

Heard about it from my family since they got annoyed at all the tracking google does and I tried it out and have been using it since. I really like how it also has only 1 ad in the search and allows for more customization!

What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)

untitled

```
  [X] Added metadata and attribution information
  [X] Wrote test file and added to t/ directory
  [X] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
  [X] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
  [X] Tested cross-browser compatibility
  
    Please let us know which browsers/devices you've tested on:
    - Windows 8
        [X] Google Chrome
        [X] Firefox
        [] Opera
        [X] IE 10

    - Windows 7
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 8
        [] IE 9
        [] IE 10

    - Windows XP
        [] IE 8

    - Mac OSX
        [] Google Chrome
        [] Firefox
        [] Opera
        [] Safari

    - iOS (iPhone)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - iOS (iPad)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - Android
        [X] Firefox
        [] Native Browser
        [X] Google Chrome
        [] Opera
```

### CODE REVIEW

**Comment by moollaza** [comment]
@GreenBeard thanks a lot for contributing, we really appreciate it! We'll be sure to review this shortly and give you some feedback!

Did you happen to notice the portion of the documentation which asks developers to email us for Instant Answer approvals? We ask that developers email use before working on anything so we can help developers flesh out their ideas, and so we can make sure developers won't build something we can't use. It's totally OK that you didn't email us first, I'd just like to know so we can improve the documentation :)

This is a great start, but the `base` template is really reserved for custom Instant Answers which can't use any of our existing [templates](https://duck.co/duckduckhack/spice_templates_overview#template-groups). 

Ideally, using a template, you'll be able to prevent writing and HTML or CSS as our templates will handle building the result and styling it. I would suggest that you re-implement this using the `info` template and the `record` sub-template to create your table. That should alleviate the need for CSS and HTML entirely.

**Comment by GreenBeard** [comment]
@moollaza I was mostly curious if I could do it because I have made programs in the past but always start on too big of projects whenever I like something and I want to contribute so I wanted to finish one completely even if it didn't turn out to accepted and if it was that would be an added bonus. I will probably try to make a better Instant Answer later but this was interesting and fun for me so even if it didn't work out that was fine :)

Also I saw the info and record sub-template and tried it but I got confused and did it in css instead. I could redo it into info and record if that would be better. (I was doing something else wrong in my code when I redid it)

**Comment by moollaza** [comment]
>Also I saw the info and record sub-template and tried it but I got confused and did it in css instead. I could redo it into info and record if that would be better. (I was doing something else wrong in my code when I redid it)

Sorry to hear you ran into trouble -- if you have that code around please update the PR and push it. I'll advise if there's any bugs/problems. It would be preferred if you went that route so that in-case we change the design for the table, this IA will automatically get updated and we won't have to manually change the classes/CSS/HTML, etc

**Comment by moollaza** [comment]
@GreenBeard Ping! Are you still interested in finishing this up? We'd love to see it go live!

We've made a bunch of documentation updates recently, and in particular new documentation that explains how to use the Images template which this IA could certainly use!

**Comment by GreenBeard** [comment]
@moollaza Not really that interested in finishing it up. I don't think it would be very useful in the first place but was a fun test. :)

**Comment by moollaza** [comment]
>Not really that interested in finishing it up. I don't think it would be very useful in the first place but was a fun test. :)

Not a problem :) If you don't mind, I'll mark this one as abandoned for someone else in the community to finish up. 

> I don't think it would be very useful in the first place but was a fun test. :)

I actually think there's some use in having this IA :+1:  It could be improved to show the actual GIF along with the metadata.

**Comment by moollaza** [comment]
BTW, @GreenBeard feel free to stick around and comment/help on other PR's & Issues or even submit more Instant Answers! I just hope you finish those ones so we can see them go live! ;)

**Pull request closed without merging**
