### PR TITLE
SearchCode: Add more at link

### PR DESCRIPTION
**Pull request by sahildua2305**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer: **`New {IA Name} Instant Answer`**
- [x] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [x] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{SpiceRole/Templates/Tests/Docs}: {Short Description}`**

###### People to notify (@mention interested parties)
@moollaza 

---

Instant Answer Page: https://duck.co/ia/view/search_code

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by edgesince84** [comment]
This should definitely help with the programming mission!  thanks @sahildua2305

**Comment by tagawa** [comment]
I deployed this to beta but it doesn't seem to be triggering for me sometimes - the API is returning an "Internal server error" occasionally.

**Comment by sahildua2305** [comment]
Yes even I noticed this problem with the API. Anyway we can handle that in another issue to check the reliability of the API. This is just a quick fix that I discussed with @moollaza on another PR.

**Comment by moollaza** [comment]
@boyter any ideas if the SearchCode API has been having problems?

**Comment by moollaza** [comment]
@sahildua2305 Thanks! This LGTM :+1:

**Comment by boyter** [comment]
@moollaza Sorry yes a lot of API issues at the moment. Busy moving over to new host which should solve all the issues for good (I hope!)

**Comment by moollaza** [comment]
@boyter Thanks for letting us know! Good luck with the move 👍

**Pull request merged**
