### PR TITLE
TravisStatus: Trigger on "travisci"

### PR DESCRIPTION
**Pull request by MrChrisW**
Resolving #1457

Triggers on "travisci" and "travis ci" should probably add "travis-ci"

### CODE REVIEW

**Comment by moollaza** [comment]
@MrChrisW do we need to give it a low signal for those new trigger words? Did you happen to test if it now gets priority over the Wiki IA (because I don't think it should for those generic triggers)

**Comment by MrChrisW** [comment]
@moollaza I'll add a low signal now. 

I think internally the wiki "about" IA should be triggered on a search for "travisci" - internal

Currently it triggers for "travis ci", "travis-ci"

**Comment by MrChrisW** [comment]
@moollaza signal is now low. 
If possible can we chuck it on the ddh1 server as I'm unable to ensure the **About** IA is activated by default over this IA.

**Comment by jagtalon** [comment]
@MrChrisW nice! Will give it a whirl

**Comment by jagtalon** [comment]
@MrChrisW Looks good! :+1: 

screen shot 2015-02-04 at 1 17 30 pm

**Pull request merged**
