### PR TITLE
TVmaze: Small adjustments

### PR DESCRIPTION
**Pull request by moollaza**
/cc @jagtalon @tvdavid @abeyang 
- Switched tab name to "Entertainment"
- removed bold tags (we save those for exact matches in results) and opted for `text--primary` class
- fixed `Spice.failed()` calls
- removed some trailing spaces

Pics:

2015-02-03_20h34_11
2015-02-03_20h35_06
2015-02-03_20h35_43

### CODE REVIEW

**Comment by jagtalon** [comment]
@moollaza 

Should the timezone be displayed?

screen shot 2015-02-04 at 1 01 22 pm

Should probably not trigger on these queries:

screen shot 2015-02-04 at 12 58 01 pm
screen shot 2015-02-04 at 12 58 37 pm

**Comment by jagtalon** [comment]
Yeah should definitely show the timezone for that time:

screen shot 2015-02-04 at 1 04 05 pm

Maybe convert it to non-military time as well?

**Comment by jagtalon** [comment]
@abeyang up on https://ddh1.duckduckgo.com/?q=next+episode+of+man+seeking+woman&ia=entertainment

**Comment by abeyang** [comment]
@jagtalon I agree, can we use standard time for those? And is there a reason why some are #333 (like "Dram" and the date) and the rest is #666? Can we just standardize and use #666?

**Comment by jagtalon** [comment]
@abeyang thanks @moollaza using the class `tx-clr--dk2` should put in `#666` for you

**Comment by moollaza** [comment]
OK. Pushed a big change that adds relevancy checking and better time/date display.

Getting the actual timezone for the epsiode (eg. Easter Central Time) is a real PITA. So I've opted to show the network and the country which I think is pretty suggestive.

I'm hoping that we can start using a localization lib on the frontend so we can easily display times and timezones to users.

**Comment by moollaza** [comment]
**Previous Episode**:
2015-02-07_11h48_26

**Next Episode**:
2015-02-07_11h48_11

**Comment by moollaza** [comment]
@jagtalon @abeyang live on https://ddh7.duckduckgo.com/?q=the+walking+dead+next+episode&ia=entertainment

**Comment by abeyang** [comment]
Looks good! :+1:

**Comment by moollaza** [comment]
@abeyang thanks!

**Pull request merged**
