### PR TITLE
Changed 'http' to 'https' (fixes #2744)

### LINKED ISSUE #2744: Shorten: API Redirecting to HTTPS, Code Update Required
This IA has been taken offline because it started failing.

The API now redirects to HTTPS so we need to updated the `spice to` accordingly in order to get this IA online again.   

------
IA Page:  http://duck.co/ia/view/shorten 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @danjarvis

### PR DESCRIPTION
**Pull request by anthonyn60**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer: **`New {IA Name} Instant Answer`**
- [x] Improvement
    - [ x ] Bug fix: **`Shorten: Fix 2744`**
    - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{SpiceRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

Changed HTTP to HTTPS

---

Instant Answer Page: https://duck.co/ia/view/shorten

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @danjarvis

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by tagawa** [comment]
Thank you for this @anthonyn60. We'll double-check it's OK with the HTTPS URL.

**Comment by tagawa** [comment]
@moollaza This is ready to be deployed to beta

**Comment by tagawa** [comment]
@anthonyn60 This is now working on beta: https://beta.duckduckgo.com/?q=shorten%20http://www.duckduckgo.com/about.html

It looks good to me. Please could you give it a final check? If you're happy, we can merge.

**Comment by tagawa** [comment]
This is strange - it won't trigger for me now. Yesterday it was fine, on Codio it's fine, but today on beta it's not working :-(

@moollaza Any idea why this has stopped triggering?

**Comment by tagawa** [comment]
Weird. Beta is OK again - I guess it was a temporary glitch - so I'm merging.
Thanks for the fix @anthonyn60. This should be live in a few days.

**Comment by edgesince84** [comment]
hey @anthonyn60, thank you for your contribution to DuckDuckHack, we really appreciate it! I'm reaching out to let you know that we recently launched a new forum with the initiative of improving programming-related searches, and I hope you'll [join us](https://forum.duckduckhack.com/)!

There are a lot of important tasks up for grabs that we'd like your help with, so feel free to and [jump in](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53).

**Pull request merged**
