### PR TITLE
Remove view from SoundCloud, no longer necessary

### PR DESCRIPTION
**Pull request by bsstoner**
@andrey-p 
cc @moollaza

### CODE REVIEW

**Comment by moollaza** [comment]
LGTM :+1:

**Comment by moollaza** [comment]
Whoops, wrong PR. But I'm pretty sure this is good too ;)

**Comment by bsstoner** [comment]
Wait, I jumped the gun here. This will work, but might break in the case where there's only 1 result returned by sound cloud. Want to make a few internal changes first before doing this.

**Comment by moollaza** [comment]
:+1:

**Pull request closed without merging**
