### PR TITLE
Currency: Fixes #3214 Support 'Currency' trigger

### LINKED ISSUE #3214: Currency: Support 'Currency' trigger
## Problem

In https://github.com/duckduckgo/zeroclickinfo-spice/commit/d6207c9804607d4d28234879a242f8ffd28df705, I added an edge case to stop the currency IA from trigger when a number wasn't present. This was to stop false positive triggering and resolve ambiguity. For example: 

screen shot 2017-03-28 at 10 53 39 am

From feedback, and internal unanswered query data we should still trigger this Instant Answer if the `currency` keyword is present. For example, `usd currency`, or `GBP currency`. This issue would be well suited to some new to DuckDuckHack.

## Solution

1. Add 2 or 3 tests
2. Build in logic to handle this
3. Run tests / test on duckpan
4. Send a PR

## People to notify
@pjhampton

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/currency

### PR DESCRIPTION
**Pull request by lernae**
## Description of new Instant Answer, or changes

"currency" keyword will now trigger currency IA with or without an amount.  For ex: "usd currency", "1 usd currency", "20 usd currency in mexican peso currency", etc.  

## Related Issues and Discussions

Fixes #3214 

## People to notify

@pjhampton 

---

Instant Answer Page: https://duck.co/ia/view/currency

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
Deploying to Beta...

**Comment by moollaza** [comment]
@lernae Thanks! This LGTM :+1:

Great job 💯

**Comment by bsstoner** [comment]
This was released to production 🚀

**Pull request merged**
