### PR TITLE
SublimePackages: add new download and clock icon to footer

### PR DESCRIPTION
**Pull request by moollaza**
Updates to meet newest design

- adds new download and clock icon to footer
- more to come...

Design:
screen shot 2015-05-26 at 9 43 11 am

/cc @abeyang @MrChrisW

### CODE REVIEW

**Comment by MrChrisW** [comment]
Beautiful :+:
Let's hope @abeyang approves :laughing:

**Comment by moollaza** [comment]
@abeyang here's how it looks with the styles applied...

sublime_text_packages_json_at_duckduckgo

**Comment by abeyang** [comment]
@moollaza looking good! A few things:

- Subtitle: Can we change the subtitle to the version number, to be more consistent with the other IAs? It's odd to have the developer as a subtitle, b/c it's not immediately clear what that is.
- Snippet: let's bring it down by 2px.
- Footer:
  - Let's shift the clock icon down by 1px, and
  - Right-align the date (and lose that *dot*)

**Comment by javathunderman** [comment]
Ping @moollaza

**Comment by MrChrisW** [comment]
>Subtitle: Can we change the subtitle to the version number, to be more consistent with the other IAs? It's odd to have the developer as a subtitle, b/c it's not immediately clear what that is.

@abeyang Unfortunately the API doesn't respond with the package version number, only the version of sublime text is supports. Example: https://duckduckgo.com/js/spice/sublime_packages/php

**Comment by abeyang** [comment]
@MrChrisW Ok, we can keep the author then. But can we prepend it with "by"? So it should look like this:

> by SublimeTextUser

**Comment by moollaza** [comment]
@MrChrisW looks like this one has merge conflicts now -- looks like we just need to add `by <user>` to the subtitle and this is good to go :+1:

**Comment by MrChrisW** [comment]
@moollaza Updated your changes :stuck_out_tongue_winking_eye: 
One issue is the default style for `.tile__sub` is `text-transform: capitalize;`  Fix: Changing it to `none` in a custom CSS file... although I'd like to avoid that.

2015-11-24-43-sublime text package php at duckduckgo

**Comment by moollaza** [comment]
> @moollaza Updated your changes :stuck_out_tongue_winking_eye: 

Whoops! I totally forgot this was ***my*** branch -- I scrolled up and saw your comments -- my bad, and thanks a lot for updating! @MrChrisW 

>One issue is the default style for .tile__sub is text-transform: capitalize; Fix: Changing it to none in a custom CSS file... although I'd like to avoid that.

That’s pretty minor, I think it's fine as-is.

**Comment by moollaza** [comment]
Result: 
sublime_text_package_handlebars_at_duckduckgo

**Pull request merged**
