### PR TITLE
Port Stopwatch to Goodies

### PR DESCRIPTION
**Pull request by mattr555**
Remove `Stopwatch` so it can be added in goodies.

Porting Issue: https://github.com/duckduckgo/zeroclickinfo-spice/issues/2463

Porting PR: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2846

https://duck.co/ia/view/stopwatch

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by jdorweiler** [comment]
This is waiting on https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2846?

**Comment by GuiltyDolphin** [comment]
@jdorweiler Yup! We need to get the Goodie versions merged before we can delete the Spice. Thanks for pointing this one out (needed the `On Hold` label).

**Comment by moollaza** [comment]
Going to Merge + Release this tomorrow..

/cc @MariagraziaAlastra

**Comment by GuiltyDolphin** [comment]
@moollaza Awesome - let me know how it goes (any issues) so we can make sure the other ports go smoothly!

**Comment by moollaza** [comment]
Thanks! This LGTM :+1:

**Pull request merged**
