### PR TITLE
Just Delete Me: Fix #2743 by replacing .includes() with .indexOf()

### LINKED ISSUE #2743: Just Delete Me: Replace `string.includes()` with IE friendly function
Our internal CasperJS tool failed when checking if this Instant Answers was online because of the `string.includes()` method which has been used, because it is not supported across all browsers.

We need to replace this with something that works in Chrome, Safari, FireFox and IE 9+

For now the IA has been disabled in Production

------
IA Page:  http://duck.co/ia/view/just_delete_me 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @riqpe

### PR DESCRIPTION
**Pull request by riqpe**
- [X] Improvement
    - [X] Bug fix: **`Just Delete Me: Fix #2743 by replacing .includes() with .indexOf()`**

###### Description of changes

Replaced String.prototype.includes() calls with calls to String.prototype.indexOf() for better support throughout different browsers.

###### Which issues (if any) does this fix?

Fixes #2743.

String.includes() method which has been used, was not supported across all browsers.

Replaced this with something that works in Chrome, Safari, FireFox and IE 9+

###### People to notify (@mention interested parties)

@moollaza 

---

Instant Answer Page: https://duck.co/ia/view/just_delete_me

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @riqpe

### CODE REVIEW

**Comment by daxtheduck** [comment]
@riqpe Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by tagawa** [comment]
Thank you very much for this PR @riqpe. One small comment - is it possible to remove the second parameter from the `indexOf` function, i.e. `indexOf(this)`, as the default for the second parameter is zero anyway.

**Comment by tagawa** [comment]
@riqpe Perfect! Thanks very much for this - IE users will be happy 😃

**Comment by edgesince84** [comment]
hey @riqpe thank you for your contribution to DuckDuckHack, we really appreciate it! I'm reaching out to let you know that we recently launched a new forum with the initiative of improving programming-related searches, and I hope you'll [join us](https://forum.duckduckhack.com/)!

There are a lot of important tasks up for grabs that we'd like your help with, so I hope you'll [jump in]](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53)!

**Pull request merged**
