### PR TITLE
Github: Enhance github search results (Closes #2518)

### LINKED ISSUE #2518: Github: Show more info in results
GitHub provides the following data as well in their search results:
- Language
- Number of Forks

Should we include it too?

IA Page: https://duck.co/ia/view/github

### PR DESCRIPTION
**Pull request by swapagarwal**
Show repository language in search results.
Closes #2518 
IA Page: https://duck.co/ia/view/github

### CODE REVIEW

**Comment by daxtheduck** [comment]
@swapagarwal Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by swapagarwal** [comment]
Screenshot

**Comment by moollaza** [comment]
@swapagarwal all this info won't fit into a single `<div>` -- we'll need to add another `<div class="one-line">` to contain the new info

**Comment by moollaza** [comment]
It should be two lines of text for the footer

**Comment by moollaza** [comment]
Or we can put the Language into a `altSubtitle`

**Comment by swapagarwal** [comment]
This needs a fork icon to be rendered nicely.

**Comment by swapagarwal** [comment]
This needs a fork icon to render nicely.

**Comment by swapagarwal** [comment]
Screenshot

**Comment by jagtalon** [comment]
@swapagarwal nice! although I think there's a little bit too much information in there in my opinion:

- Adding forks adds a bunch of clutter
- I don't think "Updated ..." is important at all, but I do think that the language is necessary

screen shot 2016-02-22 at 6 46 16 am

What do you think, @abeyang?

**Comment by swapagarwal** [comment]
@jagtalon Yep, that looks cleaner!

**Comment by moollaza** [comment]
>I don't think "Updated ..." is important at all, but I do think that the language is necessary

I would argue that `updated` is the best indication of whether or not the repo is active or stale. E.g most recent commit being last week vs 3 years ago tell you a lot.

**Comment by GuiltyDolphin** [comment]
I agree with @moollaza - if you're looking through for a project to use and/or contribute to - you'd want a rough indication of the activity.

**Comment by jdorweiler** [comment]
This pull request is being closed due to inactivity but, if anyone would like to continue it, please @ mention 'duckduckhack-contributors' for help and http://docs.duckduckhack.com/submitting/submitting-overview.html for reference.

**Comment by swapagarwal** [comment]
So, what are we going with? Only stars and language?

**Pull request closed without merging**
