### PR TITLE
AgeOfCelebrity spice instant answer

### PR DESCRIPTION
**Pull request by davidcroda**
What does your Instant Answer do? 
Calculates the age of a person from the birth date on their Wikipedia page.

What problem does your Instant Answer solve (Why is it better than organic links)? 
It immediately shows the user the answer to their question, without requiring them to perform math in their head

What is the data source for your Instant Answer? (Provide a link if possible)
Wikipedia

Why did you choose this data source?
It was suggested in the forumn post

Are there any other alternative (better) data sources?
Not that I know of

What are some example queries that trigger this Instant Answer?
How old is bill clinton
how old was Jimmy Hendrix
age of katy perry

Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)
Anyone who wants to know the age of someone famous

Is this Instant Answer connected to a DuckDuckHack Instant Answer idea?
Yes, https://duck.co/ideas/idea/4964/instant-answer

Which existing Instant Answers will this one supersede/overlap with?
None

Are you having any problems? Do you need our help with anything?
I am not sure if the matching is good enough. It has worked with my tests. Would it be better if I matched explicitly on month names in the regex? I could also use suggestions on layout. Wikipedia only provides a tiny thumbnail image, so I went with an icon layout.

What are the terms of use for the API? Will DuckDuckGo need specific authorization (e.g. an API key)? Are there any costs associated with API usage?
None

Where did you hear about DuckDuckHack? (For first time contributors)
HackerNews

What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)
screen shot 2015-03-08 at 11 15 40 pm

Checklist

Please place an 'X' where appropriate.

[X] Added metadata and attribution information
[X] Wrote test file and added to t/ directory
[X] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[X] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
[] Tested cross-browser compatibility
 ^ - I use a built in template with only text and an image

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 10

    - Windows 7
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 8
        [] IE 9
        [] IE 10

    - Windows XP
        [] IE 8

    - Mac OSX
        [X] Google Chrome
        [] Firefox
        [] Opera
        [] Safari

    - iOS (iPhone)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - iOS (iPad)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - Android
        [] Firefox
        [] Native Browser
        [] Google Chrome
        [] Opera

### CODE REVIEW

**Comment by MrChrisW** [comment]
Hi @davidcroda! Thanks for your contribution, we'll be sure to provide feedback shortly.  In the meantime can you update your initial comment to include the [pull request template](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/pull_request_template_spice.md) this will allow the community to get a quick overview of your new Instant Answer.

**Comment by davidcroda** [comment]
Updated, sorry, forgot about that part.

**Comment by MrChrisW** [comment]
Thanks for updating those details! We may want to look at using an alternative API to avoid using regex to extract the birthday as his can cause problems if the formatting changes. 

After a search this API looks good: https://prosperent.com/documentation/api/celebrity

Example: http://api.prosperent.com/api/celebrity?filterCelebrity=Jessica+Alba I'm unsure if there are any T&C of use. I'll investigate.

**Comment by davidcroda** [comment]
Sounds good, I will take a look at that API and updating my implementation later tonight.

**Comment by moollaza** [comment]
@davidcroda thanks a lot for this! But I wish you would have emailed us for approval first!

The only reason I say this is because we plan to handle these queries and surface this information using our current (internal) Wikipedia processing. The goal is to make most of the Wikipedia Infobox data into triggers so the whole system and query handling is more flexible.

This is pretty good and if we can use an alternative API that would simply things that's even better, but I just want to let you know that eventually this will be deprecated in favor of our own handling of this.

If you're OK with that and don't mind continuing, then you're absolutely welcome. If not, we can close this.

I'm happy either way, but obviously having this go live would be awesome even if its only around for a short while (probably some number of months)

**Comment by davidcroda** [comment]
@moollaza 

Makes sense, and not a problem. I really just wanted to try out the Instant Answer API. That request was tagged as "Developer Needed", and looked like low hanging fruit, so I took a crack.  However I can see how this could be a lot more useful with some actual natural language processing and a quality data source.

I will take a look at the alternate API. I doubt it will be much work to update the code to use it, and I might as well finish what I started.  However I won't be offended if you guys choose not to use it in production.

Thanks!

**Comment by moollaza** [comment]
>I will take a look at the alternate API. I doubt it will be much work to update the code to use it, and I might as well finish what I started. However I won't be offended if you guys choose not to use it in production.

Alright sounds good! Thanks again for taking the time to contribute @davidcroda!

**Comment by davidcroda** [comment]
On further review of the API, it really doesn't seem to provide any type of usage information. It seems to be intended for 3rd party marketers. There are no terms of use or attribution requirements listed. It seems like something that is not intended for mass consumption, and sort of seems sketchy as well.

As such, I think I am just going to close this. I appreciate you taking the time to review it, and best of luck on your actual Wikipedia integration and further development.

I will try to pick something actually useful next time I try to contribute! :+1:

**Pull request closed without merging**
