### PR TITLE
METAR Information: Change API url to https. Add new translation.

### LINKED ISSUE #2897: METAR Information: API Endpoint not working
Requesting http://avwx.rest/api/metar.php?station=klax&format=JSON&options=info,translate fails to load. See what the problem is or contact avwx.rest.

Thank you!

------
IA Page:  http://duck.co/ia/view/metar 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @santigl

### PR DESCRIPTION
**Pull request by santigl**
Fixes #2897 

###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.
- [ ] New Instant Answer: **`New {IA Name} Instant Answer`**
- [x] Improvement
  - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
  - [x] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
  - [ ] Other (Role, Template, Test, Documentation, etc.): **`{SpiceRole/Templates/Tests/Docs}: {Short Description}`**
###### Description of changes
- Change the API url to use https. 
- Add a "maintenance check warning" indicator to the table when that warning is specified in a metar.
###### Related Issues or Discussions

---

Instant Answer Page: https://duck.co/ia/view/metar

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @santigl

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by pjhampton** [comment]
Is it possible we can test this change, @santigl? https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/t/Metar.t

**Comment by santigl** [comment]
The input didn't change, @pjhampton, so it triggers in the same ways. And the output is still dynamic.

**Comment by pjhampton** [comment]
Ok, cool @santigl Thanks! 👍 
Next reviewer can merge / deploy

**Comment by moollaza** [comment]
@santigl Thanks! This LGTM :+1:

**Comment by santigl** [comment]
Great. :+1:  Thanks a lot @pjhampton and @moollaza !

**Pull request merged**
