### PR TITLE
New medium article spice

### PR DESCRIPTION
**Pull request by abhisheksp**
https://duck.co/ia/view/medium_article

### CODE REVIEW

**Comment by daxtheduck** [comment]
@abhisheksp Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@abhisheksp we ask that developers don't make their own API's for Instant Answers.

Also, it looks like this would violate the Medium.com Terms of Service which prohibits scraping their content or searching it via other means: https://medium.com/policy/medium-terms-of-service-9db0094a1e0f#.ntq85afch

Unfortunately I don't think we we can use this. Please try and use existing APIs offered by services. You're welcome to reach out to Medium to see if they'll allow this or if they can expose a search API for us to use

**Comment by abhisheksp** [comment]
I am in the process of talking to medium developers. Let me get back to you based on their reply.

**Comment by moollaza** [comment]
@abhisheksp any response from Medium?

I'm going to close this for now. If needed we can always reopen

**Pull request closed without merging**
