### PR TITLE
Add support for cast & crew, rename spice

### PR DESCRIPTION
**Pull request by whalenrp**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer: **`New {IA Name} Instant Answer`**
- [x] Improvement
    - [x] Bug fix: **`{IA Name}: Fix #2762`**
    - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{SpiceRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

This is a continuation of the thread on #2762

###### People to notify (@mention interested parties)
@moollaza @travisbell @GuiltyDolphin 

---

Instant Answer Page: https://duck.co/ia/view/movies_filmography

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @whalenrp

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by whalenrp** [comment]
Hey all. This is a followup to the comments on #2762.

@travisbell, thanks for the tip. I've updated the trigger and the test cases to include Crew along with cast results. I've also renamed the files per @moollaza's suggestion to Filmography, which I think generalizes the IA to include crew as well.

@moollaza, I wasn't able to find any mention of increasing the result page size for the API, but maybe this is something that @travisbell knows about?

**Comment by travisbell** [comment]
@whalenrp Great, that's a good addition.

We don't support custom page sizes but (without knowing how these responses are exactly queried/displayed) is it possible to query the second page and append the second page results to the results? Kind of like an autocomplete/lazy load situation?

**Comment by moollaza** [comment]
> is it possible to query the second page and append the second page results to the results? Kind of like an autocomplete/lazy load situation?

@travisball we support lazy loading additional results, however the issues is that these API requests are made client side and need to be proxied through DDG. We don't currently have a great way to do that though...

@whalenrp you may be able to use something like...

```perl
# optional second capture for "&page=#"
spice from => /([^/]+)/?([^/]+)?/;

spice to => 'http://api.themoviedb.org/3/discover/movie?with_people=$1&api_key={{ENV{DDG_SPICE_MOVIEDB_APIKEY}}}&sort_by=popularity.desc$2'
```

and do something like...

```js
var nextPage = "&page=" + $nextPageNum;
$.getJSON("/js/spice/movie_filmography/" + $query + "/" + encodeURIComponent($nextPage), function () {...});
```

It's kinda ugly though and I'm not sure if it'll work...

**Comment by moollaza** [comment]
@whalenrp this PR is giving us some trouble on Beta because of how we're handling the file renames -- totally not your fault -- so I've deployed it to my dev box and tested it there: https://moollaza.duckduckgo.com/?q=Movies+directed+by+Steven+Spielberg&ia=movies

Thanks! This LGTM :+1:

**Comment by travisbell** [comment]
Hey @moollaza 

I'm not seeing the Movies IA on beta or prod anymore, is this still going to make its way in?

**Pull request merged**
