### PR TITLE
Steam: Remove Steam Specials IA due to failing API.

### PR DESCRIPTION
**Pull request by MrChrisW**
Fixing #1372

### CODE REVIEW

**Comment by jagtalon** [comment]
@MrChrisW Aren't we waiting for @killerfish on this?

**Comment by MrChrisW** [comment]
@jagtalon Unfortunately @killerfish hasn't heard anything from Steam at this stage and has suggested [pulling the Spice](https://github.com/duckduckgo/zeroclickinfo-spice/issues/1372#issuecomment-69132063) for the time being.

**Comment by MrChrisW** [comment]
Not actually sure if this is the correct way to disable?

**Comment by jagtalon** [comment]
@MrChrisW gotcha

**Pull request merged**
