### PR TITLE
Namespace "Experimental IA" Spice CSS

### LINKED ISSUE #2635: Beta Instant Answers (Internal): CSS Should be Namespaced
The CSS rules for IA's must be prefixed with `.zci--<id>` to ensure that the CSS rules do not affect other elements on the page.

This IA should have it's CSS updated so that it only applies to the `.zci` container for its tiles.

------
IA Page:  http://duck.co/ia/view/experimentalia
Maintainer: @vikashvverma

### PR DESCRIPTION
**Pull request by rasikapohankar**
Issue #2635
Added `.zci--<id>` to the css rules.

IA Page: http://duck.co/ia/view/experimentalia

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by vikashvverma** [comment]
@rasikapohankar Thanks!
@moollaza LGTM

**Comment by rasikapohankar** [comment]
@moollaza @vikashvverma There isn't a lot of change here but I was just trying to test it using Duckpan server. The trigger is `.*` but it wasn't showing the answer. Is it possible to query for this instant answer? Also what is `$ENV{SHOW_IA_TESTING}`?

**Comment by rasikapohankar** [comment]
Needed to set the environment variable `SHOW_IA_TESTING` to 1 . Now it triggers the answer! :smile:

**Comment by vikashvverma** [comment]
@rasikapohankar yup, right!

**Comment by rasikapohankar** [comment]
@moollaza :)

**Comment by rasikapohankar** [comment]
Hey @moollaza! Can this be merged?

**Comment by moollaza** [comment]
@rasikapohankar Thanks! This LGTM :+1:

**Pull request merged**
