### PR TITLE
Lastfm (Song): Port to new spice api

### PR DESCRIPTION
**Pull request by killerfish**
@jagtalon I dont remember, but i think we used tags in some ia, was thinking perhaps we could add those here. (didnt put image, didnt seem very relevant).
SS below: -
lastfmsong

### CODE REVIEW

**Comment by jagtalon** [comment]
@killerfish thanks! Maybe it would work without the image for this one. CC @abeyang

**Comment by jagtalon** [comment]
@abeyang I have it up on a server https://ddh9.duckduckgo.com/?q=fuel+for+hatred+song+by+satyricon&ia=music :)

**Comment by jagtalon** [comment]
@abeyang ping! :)

**Comment by javathunderman** [comment]
Ping @abeyang

**Comment by jagtalon** [comment]
Hey, @killerfish! Some things from @abeyang:

- Remove Grooveshark since they're out of business
- Use the list view for this
- And can we remove the duration from the title, and add that as a line-item (below artist)? It should be: Duration: 3:51

**Comment by moollaza** [comment]
Closing. This is stale... Happy to reopen

**Pull request closed without merging**
