### PR TITLE
Currency: Adding lev Alias

### LINKED ISSUE #3207: Currency: Update alias for Bulgarian Lev
## Problem

Based on User Feedback, this Instant Answer isn't triggering how it should on Bulgaria's official currency. 

**Triggering:** 👍 

screen shot 2017-03-24 at 4 33 48 pm

**Not Triggering**: 👎 
screen shot 2017-03-24 at 4 33 21 pm

## Solution

1. Add a test for this, or two!
2. Update the [currencyNames](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/currency/currencyNames.txt#L14) file to make this triggering more lenient. 

## People to notify

@pjhampton

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [x] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/currency

### PR DESCRIPTION
**Pull request by BillyBarbaro**
## Description of new Instant Answer, or changes
Adds the Alias "lev" for the Bulgarian Lev.

## Related Issues and Discussions
Fixes #3207 

## People to notify
@pjhampton 

---
Instant Answer Page: https://duck.co/ia/view/currency

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by pjhampton** [comment]
@BillyBarbaro thanks! LGTM! ❤️  💙  💛  💜 
@moollaza can we get this push to beta, please? 😄

**Comment by moollaza** [comment]
Deploying to Beta!

**Comment by moollaza** [comment]
@BillyBarbaro Thanks! This LGTM :+1:

**Pull request merged**
