### PR TITLE
Fixes #2995: Movies/Filmography JS Error

### LINKED ISSUE #2995: Movies/Filmography: JS Error
I'm seeing an error, "jse_TypeError: data.results[0] is undefined". I think we need to check the JS objects before accessing them.

Example queries:
"movies with indiana in the title"
"movies with good scores"

@jagtalon

### PR DESCRIPTION
**Pull request by ManrajGrover**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.
- [ ] New Instant Answer: **`New {IA Name} Instant Answer`**
- [x] Improvement
  - [x] Bug fix: **`{Actor Filmography}: Fix {Issue number or one-line description}`**
  - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
  - [ ] Other (Role, Template, Test, Documentation, etc.): **`{SpiceRole/Templates/Tests/Docs}: {Short Description}`**
###### Description of changes

Moves getting `castId` after data check.
###### Related Issues or Discussions
#2995
###### People to notify

@mention any relevant people/organizations
@b2ddg @jagtalon @moollaza 

---

Instant Answer Page: https://duck.co/ia/view/movies_filmography

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mention
@whalenrp

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by ManrajGrover** [comment]
@moollaza Let's deploy it on beta to test it 😄

**Comment by sahildua2305** [comment]
@ManrajGrover Can we have some additional tests (can be taken from the actual issue reported) to make sure that issue isn't there anymore?

**Comment by ManrajGrover** [comment]
@sahildua2305 The queries mentioned in the issue actually trigger the IA. This was more of a Front End bug where API doesn't provide any API and code was trying to access an undefined object. `Spice.failed()` is called in case it `hasFailed`. We can add these test cases for backend triggering but as far as I remember, there is currently no way to test the front end in place right now.

/cc @moollaza

**Comment by whalenrp** [comment]
Agreed. Short of testing in beta, I don't think there's any infrastructure
for testing the Javascript side of things.

**Comment by ManrajGrover** [comment]
@moollaza Looks like PR isn't deployed to beta. It is still using old code.

**Comment by moollaza** [comment]
@ManrajGrover this is now deployed, and looks to be working 👍 

Thanks for the awesome fix 💯

**Pull request merged**
