### PR TITLE
fixes github trigger for repo search #2512

### PR DESCRIPTION
**Pull request by Sayanc93**
fixes issue #2512

### CODE REVIEW

**Comment by daxtheduck** [comment]
@Sayanc93 Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@Sayanc93 unfortunately this doesn't solve the problem. "github" is OK as a trigger, but we need to make sure that the query contains more than just `github` -- we need to check that the remainder is defined and is not `''`.

--

Don't forget to update the tests as well!

**Comment by moollaza** [comment]
@duckduckgo/duckduckhack-mentors -- Anyone able to assist @Sayanc93 with a correct solution?

**Comment by soleo** [comment]
@moollaza I don't think there are any issues with q=github. The production duckduckgo.com displays news feed about GitHub. In dev environment, it triggers GitHub status which is it supposed to behave. The query in github.pm is guarded with the following snippet. 
```perl
    s/^github\s+|\s+github$//;
    if ($_ eq "" || m/\bjobs\b|\bstatus\b/) {
        return;
    }
```
I think the issue and PR should be closed.

**Comment by soleo** [comment]
query github is test case in github_status as well.

```perl
'github' => test_spice(
        '/js/spice/github_status/github',
        call_type => 'include',
        caller => 'DDG::Spice::GithubStatus'
    ),
```

**Comment by moollaza** [comment]
@soleo I'm definitely seeing the GitHub Spice trigger for the query "GitHub":
github_at_duckduckgo

I consider that an irrelevant result because those repos are pretty random.

I think we previously considered "github" and OK query for the GitHub Status IA, but now that I'm seeing it, I feel it's also irrelevant. Anyone searching for "GitHub" is probably trying to get to the site, or trying to figure out what it is. If you wanted to know if the site is working you'd probably search for something like "github status" or "is github,com up?"

**Comment by Sayanc93** [comment]
@moollaza - will using regex be suitable in this case?

**Comment by moollaza** [comment]
> @moollaza - will using regex be suitable in this case?

Not for the triggers -- we can use `github status` as the trigger, or `github` and then use a `regex in the handle` to ensure it matches some pattern

Regex should only be necessary when matching substrings or patterns of letter/numbers

**Comment by GuiltyDolphin** [comment]
@moollaza As far as I can tell this is a *really* easy fix:

Change line 21 from `s/^github\s+|\s+github$//;` to `s/^github\s*|\s+github$//;`.

**Comment by jagtalon** [comment]
@Sayanc93 please add a test as well and this should be good!

**Comment by Sayanc93** [comment]
@jagtalon - can this be merged now?

**Comment by GuiltyDolphin** [comment]
@Sayanc93 Thanks, looks good! :dolphin:

**Pull request merged**
