### PR TITLE
Use alt_to attribute instead of separate modules

### PR DESCRIPTION
**Pull request by zachthompson**
Certain instant answers are using modules solely to define additional javascript end points.  Use the new `alt_to` attribute instead.

Depends on https://github.com/duckduckgo/duckduckgo/pull/163

### CODE REVIEW

**Comment by zachthompson** [comment]
alt_to keys should be updated to match

**Comment by b2ddg** [comment]
@zachthompson Should this PR be looked at after https://github.com/duckduckgo/duckduckgo/pull/163, or should I review with the others?

**Comment by zachthompson** [comment]
@b2ddg I would use this with the main ddg pr to verify that they work.

**Comment by b2ddg** [comment]
@zachthompson ok cool, I used the xkcd one to verify it worked internally. Some of them, like Canistreamit.pm, look like there isn't an alternative. Are those deprecated and intentionally deleted?

**Comment by zachthompson** [comment]
Yes, there are few that have just been removed.  Not in Blocks nor are there plans for them returning.

**Comment by moollaza** [comment]
Thanks! This LGTM :+1: Tested & Working

**Pull request merged**
