### PR TITLE
Remove Spice Code, Port Timer to Goodies

### PR DESCRIPTION
**Pull request by GuiltyDolphin**
This PR removes the `Timer` Spice.

Goodies PR: duckduckgo/zeroclickinfo-goodies#2253

Porting Issue: duckduckgo/zeroclickinfo-spice#2463

---

IA Page: https://duck.co/ia/view/timer

### CODE REVIEW

**Comment by daxtheduck** [comment]
## [Timer](https://duck.co/ia/view/timer)

**Description**: Displays a countdown timer

**Example Query**: [timer](https://beta.duckduckgo.com/?q=timer), [timer 4 mins](https://beta.duckduckgo.com/?q=timer 4 mins)

**Tab Name**: Timer

**Source**:  

*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/timer)*

---
*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/timer)*

**Comment by moollaza** [comment]
@GuiltyDolphin if you can resolve the conflicts here I can push this onto Beta so the Goodie will work 👍

**Comment by GuiltyDolphin** [comment]
@moollaza C'est done.

**Comment by moollaza** [comment]
Deploying...

**Comment by moollaza** [comment]
@GuiltyDolphin Thanks! This LGTM :+1:

**Pull request merged**
