### PR TITLE
AlternativeTo: Improve triggering

### PR DESCRIPTION
**Pull request by sahildua2305**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer: **`New {IA Name} Instant Answer`**
- [x] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [x] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{SpiceRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes
I noticed that this IA doesn't get triggered for query `opensource alternative to github` because the space between `open` and `space` wasn't optional.

###### People to notify (@mention interested parties)
@moollaza 

---

Instant Answer Page: https://duck.co/ia/view/alternative_to

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @vikashvverma

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by edgesince84** [comment]
Cool, thanks for the fix, @sahildua2305!

**Comment by moollaza** [comment]
@sahildua2305 please add a test to ensure the updated triggering works as expected 👍

**Comment by moollaza** [comment]
@sahildua2305 Thanks! This LGTM :+1:

**Comment by sahildua2305** [comment]
:tada:

**Pull request merged**
