### PR TITLE
travis status IA

### PR DESCRIPTION
**Pull request by josephwegner**
**What does your Instant Answer do?**
It grabs Travis CI's status from the Statuspage.io page, and shows them to the user.

**What problem does your Instant Answer solve (Why is it better than organic links)?**
Quickly see if Travis is down or not, and which pieces are actually down.

**What is the data source for your Instant Answer? (Provide a link if possible)**
StatusPage.io: http://status.travis-ci.com/index.json

**Why did you choose this data source?**
It is where Travis posts its own status updates

**Are there any other alternative (better) data sources?**
Twitter, maybe?

**What are some example queries that trigger this Instant Answer?**
"Travis Status", "Travis Up"

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
programmers

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
I don't think so

**Which existing Instant Answers will this one supersede/overlap with?**
None

**Are you having any problems? Do you need our help with anything?**
Nope

**What are the terms of use for the API? Will DuckDuckGo need specific authorization (e.g. an API key)? Are there any costs associated with API usage?**
Nope

**Where did you hear about DuckDuckHack? (For first time contributors)**
Second time

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
screen shot 2014-11-18 at 3 06 53 pm

## Checklist
Please place an 'X' where appropriate.

```
[x] Added metadata and attribution information
[x] Wrote test file and added to t/ directory
[x] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[x] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
[x] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 10

    - Windows 7
        [x] Google Chrome
        [x] Firefox
        [] Opera
        [] IE 8
        [x] IE 9
        [x] IE 10

    - Windows XP
        [] IE 7
        [] IE 8

    - Mac OSX
        [x] Google Chrome
        [x] Firefox
        [x] Opera
        [x] Safari

    - iOS (iPhone)
        [x] Safari Mobile
        [] Google Chrome
        [] Opera

    - iOS (iPad)
        [x] Safari Mobile
        [] Google Chrome
        [] Opera

    - Android
        [] Firefox
        [x] Native Browser
        [] Google Chrome
        [] Opera
```

### CODE REVIEW

**Comment by josephwegner** [comment]
so... is this good to go? IMO, the design is a pretty good mapping to the status that gets sent back.

**Comment by abeyang** [comment]
Hi @josephwegner, sorry for the long silence -- Christmas/New Year's holidays hit right after our convo. 

I'm not comfortable in releasing the current design (assuming you haven't made any changes since our convo), given that the colors seem to suggest severity, when in fact it doesn't.

I'm in the middle of working on a design -- will try to get something out to you in a day or two. Thanks for your patience!

**Comment by abeyang** [comment]
@josephwegner again, sorry for the delay. We were toying around with making this IA more beefed up given the available API, but since it'll take more time for us to iterate and fine-tune, we think we can go for the simpler approach for now:

travis-status-v1 1

It's very close to what you already have. However, rather than having the color indicate progress (as you had it), color should indicate severity (as statuspage.io has it). Also, the byline should indicate when it was last checked.

LMK if you have any further questions!

**Comment by jagtalon** [comment]
This is good for now! :+1: Will have to change the colors in another PR

**Comment by jagtalon** [comment]
@josephwegner It's live! https://duckduckgo.com/?q=travis+ci+status&ia=status

**Pull request merged**
