### PR TITLE
Octopart: Include relevancy checking against item title

### LINKED ISSUE #2207: Octopart: triggering for "___ specs"
Is there a way to adjust the trigger so it doesn't show for queries like "<product> specs"? These look pretty bad and are probably popular searches:

screen shot 2015-09-28 at 1 18 23 pm
screen shot 2015-09-28 at 1 19 55 pm

------
IA Page:  http://duck.co/ia/view/octopart

### PR DESCRIPTION
**Pull request by MrChrisW**
Fixes #2207

This allows queries like the following by checking the query against the item title
+ [atmega datasheet](https://beta.duckduckgo.com/?q=atmega+datasheet&ia=parts)
+ [ne555 specs](https://beta.duckduckgo.com/?q=ne555+specs&ia=parts)

Queries - will not trigger
+ people round specs 
+ apple watch specs

-----
IA Page: https://duck.co/ia/view/octopart

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
Deploying to beta...

**Comment by moollaza** [comment]
Whoos, @MrChrisW don't forget to link an IA page! We need them to deploy to beta :+1:

**Comment by MrChrisW** [comment]
@moollaza Fixed.

**Comment by moollaza** [comment]
@MrChrisW Thanks! This LGTM :+1:

I think we could even make `specs` an `end` trigger because I can't see many people searching "specs X". All the queries in the autocomplete that start with specs are unrelated to Octopart... It seems "Specs" is a store in the US?

**Pull request merged**
