### PR TITLE
Forecast: Addition of precipitation to the forecast result (#2795)

### LINKED ISSUE #2795: Forecast: Add % precipitation to answer
could show % precipitation to answer as this could be useful to some users.

------
IA Page:  http://duck.co/ia/view/forecast 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @himanshu0113

### PR DESCRIPTION
**Pull request by lernae**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer: **`New {IA Name} Instant Answer`**
- [X ] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [X ] Enhancement: **`Forecast: Fixes #2795 by adding precipitation to the forecast result for current conditions`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{SpiceRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

As per enhancement suggested in #2795, this change will add precipitation to be included in the forecast result for current conditions.  In addition to updating the handlebars and the js to include precipitation in the current results, css was also updated in order to allow enough space for precipitation to be displayed.

###### Which issues (if any) does this fix?

Fixes #2795 - This is an enhancement that will add precipitation into the forecast result.

###### People to notify (@mention interested parties)
@himanshu0113

---

Instant Answer Page: https://duck.co/ia/view/forecast

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @himanshu0113

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by tagawa** [comment]
Thank you for this improvement @lernae. It's now up on the beta server: https://beta.duckduckgo.com/?q=weather+in+yokohama&ia=weather

There's one issue - please could you round the percentage to the nearest integer? That will fix the layout problem in the screenshot.

weather-ia-precipitation

**Comment by lernae** [comment]
Hi @tagawa- Rounding precipitation percentage to the nearest integer is now in.

**Comment by tagawa** [comment]
Thanks @lernae - looking good now! I'll leave this open for a couple of days to see if there are any further review comments, then it should be good to merge.

https://beta.duckduckgo.com/?q=weather+in+yokohama&ia=weather
weather-ia-precipitation_fixed

**Comment by tagawa** [comment]
@lernae Let's merge this. Thanks again for adding this improvement! 🌈 

And if you'd like to continue contributing, we're currently on a programming mission, aiming to improve Instant Answers for developers. More info on how to help out here: https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53

**Pull request merged**
