### PR TITLE
PeopleInSpace: Add People's rank to IA

### PR DESCRIPTION
**Pull request by vikashvverma**
Fixes https://github.com/duckduckgo/zeroclickinfo-spice/issues/2574

IA Page: https://duck.co/ia/view/people_in_space
Maintainer: @elebow

### CODE REVIEW

**Comment by daxtheduck** [comment]
@vikashvverma Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by elebow** [comment]
Looks good to me :thumbsup:.

In the future, I recommend putting new code and cleanup changes in separate commits. That will help reviewers isolate what has changed.

**Comment by vikashvverma** [comment]
@elebow sure

**Comment by vikashvverma** [comment]
@GuiltyDolphin I think, this can be merged now!

**Comment by moollaza** [comment]
This will require a design review -- I don't believe this currently looks acceptable.

@abeyang can you give this a look over?

I suspect we should remove the `()`, increase the font size a bit and give it a lighter color?

We may need to increase the tile height because it looks a little cluttered.

Deploying to Beta now..

**Comment by moollaza** [comment]
This PR is being closed due to inactivity. If you're still interested in finishing, please let me know and I'll gladly re-open it for you!

**Pull request closed without merging**
