### PR TITLE
Fix octopart console errors

### PR DESCRIPTION
**Pull request by bsstoner**
screen shot 2015-09-28 at 1 12 04 pm

@jagtalon
cc @moollaza

### CODE REVIEW

**Comment by jagtalon** [comment]
@bsstoner checking!

**Comment by jagtalon** [comment]
@bsstoner it's a bit weird that the datasheet button just links to the current page because there's no URL in the a tag. 

screen shot 2015-09-28 at 2 27 49 pm

What if we link to https://octopart.com/contact/send_file?ppid=24675717&type=datasheet&continue_to=/721007-carlisle-24675717 instead and the button saying "Send a Datasheet"? This might be a design question though, but would love to hear what you think!

**Comment by bsstoner** [comment]
Why if we add a conditional to the template and hide the button? https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/octopart/buy.handlebars

**Comment by jagtalon** [comment]
@bsstoner that might be the best solution so go for it! :)

**Comment by jagtalon** [comment]
@bsstoner nice! :+1:

**Pull request merged**
