### PR TITLE
Whois: Fixed the sourceUrl

### PR DESCRIPTION
**Pull request by davidofferman**
I've noticed that the Whois spice didn't redirect to a valid page when you click on the link that appears on the bottom of the instant answer. I modified the URL to now redirect to the correct page.

One issue is, I couldn't find a URL that would show the "raw text" version of the whois response. The best I could get is JSON, and then the user can click over to the "raw text" page. 

---

Instant Answer Page: https://duck.co/ia/view/whois

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @b1ake

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by davidofferman** [comment]
I found a URL which may work better than the one I used. The downside is it's not HTTPS, but it has the advantage of loading faster and it shows the result in raw format instead of json.

http://whois.whoisxmlapi.com/duckduckgo.com

If the lack SSL/TLS doesn't matter, I'll make the change.

**Comment by b1ake** [comment]
@davidofferman I like that output from the `http` version of the URL, e.g. http://whois.whoisxmlapi.com/duckduckgo.com. Good job finding it!

The `https` version in this PR isn't working for me, here's what I see:

screen shot 2016-07-25 at 10 18 20 am

I'd recommend changing the PR to use the `http` version, and then we'll ping @moollaza and make sure he's okay with that.

**Comment by davidofferman** [comment]
@b1ake I changed the URL to the new whois results page. In your screenshot, it's showing the old URL that I removed in my first commit. Did you possibly pull the wrong branch?

**Comment by b1ake** [comment]
@davidofferman Ah I see, sorry for testing with the wrong https URL. I was actually just using the beta server: https://beta.duckduckgo.com/?q=whois+http%3A%2F%2Fduckduckgo.com&ia=whois. I'm not sure how often that is updated with the new code

**Comment by b1ake** [comment]
@davidofferman 👍 LGTM. @moollaza, are you okay with the 'More at' link pointing to an `http` URL? If so, it's ready to merge.

**Comment by moollaza** [comment]
LGTM :+1:

**Pull request merged**
