### PR TITLE
Remove color picker

### LINKED ISSUE #2463: Port non-API Spice to Goodies
Goodies can support JS too! Any Spice that doesn't require API calls should be ported to Goodies, if you're interested, please follow the Guidelines below.
### Choosing a Spice
1. **Pick an available Spice from the `Relevant Spices` list** (if you have mentioned that you would like to port a Spice, but can no longer do so for any reason, please let me know so I can make it clearly available again).
2. **Comment to let me know which Spice you are interested in porting**, feel free to inquire about Spices that are taken but haven't seen any development for a long time.
### Porting the Spice
1. If you want to move any of the JS into Perl, feel free, but the functionality must remain the same (**_if you are extending the functionality at all, please make that clear in your pull request!**_).
2. Update the tests accordingly - the test format will no longer be the same. If you are able to do so, please update the tests to actually show results rather than just responses.
3. Make sure the tests pass (use `duckpan test` to test everything and `duckpan test SPICE_NAME` (where `SPICE_NAME` is the name of the Spice being ported) to test the Spice).
### Uploading your changes
1. Make a pull request with the title `Port SPICE_NAME to Goodies` where `SPICE_NAME` is the name of the Spice you are porting. You should make one PR on Spice, which removes the Spice, and one on Goodies, which ports the functionality. **_Please link to the PR on the other repo as well as this issue for both pull requests!**_
2. Add a link to the IA page of the Spice in the PR description. **Do not create a new IA page for the Goodie version**.
3. If you have changed the functionality at all, please let us know in the pull request!
## Relevant Spices
- [ ] `Editor`
- [x] `Timer`
- [x] `Geometry`
- [x] `ColorPicker`
- [x] `Stopwatch`
- [x] `FlashVersion`

---

Reference to the Goodie issue: duckduckgo/zeroclickinfo-goodies#2258

### PR DESCRIPTION
**Pull request by ManrajGrover**
##### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer: **`New {IA Name} Instant Answer`**
- [x] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [x] Enhancement: **`{ColorPicker}: {Removes ColorPicker IA}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{SpiceRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

This pull request removes Color Picker IA. This has been ported to Goodies.

###### Which issues (if any) does this fix?

Fixes #2463

###### People to notify (@mention interested parties)

@moollaza @zekiel 

---

Instant Answer Page: https://duck.co/ia/view/color_picker

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mention
@chrisharrill

### CODE REVIEW

**Comment by daxtheduck** [comment]
@ManrajGrover Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by edgesince84** [comment]
thanks Manraj!

**Comment by moollaza** [comment]
@ManrajGrover thanks! Deploying to Beta

**Comment by moollaza** [comment]
@ManrajGrover Thanks! This LGTM :+1:

**Pull request merged**
