### PR TITLE
Bible: adding verse of the day

### LINKED ISSUE #2929: Bible verse of the day
@hunterlang @MAMAMIA9 @pnpninja I was experimenting with learning about the IAs and made some updates to the Bible spice for verse of the day if wanted to include this in the IA.  I can open a pull request if want to include.
https://github.com/gerlachry/zeroclickinfo-spice/tree/gerlachry/bible-verse-of-day2

### PR DESCRIPTION
**Pull request by gerlachry**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer: **`New {IA Name} Instant Answer`**
- [X] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [X] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{SpiceRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

Adding 

> bible verse of the day

 triggers and tests.  Uses the NET Bible API [verse of the day](http://labs.bible.org/api_web_service).  The default 1 day caching seems ok for this verse of the day or should this one also be split out to a separate IA like what is being suggested in #2826 for random bible verse and then enable a much longer cache duration on this current IA?

###### Which issues (if any) does this fix?

Fixes #2929  - Adds regex for verse of day and various tests.

###### People to notify (@mention interested parties)
@pnpninja @tagawa @hunterlang 

---

Instant Answer Page: https://duck.co/ia/view/bible

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mention

### CODE REVIEW

**Comment by daxtheduck** [comment]
@gerlachry Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by tagawa** [comment]
@gerlachry Thank you for adding this. I think a day's caching would be fine and combining it as you've done here will work. However there seems to be an issue installing it on the beta server. Not sure what's going on so I'll try to look into it.

**Comment by gerlachry** [comment]
@tagawa Thanks.  If need something from me or additional updates for deploying let me know.

**Comment by tagawa** [comment]
Hi @gerlachry. I've looked into this a bit more but can't see the problem. Your code looks fine, it works for me in Codio, and all the tests pass. I've asked for some expert help from a colleague so hopefully we can get it fixed soon.

**Comment by tagawa** [comment]
Thanks to @jdorweiler working his magic, this is now working on the beta server for testing: https://beta.duckduckgo.com/?q=bible+verse+of+the+day&ia=answer
Let's give it a few days to see if there are any review comments, and after that we can merge.

**Comment by tagawa** [comment]
@gerlachry We've had no further review comments and this is working well for me on the beta server (and the previous functionality is unaffected) so let's merge! Thanks again for this improvement 😄

**Pull request merged**
