### PR TITLE
Add Bower instant answer

### PR DESCRIPTION
**Pull request by francisbrito**
**What does your Instant Answer do?**
Displays a list of matching Bower packages.

**What problem does your Instant Answer solve (Why is it better than organic links)?**
Cumbersomeness in remembering where Bower packages are located at.

**What is the data source for your Instant Answer? (Provide a link if possible)**
[Bower Package Registry API](http://bower.herokuapp.com/packages)

**Why did you choose this data source?**
Its the official place to get Bower package list from.

**Are there any other alternative (better) data sources?**
No. AFAIK.

**What are some example queries that trigger this Instant Answer?**
`bower underscore` or `angular bower`.

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
Web developers.

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
Yes

**Which existing Instant Answers will this one supercede/overlap with?**
SearchCode

**Are you having any problems? Do you need our help with anything?**
Sometimes, when searching for a term that returns many packages (`bower jquery` for example) the Instant Answer displays **all** matches. It would be nice if I could limit the amount of packages to XX amount. I know this can done manually by "cutting" the API result into a smaller subset, but I'd like to know what you guys think before actually making that change.

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
bower-ia-scrot

## Checklist
Please place an 'X' where appropriate.

```
- [X] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
- [X] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
- [X] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
- [X] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
- [X] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        - [X] Google Chrome
        - [X] Firefox
        - [X] Opera
        - [X] IE 10

    - Windows 7
        - [] Google Chrome
        - [] Firefox
        - [] Opera
        - [] IE 8
        - [] IE 9
        - [] IE 10

    - Windows XP
        - [] IE 7
        - [] IE 8

    - Mac OSX
        - [] Google Chrome
        - [] Firefox
        - [] Opera
        - [] Safari

    - iOS (iPhone)
        - [] Safari Mobile
        - [] Google Chrome
        - [] Opera

    - iOS (iPad)
        - [] Safari Mobile
        - [] Google Chrome
        - [] Opera

    - Android
        - [] Firefox
        - [] Native Browser
        - [] Google Chrome
        - [] Opera

```

### CODE REVIEW

**Comment by moollaza** [comment]
@francisbrito Thanks a lot for contributing, we really appreciate it :smiley:. 

This looks like a great start but I'm concerned about the lack of info for each package. Our other package search Instant Answers use APIs which provide some basic information (like a description) about the package.

I notice a search on bower.io (http://bower.io/search/?q=angular) provides a different list of results, but each has a description, owner, star rating, etc.

In the backend they seem to be making a single request to a hosted list but the size is massive because it seems to be an exhaustive list of all packages. Do you happen to know if there's a better API which we can use that provides details and preferably a limit on the number of results?

**Comment by francisbrito** [comment]
Thanks for the quick response @moollaza! :)

The data being displayed at bower.io/search is a "beefed-up" version of what is returned by the Bower registry, in fact its code references it ([here](https://github.com/bower/search-server/blob/master/component-list.js#L8)). The inconsistency between the packages at bower.io and those at the registry is related to [an issue](https://github.com/bower/search-server/issues/20) with the former where some packages whose URL has being updated are being skipped over. 

I suggest that the registry be used since it would make this instant answer homologous to using the Bower CLI `search` command. 

Here's a comparison of results from the registry and the CLI:
bower-cli-registry-cmp-scrot

On the other bower.io/search [does](https://bower-component-list.herokuapp.com/keyword/jquery) provide a way to filter packages so it could be used instead.

**Comment by francisbrito** [comment]
@moollaza alternatively I could try bower.io/search's approach, i.e: downloading the enhanced JSON file and filtering results manually. Any thoughts?

**Comment by davidjbradshaw** [comment]
Just to update you https://github.com/bower/search-server/pull/21

**Comment by moollaza** [comment]
@davidjbradshaw thanks for the head's up!

@francisbrito my biggest concerns are the size of the request and the usefulness of the result. We try to keep them as small as possible so the Instant Answer displays nice and quickly and we obviously would like to show as much relevant info as we can. It seems like the bower-component-list `keyword` endpoint is pretty good, but that search for "jQuery" returns a pretty large response (400kb). Other searches I tried were relatively quick/small so I think it's ok to move forward with that.

You can use a [relevancy block](https://duck.co/duckduckhack/spice_displaying#relevancy-blocks) to help make sure results are relevant if the results from there aren't very relevant.

Let me know how it goes!

**Comment by moollaza** [comment]
Ping! @francisbrito just checking in -- are you still interested in working on this?

**Comment by moollaza** [comment]
Closing. @francisbrito if you'd still like to finish this, please let us now and we can re-open the PR :)

**Pull request closed without merging**
