### PR TITLE
Improvement Bug fix: Forvo: Fix 2621

### LINKED ISSUE #2621: Forvo: Layout breaks with long words on small screens
Search results with long words/phrases break the layout on small screens where the result must take up more than one line. For example, searching "pronounce cheese" on the iPhone 6 returns "Peter Anderson cheese [en]", which wraps and takes up two lines in portrait. This causes all of the genders, nationalities, and flags on the right to be offset down by almost a line.
asset

------
IA Page:  http://duck.co/ia/view/forvo

### PR DESCRIPTION
**Pull request by carolyz**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer: **`New {IA Name} Instant Answer`**
- [x] Improvement
    - [x] Bug fix: **`Forvo: Fix 2621`**
    - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{SpiceRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

Fixed layout issue with small displays where the sidenote (right) doesn't align with the words (left). 

###### Which issues (if any) does this fix?

Fixes #2621 - Added ` display:table-cell;` to relevant elements in forvo.css. This is my first time doing this so definitely give me a shout if there is anything out of place.

###### People to notify (@EpicWolverine)

---

Instant Answer Page: https://duck.co/ia/view/forvo

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @alexbaforvo

### CODE REVIEW

**Comment by daxtheduck** [comment]
@carolyz Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by alohaas** [comment]
Hey @carolyz thanks for this fix! I'll take a look, but we should be able to merge soon :)

**Comment by alohaas** [comment]
hey @carolyz if you look at the IA on the duckduckgo beta server, it looks like the layout is still not quite right - https://beta.duckduckgo.com/?q=how+to+pronounce+aluminum&ia=answer. 

I would suggest following the advice in the issue comments and use `text-overflow: ellipsis;` rather than `display: table-cell;`. For more information on how to use the `ellipsis` property, check out this post - https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/

**Comment by carolyz** [comment]
Hey @alohaas I've implemented `text-overflow: ellipsis;` and everything looks okay on my end. Thanks for getting back so quickly! Let me know if it could be improved in any way!

**Comment by alohaas** [comment]
Thanks @carolyz. Looks great 👍 

screen shot 2016-06-13 at 12 07 48 pm

**Pull request merged**
