### PR TITLE
Invalidate XKCD cache every 6 hours

### LINKED ISSUE #2634: XKCD: Cached comics are outdated
The ZCI shows another comic than the website. It is not up to date.
Didn't check the source, but it seems as if it is not able to update properly.

------
IA Page:  http://duck.co/ia/view/xkcd 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sdball

### PR DESCRIPTION
**Pull request by gaulrobe**
Fixes #2634 

In order to be more up-to-date with newer XKCD comics, how does a 6 hour cache sound?

https://duck.co/ia/view/xkcd

### CODE REVIEW

**Comment by daxtheduck** [comment]
@gaulrobe Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by mattr555** [comment]
@gaulrobe Thanks a lot for this fix! Why don't we bump it down to 1 hour? xkcd serves enough traffic that they can handle a few more hits from us :)

Also, could you add the same `proxy_cache_valid` to the other endpoint (as described [here](http://docs.duckduckhack.com/backend-reference/api-reference.html#attributes-of-altto-endpoints))? Without it, the caches could fall behind from each other and wrongly miss a "Next" link.

**Comment by gaulrobe** [comment]
@mattr555 thanks for catching that! 1 hour sounds good to me too. Fixed!

**Comment by mattr555** [comment]
Awesome, thanks again! :ship:

**Pull request merged**
