### PR TITLE
DOTA 2 Heroes: Fix the buggy "more at" link

### LINKED ISSUE #2793: DOTA 2 Heroes: "more at" link not always working
When viewing the Queen of Pain IA, the "more at" link in the IA does not link to the directly Queen of Pain overview on dota2.com.  It brings you to the general "choose a hero" screen.  It links directly to other heros' profiles when viewing their IA and following the "more at" link.    Is there anything actionable there?  It might just be an issue with dota2.com

------
IA Page:  http://duck.co/ia/view/dota2 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @echosa

### PR DESCRIPTION
**Pull request by sahildua2305**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer: **`New {IA Name} Instant Answer`**
- [x] Improvement
    - [x] Bug fix: **`DOTA 2 Heroes: Fix #2793`**
    - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{SpiceRole/Templates/Tests/Docs}: {Short Description}`**

###### Which issues (if any) does this fix?

Fixes #2793 

###### People to notify (@mention interested parties)

---

Instant Answer Page: https://duck.co/ia/view/dota2 

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @echosa

### CODE REVIEW

**Comment by daxtheduck** [comment]
@sahildua2305 Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by echosa** [comment]
Simple enough. Seems like it should work. :+1:

**Comment by sahildua2305** [comment]
@moollaza Maintainer approved. :smiley:
Thanks @echosa :smile:

**Comment by moollaza** [comment]
@sahildua2305 Thanks! This LGTM :+1:

**Pull request merged**
