### PR TITLE
Updating API to fix existing Indego Bikeshare IA

### PR DESCRIPTION
**Pull request by AcriCAA**
@moollaza I updated the API url here.  Let me know if you need anything else.  Thanks again. 

-----
IA Page: https://duck.co/ia/view/bike_sharing_indego_phl

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata post coming soon

**Comment by AcriCAA** [comment]
@moollaza updated url in this pull request.

**Comment by moollaza** [comment]
@AcriCAA thanks! Deploying to Beta...

**Comment by moollaza** [comment]
@AcriCAA it works!

Thanks! This LGTM :+1:

**Comment by AcriCAA** [comment]
@moollaza. Looks like it's working on Beta. Nice.

**Pull request merged**
