### PR TITLE
WIP: forvo audio with single item

### PR DESCRIPTION
**Pull request by jdorweiler**
The audio view currently only shows tiles.  We should have a single item audio view. selection_047
cc @chrismorast @bsstoner @russellholt

### CODE REVIEW

**Comment by javathunderman** [comment]
@moollaza @jagtalon @jdorweiler I'm going to pick this up and see what happens, but I'm not really sure if I'm the best person to tackle this. Anyone else want to do this?

**Comment by moollaza** [comment]
@javathunderman give it a go! We're all here to help :+1:

**Comment by javathunderman** [comment]
@moollaza Is there any old code to work off of?

**Comment by moollaza** [comment]
@javathunderman there was a branch that I deleted because it was really outdated. I would model this after the SoundCloud IA in terms of the JS and templates:

https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/sound_cloud/sound_cloud.js#L38

The most important part is specifying the `model` and `view` are Audio. This will allow the tiles to automatically have an audio player so that clicking the tile will play the audio and show the progress.

**Comment by moollaza** [comment]
I restored the branch so you can see the old code, but like I said a lot of it is outdated.

**Comment by jdorweiler** [comment]
Check out dictionary too.  It also uses audio. https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/dictionary/definition/dictionary_definition.js

**Comment by javathunderman** [comment]
@moollaza @jdorweiler No, can't do it. The JS is just a bit too complex for me.

**Comment by moollaza** [comment]
@javathunderman I suggest you at least give it a go! That way we can help you in the PR and you'll learn some stuff along the way.

The dictionary IA is indeed very advanced, but the Forvo IA, AFAIK shouldn't be much more different than a standard Spice that uses templates to produce  a tile view.

As mentioned the only different/important piece is that `Spice.add()` needs to specify the `view` and `model` are `'Audio'` and then in your `normalize` function you'll need to specify a few special properties that the `Audio` model expects:

```js
usingWaveformImage: usingWaveformImage,
duration: o.duration,
streamURL: streamURL
```

The code should look very similar to SoundCloud. All the crazy JS in the Forvo branch is now replaced with `view: 'Audio'` 

You can do it :+1:

**Comment by javathunderman** [comment]
Alright, you've convinced me. :+1: 

I'm currently working on the ISS location (#1559) and Melting/Boiling temperatures (submitting a PR shortly)

**Pull request closed without merging**
