### PR TITLE
New What3Words Geocoder Instant Answer

### PR DESCRIPTION
**Pull request by moollaza**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [x] New Instant Answer: **`New {IA Name} Instant Answer`**

###### Description of changes

Adds a Spice that uses the What3Words API for forward (three word) address geocoding and reverse (lat/lon coordinate) geocoding.

###### People to notify (@mention interested parties)

@duckduckgo/community-leaders care to review?

---

Instant Answer Page: https://duck.co/ia/view/what3words

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @moollaza

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=what3words force.tension.mows)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/what3words_mobile.png?Jas5isyeeL)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=what3words force.tension.mows)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/what3words_mobile.png?cKL73Tqx4o)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=what3words force.tension.mows)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/what3words_mobile.png?QgP5qxIBQd)

**Comment by tagawa** [comment]
Nice work @moollaza! Good to see a new map IA.

It works for some queries for me but not all, e.g. https://beta.duckduckgo.com/?q=what3words+homing.udder.zooms - these words work on the official website.

Also, initially I forgot the periods and kept searching for three space-separated words, until I remembered the dots. As the "what3words" trigger is required, perhaps it could work with space-separate words as well, and even comma-separated?

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=what3words force.tension.mows)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/what3words_mobile.png?jHZtBRu0gB)

**Comment by moollaza** [comment]
@tagawa I've made some changes that add support for https://beta.duckduckgo.com/?q=what3words+homing.udder.zooms&ia=map -- however, the ArcGIS API that provide the city/country info seems to time out for requests related to Japan (and other parts of East Asia)

For some reason those requests are taking up to 4 or 5 seconds to give a response....

**Comment by moollaza** [comment]
> Also, initially I forgot the periods and kept searching for three space-separated words, until I remembered the dots. As the "what3words" trigger is required, perhaps it could work with space-separate words as well, and even comma-separated?

I think the intention is that 3 word address are only meant to be search in the form of `word.word.word` -- enforcing that pattern narrows the query space which helps to ensure relevancy.

For now I think we should leave it as-is and relax the triggering if needed.

**Comment by moollaza** [comment]
> For some reason those requests are taking up to 4 or 5 seconds to give a response....

I just realized the timeouts were a result of me increasing the distance parameter. The API is spending more time to search for a defined address within a 100km radius which clearly takes several seconds. I've reduced this down to 5000m which returns results much quicker.

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=what3words force.tension.mows)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/what3words_mobile.png?jLfxXYP0k5)

**Comment by moollaza** [comment]
Everything should be addressed now. 👍

**Comment by daxtheduck** [comment]
@moollaza this is now merged! It should be live on DuckDuckGo within one week (or during the next release) and we'll be sure to notify you when it happens.

After your Instant Answer goes live for the World to use, you will be able to see [traffic information](http://docs.duckduckhack.com/maintaining/tools.html#monitor-your-instant-answer-page) about your IA as well as receive feedback directly from users. 
                
Please refer to the [maintenance guide and docs](http://docs.duckduckhack.com/maintaining/guidelines.html) to keep up with potential changes to your Instant Answer.
                
Thank you again for your help!

**Pull request merged**
