### PR TITLE
npm: Enhanced UI/UX

### LINKED ISSUE #3266: npm: Improve detail view UX
## Problem

In #3257 we added the single detail view back to improve engagement. But we need to make some changes to improve the UX.

screen_shot_2017-04-25_at_9_37_48_pm

## Solution

1. Add the description from the api call 
2. Remove the separator beside the _More at_ link
3. Send a PR

## People to notify

@duckduckgo/duckduckhack-contributors 

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/npm

### PR DESCRIPTION
**Pull request by mayank**
## Description of new Instant Answer, or changes
Enhanced the UI for npm spice as described #3266 

image

## Related Issues and Discussions
Fixes #3266 

## People to notify
@pjhampton 

---

Instant Answer Page: https://duck.co/ia/view/npm

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by pjhampton** [comment]
Restarting failed build 👍

**Comment by pjhampton** [comment]
Nice @mayank 🚀

**Comment by mayank** [comment]
@pjhampton thanks

**Comment by bsstoner** [comment]
This was released to production :rocket:

**Pull request merged**
