### PR TITLE
Refine couprex trigger words

### PR DESCRIPTION
**Pull request by b2ddg**
Refining the triggering conditions for couprex due to interference from unrelated queries.

/cc @AdamSC1-ddg 

---
IA Page: https://duck.co/ia/view/couprex

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by AdamSC1-ddg** [comment]
Hey @b2ddg - good catches on these, @moollaza had been talking about how to refine the trigger space. Since most of the listings on the site right now are discounts and deals (only about 30-40% are coupons). 

Instead of removing the words is there common trends we could de-limit with? Such as "how to" "with" etc so that we would trigger on "shoe deals" but not "how to deal with people" etc?

**Comment by b2ddg** [comment]
Hey @AdamSC1-ddg! 
It's not totally clear how to separate the query space here. For the words 'deal' and 'discount', we can probably trigger on those if they're at the beginning or end of the query only, but that doesn't seem appropriate for the other words, like coupon which should clearly trigger this IA when it's present anywhere in the query.

**Comment by b2ddg** [comment]
@moollaza Let's move forward with this and handle some of overtriggering internally.

**Comment by moollaza** [comment]
@b2ddg Thanks! This LGTM :+1:

**Pull request merged**
