### PR TITLE
[Indeed.com jobs spice plugin] based on GithubJobs.pm plugin

### PR DESCRIPTION
**Pull request by parker**
**What does your instant answer do?**
Provides job search via Indeed.com API
https://dukgo.com/ideas/idea/767/indeed-com-jobs-spice-plugin

**What problem does your instant answer solve (Why is it better than organic links)?**
Organic links do not contain individual job postings.

**What is the data source for your instant answer? (Provide a link if possible)**
Indeed.com - http://www.indeed.com
https://ads.indeed.com/jobroll/xmlfeed

**Why did you choose this data source?**
Indeed is the number 1 Job Search site in the US
http://blog.indeed.com/2013/02/14/independent-study-indeed-1-external-source-of-hire/

**Are there any other alternative (better) data sources?**
Alternatives:
- GitHub Jobs
- [Stackoverflow Careers Api](http://meta.stackoverflow.com/questions/158005/stackoverflow-careers-api)
- [LinkedIn Jobs Api](https://developer.linkedin.com/apis)
- [SimplyHired Api](http://www.simplyhired.com/a/publishers/overview)

**What are some example queries that trigger this instant answer?**
perl jobs in Austin, TX
jobs in Austin, TX
jobs
perl jobs
I want java job in Austin

**Which communities will this instant answer be especially useful for? (gamers, book lovers, etc)**
Users looking for a job

**Is this instant answer connected to an [Ideas.DuckDuckHack](https://duckduckhack.uservoice.com/forums/5168-ideas-for-duckduckgo-instant-answer-plugins) or [Duck.co](http://duck.co/) thread?**
https://dukgo.com/ideas/idea/758/jobs-search-via-indeed-com

**Which existing instant answers will this one supersede/overlap with?**
GithubJobs.pm
The current implementation uses the same triggers and regular expression from GithubJobs.pm

The GitHub Jobs api could be modified to only look for programming specific jobs using keywords like "perl, java, javascript, C#, programming, etc".

**Are you having any problems? Do you need our help with anything?**

I could not figure out why GitHub Jobs superseded the IndeedJobs instant answer when both triggered results.

**Required environment variable**
- _DDG_SPICE_INDEED_JOBS_PUBLISHER_ - should contain the publisher number for Indeed's Api. You can register via https://ads.indeed.com/jobroll/xmlfeed
## Checklist

Please place a ✔ where appropriate.

```
[✔] Added metadata and attribution information
[✔] Wrote test file and added to t/ directory
[✔] Verified that instant answer adheres to design guidelines(https://github.com/duckduckgo/duckduckgo-documentation/blob/master/duckduckhack/styleguides/design_styleguide.md)
[] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        [] Google Chrome   
        [] Firefox         
        [] Opera           
        [] IE 10           

    - Windows 7
        [] Google Chrome   
        [] Firefox         
        [] Opera           
        [] IE 8            
        [] IE 9            
        [] IE 10           

    - Windows XP
        [] IE 7            
        [] IE 8            

    - Mac OSX
        [✔] Google Chrome   
        [✔] Firefox         
        [] Opera           
        [✔] Safari          

    - iOS (iPhone)
        [] Safari Mobile   
        [] Google Chrome   
        [] Opera           

    - iOS (iPad)
        [] Safari Mobile   
        [] Google Chrome   
        [] Opera            

    - Android
        [] Firefox         
        [] Native Browser  
        [] Google Chrome   
        [] Opera
```

### CODE REVIEW

**Comment by javathunderman** [comment]
Saw this on Duck.co, and my understanding is that indeed.com only has an XML (not JSON) API. Is this true?

cc @moollaza @jagtalon

**Comment by zekiel** [comment]
@javathunderman  i can't recall but we're looking into it

**Comment by javathunderman** [comment]
@zekiel If you find another source or if they support JSON, we should have this revived.

**Comment by janschreur** [comment]
The Indeed API does support JSON: simply append "&format=json" to the end of your request.

**Comment by moollaza** [comment]
Thanks @janschreur! @javathunderman looks like we already have that in our `spice to` call :)

**Comment by zekiel** [comment]
very nice @janschreur  thanks!

**Comment by javathunderman** [comment]
@moollaza Since this is live I think the "Abandoned" label can be removed.

**Comment by moollaza** [comment]
@javathunderman  :+1:

**Pull request closed without merging**
