### PR TITLE
Timer: added new test for 'time'

### PR DESCRIPTION
**Pull request by mattr555**
Added a new test that @jagtalon wanted for the new trigger in #1446. Also felt that we reached the tipping point for repeat test arguments :neckbeard: 

*edit:* hold up, I'll get #1466 too.

### CODE REVIEW

**Comment by moollaza** [comment]
@mattr555 looking good! Feel free to ping us when ready :+1:

**Comment by mattr555** [comment]
@moollaza Done! Had a rogue `?`

For the github auto-trigger: fixes #1466

**Comment by mattr555** [comment]
@moollaza Ok, _now_ it's actually done. I found that the regex guard was a little too loose, triggering on words that just started with h, m, or s (e.g. `timer 5 hellos`). I added anchors; it should be good to go now.

**Comment by moollaza** [comment]
@mattr555 thanks a lot, this looks pretty good. I noticed one bug though, it doesn't seem to trigger any more for queries that have decimals in them (e.g. "timer 3.5 minutes") -- likely related to the regex update?

**Comment by moollaza** [comment]
FTR it looks like we need to be rounding up the decimal minute/seconds calculation to the nearest second -- can fix later though, not a big deal

**Comment by jagtalon** [comment]
@mattr555 sweet! :+1:

**Comment by jagtalon** [comment]
@mattr555 the "timer 3.5 minutes" thing should probably be in the test too!

**Comment by mattr555** [comment]
@jagtalon @moollaza Should be good now!

**Comment by jagtalon** [comment]
@mattr555 thanks! :+1:

**Pull request merged**
