### PR TITLE
Holiday: False trigger on "California Primary"

### LINKED ISSUE #2651: Holiday: False trigger
This IA shouldn't be triggered on the following query:
[when is california primary 2016](https://duckduckgo.com/?q=when+is+california+primary+2016&ia=answer)

As [reported on Twitter](https://twitter.com/xarph/status/717064457227112448).

------
IA Page:  http://duck.co/ia/view/holiday 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @sekhavati

### PR DESCRIPTION
**Pull request by sekhavati**
Fixes #2651. This is a crude fix that simply addresses the issue mentioned. Any query with the word "primary" no longer triggers this IA, so this should cover other `<state> primary` searches too.

---
IA Page: http://duck.co/ia/view/holiday

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by jdorweiler** [comment]
@sekhavati could you add a test please.

**Comment by sekhavati** [comment]
@jdorweiler Tests added

**Comment by jdorweiler** [comment]
:+1:  looks good.  Thanks @sekhavati

**Pull request merged**
