### PR TITLE
Make dist.ini more robust and useful

### PR DESCRIPTION
**Pull request by pfirsichbluete**
* Made dist's main_module explicit,
* Fixed several dzil warnings, and
* Add more static linting.

### CODE REVIEW

**Comment by jagtalon** [comment]
@pfirsichbluete looks like there are merge conflicts. Please pull in master. :)

**Comment by pfirsichbluete** [comment]
> @pfirsichbluete looks like there are merge conflicts. Please pull in master. :)

Thanks. Resolved by updating the Pull-Request to current master

**Comment by moollaza** [comment]
@pfirsichbluete thanks a lot for this!

I just spoke with the team and we think we should leave out `Test::Tabs` for now.

Having a distinct styleguide and the enforcing it is still something we're discussing internally and haven't made any decisions on just yet. We'll be making some changes to our dist.ini very shortly and we're trying to minimize the complexity of our dist.ini and build times.

Personally, I like the idea of moving towards a separate tool like Codacy or HoundCI for catching minor style bugs and warning devs. I think it makes it more apparent when there's a comment on a specific line from Hound that tells the developer what needs to be fixed.

**Comment by pfirsichbluete** [comment]
> I just spoke with the team and we think we should leave out `Test::Tabs` for now.

@moollaza Cool beans. I updated the Pull-Request and it now comes without the `Test::NoTabs` commit.

(But I nonetheless kept the commit that converts existing code from tabs to spaces as the [current style guide](https://duck.co/duckduckhack/code_styleguide) requires to “Indent with 4 spaces”.)

**Comment by moollaza** [comment]
>I updated the Pull-Request and it now comes without the Test::NoTabs commit.

Thanks

>(But I nonetheless kept the commit that converts existing code from tabs to spaces as the current style guide requires to “Indent with 4 spaces”.)

Perfect!

**Comment by moollaza** [comment]
LGTM :+1:

**Pull request merged**
