### PR TITLE
Currency: trigger by symbol suffix

### PR DESCRIPTION
**Pull request by kbhat95**
This is in reference to #1930.

It seems fine going by the output I get in stdout. The actual result wasn't displaying on my test server (perhaps because I was using ```https://duckduckgo.com/js/spice/currency/$1/$2/$2``` instead of the original call?).

@MrChrisW Please let me know how this looks. Thanks! :)

### CODE REVIEW

**Comment by MrChrisW** [comment]
@kbhat95 Thanks for this! We'll review this shortly. :+1:

**Comment by moollaza** [comment]
@kbhat95 please add some additional tests to ensure that it works properly :+1:

**Comment by kbhat95** [comment]
@moollaza tests pushed!

I have **got** to start remembering the tests. Sorry!

**Comment by moollaza** [comment]
LGTM :+1:

**Pull request merged**
