### PR TITLE
Namecheap: Final adjustments

### PR DESCRIPTION
**Pull request by moollaza**
- remove subtitle
- change tab to `Domain`
- hardcode `clientip` param (API is set to ignore it for us)

/cc @abeyang @jagtalon 

Will update DDH8 in a sec...

### CODE REVIEW

**Comment by jagtalon** [comment]
LGTM

**Comment by moollaza** [comment]
https://ddh8.duckduckgo.com/?q=namecheap+checkthisoutguys.com&ia=domain

**Comment by tejasmanohar** [comment]
LGTMT (..., too)!

**Comment by abeyang** [comment]
:+1:

**Comment by moollaza** [comment]
@jagtalon @abeyang -- made one more small update. Removed the bolding because we tend to avoid that and replaced it with a clickable link:
2015-03-04_17h16_46

**Comment by tejasmanohar** [comment]
@moollaza Would you tweak one thing in this PR for the template?

>The domain 'checkthisoutguys.com' is available! Register this domain at Namecheap.
maybe make that whole thing a link: "register this domain at namecheap "

+

>The domain iliketurtles.net is not available. Make an offer to the owner at DomainAgents [link]

instead of the current text. Pretty simple fix in handlebars. This is the one Teddy from Namecheap preferred. If you'd prefer me sending in the fix, I can do it after this PR is merged :+1:

**Comment by moollaza** [comment]
@tejasmanohar great suggestion. I've pushed an updated.

**Comment by moollaza** [comment]
https://ddh8.duckduckgo.com/?q=namecheap+yolo.org&ia=domain

**Comment by abeyang** [comment]
:+1:

**Comment by jagtalon** [comment]
Nice! thanks for removing the bolding.

**Pull request merged**
