### PR TITLE
Finish support for Holiday IA

### PR DESCRIPTION
**Pull request by marcantonio**
90% of the work was done here:  https://github.com/duckduckgo/zeroclickinfo-spice/pull/1701.

screen shot 2016-01-31 at 8 54 59 pm

IA page: https://duck.co/ia/view/holiday

### CODE REVIEW

**Comment by daxtheduck** [comment]
@marcantonio Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

While the team and the community review your submission, we'd like to make sure you look good! If you'd like a free DuckDuckGo tshirt, please send over the following info to merch@duckduckgo.com, and be sure to put "Dev Merch" in the subject line:

Name:
Street Address:
City:
State / Province:
Country:
Phone (Non-US Orders only): 
T-shirt size:
GitHub username:
Link to this Pull Request:

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by marcantonio** [comment]
Also, I noticed this weird visual anomaly:

screen shot 2016-01-30 at 9 28 52 pm

**Comment by marcantonio** [comment]
Another issue:  searching for `when was` and the holiday hasn't happened yet this year returns a future event.

screen shot 2016-01-30 at 9 41 39 pm

**Comment by moollaza** [comment]
> Also, I noticed this weird visual anomaly:

@marcantonio yup that’s a known issue. Its due to the way we're loading & concatenating the CSS. I've filed an issue in the DuckPAN repo: https://github.com/duckduckgo/p5-app-duckpan/issues/310

> searching for when was and the holiday hasn't happened yet this year returns a future event.

hmm we have some logic that searches for the holiday in the current year, and uses that date. The problem is that we don't know if a holiday has occurred until we get the first API response back, and if it has but was in the previous year, we'd need to make a 2nd API call.

I guess ideally the API should give us the previous and next occurrence so we can figure out what to show based on the query.

**Comment by marcantonio** [comment]
> hmm we have some logic that searches for the holiday in the current year, and uses that date. The problem is that we don't know if a holiday has occurred until we get the first API response back, and if it has but was in the previous year, we'd need to make a 2nd API call.

> I guess ideally the API should give us the previous and next occurrence so we can figure out what to show based on the query.

Yeah I saw.  You're right, the best way would be if the API multiple dates or if we could specify multiple years in the query.  In leu of that, do spices ever make more than 1 API call?  We could either make 2 right off the bat (one for the current year and one for last year) or make a second call after the first one returns the wrong date.  Is there precedence for this?

**Comment by moollaza** [comment]
> We could either make 2 right off the bat (one for the current year and one for last year) or make a second call after the first one returns the wrong date. Is there precedence for this?

That's certainly possible. This IA actually already does that when we get no results for the user's country: 

https://github.com/duckduckgo/zeroclickinfo-spice/pull/2455/files#diff-b6a9a492539f7580c055121fa2c66c9dR46

We form a new query and hit the NGINX endpoint again

**Comment by marcantonio** [comment]
Ah, I missed that.  I don't think that code will every actually be hit though, because of L4.  I could be wrong, haven't done any JS in a while.  It seems that L45-49 should be checked in the if block at L4.

**Comment by marcantonio** [comment]
US fallback works now.  Query was missing from the second call too.

**Comment by marcantonio** [comment]
is/was now works for all cases.  Needs more thorough testing.

**Comment by marcantonio** [comment]
@moollaza, I think this is ready for testing.

**Comment by jagtalon** [comment]
Yus! I'm excited for this

**Pull request merged**
