### PR TITLE
ISBN: Ignore phone numbers, update tests accordingly

### PR DESCRIPTION
**Pull request by moollaza**
## Description of new Instant Answer, or changes
- Updated logic to ignore queries that match a phone number lookup
- Added appropriate tests

---

Instant Answer Page: https://duck.co/ia/view/isbn

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
Deploying to Beta 👍

**Comment by pjhampton** [comment]
This seems fine. This seems to be triggering on ISBN-13 only, and not ISBN-10. Is this expected behaviour @moollaza?

screen shot 2017-04-27 at 4 22 32 pm
screen shot 2017-04-27 at 4 22 25 pm

**Comment by moollaza** [comment]
@pjhampton it's triggering there, but that API (our internal Amazon API) just isn't returning a result

**Comment by pjhampton** [comment]
Right, I see 👍

**Comment by bsstoner** [comment]
This was released to production 🚀

**Pull request merged**
