### PR TITLE
Fixes #2961 by removing partial matches

### LINKED ISSUE #2961: Just Delete Me: wrong account info displayed
When I search for "delete icloud account," I'm shown instructions on deleting a JoliCloud / JoiliDrive account.

https://duckduckgo.com/?q=delete+icloud+account&t=ffab&ia=answer

---

IA Page:  http://duck.co/ia/view/just_delete_me 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @riqpe

### PR DESCRIPTION
**Pull request by riqpe**
- [x] Improvement
  - [x] Bug fix: **`JustDeleteMe: Fix  #2961`**
###### Description of changes

IA will no longer display partial matches
Fixes also display of exact name matches which was broken before but unnoticed.
###### Related Issues or Discussions

 #2961
###### People to notify

@moollaza @tagawa @mrshu @edgesince84 

---

Instant Answer Page: https://duck.co/ia/view/just_delete_me

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @riqpe

### CODE REVIEW

**Comment by daxtheduck** [comment]
@riqpe Thanks for the pull request! Unfortunately, we're only accepting contributions and improvements to a limited portion of the search space.
            
The staff and community are currently focused on making DuckDuckGo the [best search engine for programmers](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53). To ensure we're making as much progress as possible, **we are only accepting Instant Answers and updates related to the programming mission**.
    
If this is not related to the Programming Mission, it will likely be closed but you can:
    
1. Help us prevent further confusion by telling us where you found out about DuckDuckHack or where we could've alerted you earlier.
2. Keep this code handy! We'll be expanding into other search topics in the future!
3. Join us at our new home: https://forum.duckduckhack.com/

If this is related to the Programming Mission, it will be reviewed by staff and the community as soon as possible!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@riqpe sorry for the delay, thanks for this update. Deploying to Beta 👍

**Comment by bsstoner** [comment]
This should be in production now 🚀

**Pull request merged**
