### PR TITLE
Bug fix: Emojipedia: Fix #3018

### LINKED ISSUE #3018: Emojipedia: Looking up flags shows info about a regional indicator
Example: searching for the European flag 🇪🇺gives following page

https://duckduckgo.com/?q=%F0%9F%87%AA%F0%9F%87%BA&ia=answer

The zero click answer refers to [Regional Indicator Symbol Let­ter U](http://emojipedia.org/regional-indicator-symbol-letter-u/) instead of [Flag for European Union](http://emojipedia.org/flag-for-european-union/)

------
IA Page:  http://duck.co/ia/view/emojipedia 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mathewbyrne

### PR DESCRIPTION
**Pull request by Boldewyn**
###### Description of changes

The regular expression, that detects emojis, is enhanced to match better. Especially fringe cases like matching only single country-code identifiers from a sequence are addressed. Two new test cases are added.

###### Related Issues or Discussions 

Fixes #3018.

###### People to notify

Nobody in particular.

---

Instant Answer Page: https://duck.co/ia/view/emojipedia

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): me

### CODE REVIEW

**Comment by daxtheduck** [comment]
@Boldewyn Thanks for the pull request! Unfortunately, we're only accepting contributions and improvements to a limited portion of the search space.
            
The staff and community are currently focused on making DuckDuckGo the [best search engine for programmers](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53). To ensure we're making as much progress as possible, **we are only accepting Instant Answers and updates related to the programming mission**.
    
If this is not related to the Programming Mission, it will likely be closed but you can:
    
1. Help us prevent further confusion by telling us where you found out about DuckDuckHack or where we could've alerted you earlier.
2. Keep this code handy! We'll be expanding into other search topics in the future!
3. Join us at our new home: https://forum.duckduckhack.com/

If this is related to the Programming Mission, it will be reviewed by staff and the community as soon as possible!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@Boldewyn Thanks! This LGTM :+1:

**Comment by moollaza** [comment]
This is live on beta: https://beta.duckduckgo.com/?q=🇪🇺&ia=answer

**Pull request merged**
