### PR TITLE
NPM: Add TonicDev link

### PR DESCRIPTION
**Pull request by sahildua2305**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer: **`New {IA Name} Instant Answer`**
- [x] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [x] Enhancement: **`NPM: Add TonicDev link`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{SpiceRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes
Added TonicDev link in IA results alongside `More at` text.

###### People to notify (@mention interested parties)
@moollaza @MariagraziaAlastra 

---

Instant Answer Page: https://duck.co/ia/view/npm

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @remixz

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by MariagraziaAlastra** [comment]
Thanks @sahildua2305, this LGTM! 👍

**Comment by sahildua2305** [comment]
@MariagraziaAlastra Thanks :smile:

**Comment by sahildua2305** [comment]
Good find @moollaza!

Looks like on their own website as well, they are still using tonicdev links and just redirecting to runkit. We can do better 😄

**Pull request merged**
