### PR TITLE
ColoPicker update

### PR DESCRIPTION
**Pull request by moollaza**
/cc @mattr555 @chrismorast 

Small refinement to color harmony selections.

Will deploy to a dev machine soon!

### CODE REVIEW

**Comment by moollaza** [comment]
https://moollaza.duckduckgo.com/?q=color+picker&ia=colorpicker

**Comment by moollaza** [comment]
Merging with Chris' blessing :+1:

**Comment by mattr555** [comment]
👍

**Comment by jagtalon** [comment]
:+1:

**Pull request merged**
