### PR TITLE
Removed conflicting `Elixir` start trigger. Added more triggers.

### PR DESCRIPTION
**Pull request by pjhampton**
###### What does your Pull Request do (check all that apply)?

- [ ] New Instant Answer: **`New {IA Name} Instant Answer`**
- [x] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [x] Enhancement: **`{Hex Packages}: {removed elixir trigger}`**
- [ ] Non–Instant Answer
    - [ ] Other (Role, Template, Test, Documentation, etc.): **`{SpiceRole/Templates/Tests/Docs}: {Short Description}`**

###### Description of changes

Removed `elixir` startend trigger. This is going to cause an immediate problem with the elixir fathead with is coming to a conclusion. As this is more to do with hex and _not_ the elixir programming language, I have removed the trigger.

---

Instant Answer Page: https://duck.co/ia/view/hex

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @milmazz

### CODE REVIEW

**Comment by daxtheduck** [comment]
@pjhampton Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by zekiel** [comment]
@milmazz any final thoughts? We'd like to merge this as it's past the [approval time period](http://docs.duckduckhack.com/maintaining/guidelines.html#for-maintainers).

**Comment by milmazz** [comment]
Wow!, I haven't seen this PR before, sorry guys. LGTM BTW :+1:

**Pull request merged**
