### PR TITLE
Pokemon data - added more relevant MoreAt section

### LINKED ISSUE #1969: Pokedex - need better "more at" url
Right now the "more at pokeapi.co" links pokeapi.co, without any permanent url for the specific pokemon. That page just shows how to call the api. It's kind of useless. We could probably link it to bulbapedia.

Also, the name of the pokemon being searched is linked to that search page itself. E.g. searching for Machop hyperlinks the name Machop to https://duckduckgo.com/?q=pokemon+machop&t=canonical&ia=pokedex&iax=1. We could avoid doing that. It's no help at all. Linking the pokemon they evolve to, to the duckduckgo search page is fine.

/cc @AkA84

### PR DESCRIPTION
**Pull request by iambibhas**
Fixes #1969.

This is how it looks now - 

selection_058

### CODE REVIEW

**Comment by moollaza** [comment]
@iambibhas I'm not sure about the duplicate "more at" text. I think we should remove that for the 2nd link. Or ditch the 2nd link altogether.

/cc @abeyang

**Comment by iambibhas** [comment]
@moollaza @abeyang can we keep it? I'll remove the "More At" from there.

**Comment by abeyang** [comment]
Are we talking about pokemon.com? Do we need it?

**Comment by moollaza** [comment]
> Are we talking about pokemon.com?

Yup

> Do we need it?

Not exactly, but it's a useful additional place to send the user. However, this isn't something we've done before. I think without the additional "more at" text this is acceptable.

**Comment by iambibhas** [comment]
@moollaza I do think it'll be helpful to the user. I've removed the "more at" text and updated the screenshot above.

**Comment by abeyang** [comment]
I'm ok with it. Sorry, not familiar with Pokemon at all -- used to make fun of my brothers for watching it. :smile:

**Comment by moollaza** [comment]
LGTM :+1: 

Thanks again @iambibhas

**Pull request merged**
