### PR TITLE
Similar Sites Design Improvement

### PR DESCRIPTION
**Pull request by jagtalon**
Went with @chrismorast with a couple of design fixes. Was wondering if you could make a final review @moollaza?

- Better + and - button
- Font size change

### CODE REVIEW

**Comment by jagtalon** [comment]
@moollaza added your comments to https://github.com/duckduckgo/zeroclickinfo-spice/commit/c5b00b404403aba79cb66222d62b197c4187518f and https://github.com/duckduckgo/zeroclickinfo-spice/commit/7f8e2f827b4774895009fcbd551a43bc23c71eaa

**Comment by Adman** [comment]
@jagtalon Should I write tests for this?

**Comment by jagtalon** [comment]
@Adman for https://github.com/duckduckgo/zeroclickinfo-spice/commit/c5b00b404403aba79cb66222d62b197c4187518f? That would be great :)

**Comment by Adman** [comment]
@jagtalon For whole similarsites plugin

**Comment by moollaza** [comment]
@Adman yes, tests are required -- I should have noticed they were missing.

**Comment by jagtalon** [comment]
Yeah I missed that too. Thanks @Adman

**Pull request merged**
