### PR TITLE
Currency: add leu/lei aliases for RON

### PR DESCRIPTION
**Pull request by WickedA**
###### Description of changes

This PR adds the "leu" and "lei" aliases for RON to `share/spice/currency/currencyNames.txt`.

_Leu_ and _lei_ are the singular and plural words we use to refer to our currency in day-to-day life, and I see no reason why DuckDuckGo shouldn't recognise them. Google [already does this correctly](https://encrypted.google.com/search?hl=en&q=100%20lei%20to%20usd).

---

Instant Answer Page: https://duck.co/ia/view/currency

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

### CODE REVIEW

**Comment by daxtheduck** [comment]
@WickedA Thanks for the pull request! Unfortunately, we're only accepting contributions and improvements to a limited portion of the search space.
            
The staff and community are currently focused on making DuckDuckGo the [best search engine for programmers](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53). To ensure we're making as much progress as possible, **we are only accepting Instant Answers and updates related to the programming mission**.
    
If this is not related to the Programming Mission, it will likely be closed but you can:
    
1. Help us prevent further confusion by telling us where you found out about DuckDuckHack or where we could've alerted you earlier.
2. Keep this code handy! We'll be expanding into other search topics in the future!
3. Join us at our new home: https://forum.duckduckhack.com/

If this is related to the Programming Mission, it will be reviewed by staff and the community as soon as possible!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@WickedA sorry for the late very reply, and thanks a lot for this update! Can you please add a couple tests to t/Curency.t to prove this works. After that I'd be happy to merge 👍

**Comment by WickedA** [comment]
Whoops, looks like I wiped that commit out while trying to rebase.

**Comment by moollaza** [comment]
@WickedA Thanks! This LGTM :+1:

**Comment by bsstoner** [comment]
This was released to production 🚀

**Pull request merged**
