### PR TITLE
Changed congress template to media

### LINKED ISSUE #836: Congress: Switch to "media" group
Currently it uses the "products" template which is a bit of overkill, it makes more sense to use the "media" template group.

https://duck.co/ia/view/congress

### PR DESCRIPTION
**Pull request by gokul1794**
This currently looks like this, What do you think we should do about the names?
This will fix #836 
congress

### CODE REVIEW

**Comment by moollaza** [comment]
@abeyang thoughts on how this IA should look?

I hadn't noticed that it's looking pretty rought right now: https://duckduckgo.com/?q=california+senators&t=ffab&ia=congress&iai=0

**Comment by abeyang** [comment]
@moollaza let's make this one more akin to G+ (#1934) and People in Space (#1296).

**Comment by gokul1794** [comment]
Desktop
congress_desktop
Mobile
mobcongress

**Comment by moollaza** [comment]
@gokul1794 it looks like the images are being squished? Please make sure that they maintain the proportions. I believe you'll just want to specify `max-width: 100%`. So that the image doesn't get squished and sizes itself accordingly.

**Comment by abeyang** [comment]
@gokul1794 Ditto with what @moollaza said. Also, can we have the titles look/mimic those in G+/People in Space? Ie, they can expand to two lines.

**Comment by gokul1794** [comment]
@moollaza, made `max-width: 100%`,
@abeyang Title expans to two lines
width-100

**Comment by abeyang** [comment]
@gokul1794 But the avatar still needs to be circular... might be helpful to look into the G+ / People in Space code, to get started. Also need more padding below the title. Thanks!

**Comment by gokul1794** [comment]
@abeyang Is this all right?
senator

**Comment by gokul1794** [comment]
Also, @moollaza what do you think?

**Comment by moollaza** [comment]
@gokul1794 the tiles look great.

We'll need to disable the detail and item_detail panes so that the tiles when clicked follow through to `url` specified.

**Comment by gokul1794** [comment]
@moollaza Done :+1:

**Comment by jagtalon** [comment]
@gokul1794 nice! @abeyang let me set this up for you on a server.

**Comment by moollaza** [comment]
Hey guys, @abeyang is away this week so I think we're good to merge this. The design is now in line with our similar IA's and it's 10x better than the currently live IA.

**Comment by gokul1794** [comment]
Yay :boom: :tada: :stuck_out_tongue_winking_eye:

**Comment by jagtalon** [comment]
:+1:

**Pull request merged**
