### PR TITLE
New geometry formula shower / calculator Spice

### PR DESCRIPTION
**Pull request by pixunil**
This is a converted Goodie, the old PR was duckduckgo/zeroclickinfo-goodies#464

**What does your instant answer do?**
This spice shows geometric formulas (e.g. circle area) with a mockup or calculates them if sizes are specified.

**What are some example queries that trigger this instant answer?**
- formula circle perimeter
- calc circle area with radius = 3
- geometry cube volume length 50.6
- calc equilateral triangle perimeter
- formula ball volume
- geometry rectangle area a = 5,2, b = 10
- geometry cuboid volume a: 5; b: 3; c: 4

**Is this instant answer connected to a DuckDuckHack [instant answer idea](https://duck.co/ideas)?**
Yes, https://duck.co/ideas/idea/1053/geometry-calculator.

**Which existing instant answers will this one supercede/overlap with?**
Not known yet

**Are you having any problems? Do you need our help with anything?**
Only improvement questions:
 - The data is static in [geometry.js, line 68 to 365](https://github.com/pixunil/zeroclickinfo-spice/blob/geometry/share/spice/geometry/geometry.js#L68-365), maybe perl could fetch the shape wanted in a separate js file

- it would be great to get the hover color defined by the user in settings

**Checklist:**

- [x] Added metadata and attribution information
- [x] Wrote test file and added to t/ directory
- [x] Verified that instant answer adheres to design guidelines(https://github.com/duckduckgo/duckduckgo-documentation/blob/master/duckduckhack/styleguides/design_styleguide.md)
- [x] Tested cross-browser compatability *with support tables*

 Browser | supported versions | unsupported feature for older versions
 ----|-----|----
 IE | 10+ | classList
 Firefox | 8+ | classList
 Chrome | 8+ | classList
 Safari | 5.1+ | classList
 Opera | 11.5+ | classList
- [x] Tested live only on Linux (Mint) 64-bit, Firefox 33

### CODE REVIEW

**Comment by abeyang** [comment]
Hi @pixunil, just checking in. How goes it?

**Comment by jagtalon** [comment]
@abeyang I think this looks good. I'll send you the server link for a final review

**Comment by jagtalon** [comment]
https://ddh1.duckduckgo.com/?q=geometry+circle&ia=geometry it looks good to me! @mattr555 @MrChrisW any comments would be appreciated too. :)

**Comment by jagtalon** [comment]
Oh my bad--I thought it was already updated to https://github.com/duckduckgo/zeroclickinfo-spice/pull/1206#issuecomment-63888927.

**Comment by abeyang** [comment]
No problem, @jagtalon. 

@pixunil let us know if you need help with this!

**Comment by pixunil** [comment]
I just have little design problems, and I want to ask @abeyang if there is working CSS for it. Thanks.

**Comment by abeyang** [comment]
@pixunil what kind of design problems?

**Comment by jagtalon** [comment]
@pixunil you can upload your code and we can take a look at it. :)

**Comment by moollaza** [comment]
ping!

>and I want to ask @abeyang if there is working CSS for it. Thanks.

We don't have any CSS for this.  @pixunil I take it you need some help?

**Comment by pixunil** [comment]
Some new screenshots:





The colors can be discussed; I picked it like I liked…
The border over the roots could also be slightly improved, I tried some things, but they doesn't helped.

Sorry for being a bit late with this.

**Comment by jagtalon** [comment]
yup

I am excited to test this out!

**Comment by jagtalon** [comment]
@pixunil Some positioning problems with IE and iPhone 5:

screen shot 2015-02-19 at 12 21 16 pm
screen shot 2015-02-19 at 12 22 43 pm

**Comment by jagtalon** [comment]
@abeyang what do you think about the design? https://ddh9.duckduckgo.com/?q=geometry+cube&ia=geometry

Will check the code on my end.

**Comment by abeyang** [comment]
@pixunil It's shaping up quite nicely (no pun intended)! Still need a few tweaks, but I feel like we're almost there!

First, the colors:
- area: #f1a031
- perimeter: #5b9e4d
- diagonal: #4495d4

Second, let's get rid of the .root class -- I know what you're trying to do, but it just looks funny how there's a break between the √ and the top-border. So, for cube, let's do a√3 and for perimeter, we'll include parentheses -- √(...)

Finally, please apply these css changes:

```css
#zci--geometry-formulas .formula {
  margin-bottom: 5px;
}

#zci--geometry-formulas .dot {
  margin: 20px 10px 0 0;
  opacity: 0.5;
}

#zci--geometry-formulas h4 {
  color: #999;
  padding-bottom: 0;
  margin-bottom: -3px;
}

#zci--geometry-formulas sup {
  font-size: 0.6em
}

#zci--geometry-svg {
  margin-left: 50px;
}
```

It should look something like this (with the exception of the colors) in the end:
screen shot 2015-02-19 at 10 14 07 am

Thanks again -- let us know if you need any help!

**Comment by abeyang** [comment]
^ Oh, one last thing -- let's keep the height of the svg to max of **150px**. Let's try that and see how that looks...

**Comment by pixunil** [comment]
Do you also have a color for volume?

**Comment by abeyang** [comment]
Can we use the same color as area? I don't think they'll show up at the same time, right?

**Comment by pixunil** [comment]
I picked `#F1A031` for surface, and surface will show together with volume (currently `#FF6745`):

**Comment by abeyang** [comment]
I see -- because surface *is* area ("surface area." Duh. Sorry, been a while since I've done this.)

Ok, let's go with red, but can we try on the DDG red? `#DE5833`

**Comment by moollaza** [comment]
@pixunil @jagtalon yes the mobile view looks a little odd. A small fix to the CSS makes it look much better:

```css
#zci--geometry-svg {
    // removed float: left -- not needed
    fill: transparent;
    max-height: 150px;
    max-width: 50%;
}
```

2015-02-19_21h22_58

I also increased the space between the image and the formulas to about 40px or so

**Comment by jagtalon** [comment]
@pixunil @moollaza that works on a few cases but fails on iPhone 5 and 4 sizes:

screen shot 2015-02-20 at 1 10 43 pm

screen shot 2015-02-20 at 12 52 30 pm

Adjusting the width or the padding of zci--geometry-formulas should get it done.

**Comment by pixunil** [comment]
I would prefer to hide the dot when the screen is too small, as the hover effect would be useless on mobile devices and so the color.
Do you know the trigger value for the "mobile" style?

**Comment by moollaza** [comment]
>I would prefer to hide the dot when the screen is too small, as the hover effect would be useless on mobile devices and so the color.

@pixunil I believe we need the dot so the user can associate the displayed colour with what is shown in the diagram?

> Do you know the trigger value for the "mobile" style?

Not quite sure what you mean by "trigger" -- can you please clarify?

**Comment by jagtalon** [comment]
@pixunil maybe we can just make the svg a little smaller so that it fits on those sizes?

**Comment by jagtalon** [comment]
@pixunil Are you wondering how to detect mobile devices? We have the global variable `is_mobile` for that (but usually we just specify `detail_mobile` if you want to change the template on mobile devices: https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/forecast/forecast.js#L283

screen shot 2015-03-23 at 12 02 52 pm
screen shot 2015-03-23 at 12 03 06 pm

**Comment by moollaza** [comment]
@pixunil we had a talk and decided that the mobile layout isn't extremely important for now, because we'd love to get this live!

I'll take another look tomorrow and merge it in (or maybe move it to a Goodie, now that they support JS!)

We can have the community perfect the mobile display after.

Thanks again for taking the time to contribute! We really appreciate it and I'm sorry this PR has been open for so long. We're constantly trying to improve our process and templates so these can move along smoother and quicker.

**Comment by jagtalon** [comment]
@moollaza I agree with that. Code looks alright with me. Here's an IA page for it: https://duck.co/ia/view/geometry

**Comment by moollaza** [comment]
@pixunil congrats! It's live: https://duckduckgo.com/?q=geometry+cuboid&ia=geometry

Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's & Issues or even submit more Instant Answers!

**Pull request merged**
