### PR TITLE
Sunrise/Sunset: Fixes #2145

### LINKED ISSUE #2145: Sunrise/Sunset: Add triggering for "when is the sunrise in", "when does the sun rise in", etc
We should be able to trigger on queries of these forms:

- "when is the sunrise/sunset in ..."
- "when does the sun rise/set in ..."
- "when will the sun rise/set in ..."
- "sun rise/set in ..."

------
IA Page:  http://duck.co/ia/view/sun_rise_set

### PR DESCRIPTION
**Pull request by sekhavati**
Fixes #2145

https://duck.co/ia/view/sun_rise_set

### CODE REVIEW

**Comment by daxtheduck** [comment]
@sekhavati Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

While the team and the community review your submission, we'd like to make sure you look good! If you'd like a free DuckDuckGo tshirt, please send over the following info to merch@duckduckgo.com, and be sure to put "Dev Merch" in the subject line:

Name:
Street Address:
City:
State / Province:
Country:
Phone (Non-US Orders only): 
T-shirt size:
GitHub username:
Link to this Pull Request:

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by jagtalon** [comment]
:+1:

**Comment by moollaza** [comment]
@sekhavati Welcome to DuckDuckHack! Thanks a lot for contributing (we really appreciate it :smiley:). We invite you to stick around and comment/help on other PR's & Issues or even submit an Instant Answer!

Is there anything specific you like to work on?

**Comment by sekhavati** [comment]
@moollaza Thank you for the warm welcome. I don't have anything in particular I'd like to work on just now but I'll definitely be sticking around! For the time being I'm planning on fixing other issues and generally become more familiar with DuckDuckHack, then longer term hopefully contributing some Instant Answers that will make DDG even better!

I have a question in relation to this PR, how do I go about updating the IA page to include some of the new example queries it now supports?

**Pull request merged**
