### PR TITLE
Templates: Use single quotes for strings

### PR DESCRIPTION
**Pull request by sahildua2305**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] New Instant Answer: **`New {IA Name} Instant Answer`**
- [ ] Improvement
    - [ ] Bug fix: **`{IA Name}: Fix {Issue number or one-line description}`**
    - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [x] Non–Instant Answer
    - [x] Other (Role, Template, Test, Documentation, etc.): **`Templates: Use single quotes for strings`**

###### Which issues (if any) does this fix?

Fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3347

###### People to notify (@mention interested parties)
@moollaza @GuiltyDolphin

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by GuiltyDolphin** [comment]
@sahildua2305 Thanks for this!

One thing I keep forgetting to do is to add `use warnings;` to the Perl back-end files; would you mind adding that here?

**Comment by sahildua2305** [comment]
Here it is! @GuiltyDolphin :wink:

**Comment by GuiltyDolphin** [comment]
@sahildua2305 Awesome, thanks! :dolphin:

**Pull request merged**
