### PR TITLE
New Glassdoor Spice

### PR DESCRIPTION
**Pull request by kevintab95**
IA page: https://duck.co/ia/view/glassdoor

### CODE REVIEW

**Comment by daxtheduck** [comment]
@kevintab95 Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=glassdoor apple)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/glassdoor_mobile.png?lOjtWcQEFC)

**Comment by tagawa** [comment]
@kevintab95 Thanks for making the new pull request - looks much better! As you can see, the beta deployment has worked and it's ready for testing: https://beta.duckduckgo.com/?q=glassdoor%20apple

Let's leave this open for a while to see if there are review comments from the community.

**Comment by kevintab95** [comment]
@tagawa Thanks! But i noticed that the ia page for this spice doesn't show this new PR and Dev Machine status still says not installed on beta. Can I change that or will it get updated automatically? 
IA Page: https://duck.co/ia/view/glassdoor

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=glassdoor apple)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/glassdoor_mobile.png?Dmzwckdi6I)

**Comment by tagawa** [comment]
@kevintab95 Thanks for spotting that. Not entirely sure what was wrong but between us we've fixed it!

**Comment by kevintab95** [comment]
Oh alright! cool! :)

**Comment by kevintab95** [comment]
@tagawa It doesn't seem to work on the beta server! I think it's because I closed and reopened this branch. Can it be deployed on beta again?

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=glassdoor apple)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/glassdoor_mobile.png?QYKa3WJJ3W)

**Comment by tagawa** [comment]
@kevintab95 Not sure what happened there but should be OK now: https://beta.duckduckgo.com/?q=glassdoor+apple&ia=social

**Comment by kevintab95** [comment]
Yep. Thanks! :)

**Comment by tagawa** [comment]
@kevintab95 Well this looks really good and no other feedback comments so let's merge!

Thank you for creating this. We're now focusing on Instant Answers related to programming so if you'd like to continue contributing, please head over to the [DuckDuckHack forum](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53) for more info.

**Comment by daxtheduck** [comment]
@kevintab95 this is now merged! It should be live on DuckDuckGo within one week (or during the next release) and we'll be sure to notify you when it happens.

After your Instant Answer goes live for the World to use, you will be able to see [traffic information](http://docs.duckduckhack.com/maintaining/tools.html#monitor-your-instant-answer-page) about your IA as well as receive feedback directly from users. 
                
Please refer to the [maintenance guide and docs](http://docs.duckduckhack.com/maintaining/guidelines.html) to keep up with potential changes to your Instant Answer.
                
Thank you again for your help!

**Pull request merged**
