### PR TITLE
Currency: Add support for currency symbols

### PR DESCRIPTION
**Pull request by MrChrisW**
Fixing #1175 

**Only adds support for currency symbols** 

Examples queries: 
- $2 to £ => 2 usd to gbp
- 500 usd to ¥ => 500 usd to jpy

### CODE REVIEW

**Comment by javathunderman** [comment]
Is this ready to be merged?

**Comment by MrChrisW** [comment]
@javathunderman Awaiting review :+1:

**Comment by moollaza** [comment]
@MrChrisW please @ mention the person you'd like to review it -- I don't believe GitHub notifies you when you're assigned? At least I don't get emails...

**Comment by MrChrisW** [comment]
@moollaza Sure no problem. There's no alerts for assigning. I assumed this would be picked up by you or Jag when going through PR's :smile: 

@jagtalon Are you able to review this? as the original creator of the Currency IA.

**Comment by jagtalon** [comment]
@MrChrisW Nice! A few questions:

- "$500 to kr" doesn't work but "$500 to dkk" does
- NOK and DKK seem to have the same keys. Shouldn't they be unique?
- What is the source of the YML file?
- Should something like "500 $ to php" work as well where "$" maps to "USD"? Prob outside of this PR, though.

**Comment by MrChrisW** [comment]
Hi @jagtalon! 

>"$500 to kr" doesn't work but "$500 to dkk" does

`kr` wasn't included in the currency symbols file as it's not really a unicode "symbol" it can be added. Or maybe to the currencyNames.txt file instead.

>NOK and DKK seem to have the same keys. Shouldn't they be unique? 

Apparently a whole bunch of currencies with `krone` in their name use the symbol `kr`

+ [Norwegian krone](https://en.wikipedia.org/wiki/Norwegian_krone)
+ [Danish krone](https://en.wikipedia.org/wiki/Danish_krone)

>What is the source of the YML file?

http://www.xe.com/symbols.php

>Should something like "500 $ to php" work as well where "$" maps to "USD"? Prob outside of this PR, though.

That's definitely an option, it would require some modification of the regexp guard again but the mapping is already done.

**Comment by jagtalon** [comment]
@MrChrisW cool. I think this is a good start. We can make issues for the others instead. :+1:

**Comment by MrChrisW** [comment]
@jagtalon Damn that was the quickest review I've ever had.

**Comment by jagtalon** [comment]
@MrChrisW

**Comment by moollaza** [comment]
@MrChrisW nicely done!

**Pull request merged**
