### PR TITLE
make line height avoid cropping in SimilarSites IA

### PR DESCRIPTION
**Pull request by marianosimone**
as @chrismorast said in #2025, this fixes the issue:

screen shot 2015-07-13 at 10 01 17 pm

### CODE REVIEW

**Comment by MrChrisW** [comment]
Thanks for the quick change @marianosimone, this will be reviewed by the design team shortly :+1:

**Comment by moollaza** [comment]
LGTM :+1:

**Comment by moollaza** [comment]
@marianosimone thanks :smiley:

**Comment by chrismorast** [comment]
:+1: ... thanks @marianosimone !

**Pull request merged**
