### PR TITLE
color_picker - updated palette_input border and backgroup colors

### LINKED ISSUE #1789: ColorPicker: Design fixes for dark theme
When using the dark theme, the right inputs are a little hard to read:

2015-04-15_11h43_03

To fix this, we need to change the field BG color to `rgba(150,150,150,.2)` and the border color to `rgba(150,150,150,.0)`

It should look like this:

screen shot 2015-04-15 at 9 19 42 am
screen shot 2015-04-15 at 9 19 38 am

### PR DESCRIPTION
**Pull request by iambibhas**
Fixes #1789. 

selection_015

### CODE REVIEW

**Comment by MrChrisW** [comment]
@iambibhas Maybe we could just set the bg color as `#fff` and set the text color as `#000` to match the other input boxes?

selection_376

**Comment by moollaza** [comment]
@iambibhas thanks LGTM.

@MrChrisW those particular colours we chosen by our designers :)

@chrismorast is this ok?

**Comment by MrChrisW** [comment]
@moollaza No problem, I see that in the original issue :+1:

**Comment by iambibhas** [comment]
@MrChrisW :)

**Comment by moollaza** [comment]
@iambibhas can you post a pic of the display for the default theme please?

**Comment by iambibhas** [comment]
@moollaza here -

**Comment by chrismorast** [comment]
:+1: - Nice work @iambibhas , thank you!

@MrChrisW , the reason we want it to appear separate from the input fields is that these particular fields are not editable. All of the other fields can be edited to manipulate the chosen color.

**Comment by MrChrisW** [comment]
@chrismorast Yup understood. :smile:

**Comment by moollaza** [comment]
LGTM :+1:

**Pull request merged**
