### PR TITLE
CodeSearch: Change endpoint from http to https.

### PR DESCRIPTION
**Pull request by jagtalon**
@MrChrisW @jdorweiler It looks like it wasn't working because the HTTP endpoint was redirecting to the HTTPS endpoint, and we don't have anything configured to handle that. Switching to HTTPS fixes the problem.

screen shot 2015-01-01 at 1 53 55 pm

### CODE REVIEW

**Comment by jagtalon** [comment]
This fixes https://github.com/duckduckgo/zeroclickinfo-spice/issues/1373

**Comment by jagtalon** [comment]
CC @MrChrisW

**Comment by MrChrisW** [comment]
@jagtalon We'll need to update the endpoint to  https://searchcode.com/ not https://searchco.de as the SSL cert is for the .com domain. After that it's good to go!

**Comment by jagtalon** [comment]
@MrChrisW updated!

**Comment by MrChrisW** [comment]
LGTM :+1:

**Comment by MrChrisW** [comment]
@jagtalon Not sure why the `Remove CouponMountain IA` commit 78dae69 is showing up in this... Anyway!

**Pull request merged**
