### PR TITLE
PackageTracking: Adds the regex for OnTrac

### LINKED ISSUE #3344: PackageTracking: Add regex trigger for OnTrac Pattern
### Description
Currently a search for just an OnTrac parcel number returns no results. We can add a regex trigger for this pattern to capture it though.

As far as I've been able to tell OnTrac package codes are simply a "c" followed by 14 digits: 

```perl
/^c\d{14}$/
```

This regex should be added alongside the others in the Perl code.

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/package_tracking

### PR DESCRIPTION
**Pull request by adityatandon007**
## Description of new Instant Answer, or changes
This PR adds the regex trigger for OnTrac and update the test.
Test using `prove -Ilib t/PrackageTracking.t` passed

Earlier:
screenshot from 2017-06-28 17-32-17

Now:
screenshot from 2017-06-28 17-31-59

## Related Issues and Discussions
Fixes #3344 

## People to notify
@moollaza 

---

Instant Answer Page: https://duck.co/ia/view/package_tracking

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by adityatandon007** [comment]
@moollaza  I have added the regex for OnTrac so now it is triggering for query like `C11422907783469` but I was think of supporting query like `D10011125973934` which is a tracking code for OnTrack package too. Though I would need confirmation on your end regarding this.

**Comment by moollaza** [comment]
> I was think of supporting query like D10011125973934 which is a tracking code for OnTrack package too.

Sounds good! Please add it 👍

**Comment by adityatandon007** [comment]
@moollaza support added for the above discussed query

**Comment by moollaza** [comment]
@adityatandon007 Thanks! This LGTM :+1:

**Pull request merged**
