### PR TITLE
Geometry: Improves triggering 

### LINKED ISSUE #2386: Geometry: expand trigger space to cover more common queries
let's add "area of" and "perimeter of" and similar terms to expand the trigger space.

the query "area of a square" should definitely trigger this. it seems to me that "geometry square" is a fairly unlikely query when wondering about the area.

---

IA Page:  http://duck.co/ia/view/geometry

### PR DESCRIPTION
**Pull request by adityatandon007**
## Description of new Instant Answer, or changes
This PR improves the triggering of this IA

## Related Issues and Discussions
Fixes #2386 

## People to notify
@pjhampton @bsstoner

---

Instant Answer Page: https://duck.co/ia/view/geometry

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@adityatandon007 please add some tests to demonstrate the updated triggers work

**Comment by adityatandon007** [comment]
@moollaza @pjhampton for now I've removed the triggers but I have _added extra features_ like ` geometry of cylinder ` and  `geometry of cone` which were not present in this IA. Adding the triggers like `area of`, `volume of` gives ambiguous results and travis is failing too but still there is lots of improvement this IA requires apart from triggering. While I was working on this triggering thing I also encountered some issues which I'll open in issues section. Since I had not developed this IA and I don't know much about CSS and JS that's why I haven't worked on those so I'll open those for the rest to work on though I think it is something related to JS rendering and other styling things. 
One more thing although this is the spice IA but this does not use any external IA so I was confused at first whether it should be under spice or goodie IA and there is so much hard coded formula and some calculations are going on in this IA so I was thinking may be we can merge this into calculator kind of thing.

**Comment by moollaza** [comment]
@adityatandon007 this is looking pretty good. Great job so far 💯 

> Adding the triggers like area of, volume of gives ambiguous results

What do you mean by this? I tried adding `volume of` as a trigger in the Perl and the IA seems to trigger as expected?

> and travis is failing too
Did you check the output from Travis?

It looks like they were failing simply because you were missing a closing `/` in your test 😃 

```
[19:28:20] t/Geometry.t ........................ 1/? 
#   Failed test 'Testing query volume of sphere'
#   at /home/travis/perl5/perlbrew/perls/5.16/lib/site_perl/5.16.3/DDG/Test/Spice.pm line 53.
#     Structures begin differing at:
#          $got->{call} = '/js/spice/geometry/'
#     $expected->{call} = '/js/spice/geometry'
#   Failed test 'Testing query area of square with size = 5'
#   at /home/travis/perl5/perlbrew/perls/5.16/lib/site_perl/5.16.3/DDG/Test/Spice.pm line 53.
#     Structures begin differing at:
#          $got->{call} = '/js/spice/geometry/'
#     $expected->{call} = '/js/spice/geometry'
# Looks like you failed 2 tests of 5.
[19:28:20] t/Geometry.t ........................ Dubious, test returned 2 (wstat 512, 0x200)
```

Please add the triggers back and fix your test 👍 

> One more thing although this is the spice IA but this does not use any external IA so I was confused at first whether it should be under spice or goodie IA

When this IA was initially created, only Spice IAs were able to use JavaScript. Now that Goodies are able to, this IA should definitely be converted to a Goodie. There's actually an in-progress pull request for this: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3181

It may be best to push that forward to solve these issues. If that developer is still interested would you mind waiting for that to be merged and then adding the new cone and cylinder answeres to the Goodie?

**Comment by adityatandon007** [comment]
@moollaza thanks for the feedback. I'd happy waiting till the other developer is done merging this spice into goodie. 

I'd add the triggers and test too after he is done converting this spice to goodie. 

One more thing can you put the label: `on hold` on this issue for now.

**Comment by adityatandon007** [comment]
@moollaza has the other developer converted this IA into goodie. Ping me if it has so that I can test and add more triggers if required. One more thing I would like to make a new PR in case needed. If you agree I can close this PR and then make a new one if required for triggers.

**Comment by moollaza** [comment]
@adityatandon007 the Spice has now been converted to a Goodie. Can you please migrate these changes to the Goodie repo?

**Pull request closed without merging**
