### PR TITLE
Continue PR #2430  - New Package Tracking Spice

### PR DESCRIPTION
**Pull request by moollaza**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

- [x] New Instant Answer: **`New {IA Name} Instant Answer`**

###### Description of changes

Continuing PR #2430. This puts the Instant Answer in a working  state. The triggering still has plenty of room for improvements (i.e. regex)

---

Instant Answer Page: https://duck.co/ia/view/package_tracking

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=shipping status C11422907783469)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/package_tracking_mobile.png?lR0Gu2iTVW)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=shipping status C11422907783469)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/package_tracking_mobile.png?hxHT8FsmI2)

**Comment by daylenca** [comment]
Instant answer works on Firefox, Microsoft Edge, Opera, and Internet Explorer

**Comment by moollaza** [comment]
@daylenca thanks for testing!

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=shipping status C11422907783469)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/package_tracking_mobile.png?z3fuqqDkkc)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=shipping status C11422907783469)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/package_tracking_mobile.png?YWXBxMDir1)

**Comment by moollaza** [comment]
Merging. I've fixed the mobile UI

**Pull request merged**
