### PR TITLE
Bitcoin: Fixes transactions

### LINKED ISSUE #3079: Bitcoin Addresses, Blocks
More at link not working:
https://duckduckgo.com/?q=098e606cee543f86ccc90dccbfef6f5605b7eb654795896d95db44add0fd4431&kp=-1&kad=wt_WT&kl=wt-wt&t=&ia=answer

------
IA Page:  http://duck.co/ia/view/bitcoin 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jmg

### PR DESCRIPTION
**Pull request by nalinbhardwaj**
## Description of new Instant Answer, or changes

Fixes for transaction data from BitEasy API:
- Fixed date time stamp(earlier undefined)
- Fixed meta link

## Related Issues and Discussions

Fixes #3079 

## People to notify

@bsstoner @jmg 

---

Instant Answer Page: https://duck.co/ia/view/bitcoin

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by nalinbhardwaj** [comment]
@adityatandon007 Hope it's fine now. Thanks :)

**Comment by nalinbhardwaj** [comment]
@bsstoner Please review this

**Comment by bsstoner** [comment]
Thanks for the ping.

Looks good 👍

**Pull request merged**
