### PR TITLE
Unesco World Heritage Sites spice

### PR DESCRIPTION
**Pull request by marianosimone**
**What does your Instant Answer do?**
Shows a list of Unesco World Heritage sites, given a country or region

**What problem does your Instant Answer solve (Why is it better than organic links)?**
It displays the list of sites, instead of making the user go to a page which might contain it

**What is the data source for your Instant Answer? (Provide a link if possible)**
The [Unesco World Heritage Convention](http://whc.unesco.org/)

**Why did you choose this data source?**
It's the official Unesco list

**Are there any other alternative (better) data sources?**
None that I'm aware of

**What are some example queries that trigger this Instant Answer?**
- world heritage south america
- unesco heritage sites china
- world heritage sites argentina

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
Travelers, and general public

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
[World Heritage Sites](https://duck.co/ideas/idea/4548/world-heritage-sites)

**Which existing Instant Answers will this one supersede/overlap with?**
None

**Are you having any problems? Do you need our help with anything?**
I tried to use the "Places" or "Map" views, but as the api doesn't provide images, the cards for each site look dull.

I think the list display is adequate, but it would be much cooler if I could add a little map in the right side, but I couldn't find any examples on how to do that following DDG's style guides :(

Rough mockup of what I'd like to do:
mockup

**What are the terms of use for the API? Will DuckDuckGo need specific authorization (e.g. an API key)? Are there any costs associated with API usage?**
The API is not documented, but I found it while playing around with the Unesco World Heritage Convention site's urls

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
world_heritage

## Checklist

```
[X] Added metadata and attribution information
[X] Wrote test file and added to t/ directory
[X] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[X] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
[X] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 10

    - Windows 7
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 8
        [] IE 9
        [] IE 10

    - Windows XP
        [] IE 8

    - Mac OSX
        [X] Google Chrome
        [] Firefox
        [] Opera
        [X] Safari

    - iOS (iPhone)
        [X] Safari Mobile
        [] Google Chrome
        [] Opera

    - iOS (iPad)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - Android
        [X] Firefox
        [X] Native Browser
        [X] Google Chrome
        [] Opera
```

### CODE REVIEW

**Comment by marianosimone** [comment]
look @NickCalabs, another #quackNY PR ;)

**Comment by moollaza** [comment]
@marianosimone this is a great IA -- I have some thoughts/feedback:

>- I tried to use the "Places" or "Map" views, but as the api doesn't provide images, the cards for each site look dull.
    
    @marianosimone you can actually use custom templates for this so the images aren't exactly required (I'll say more about this below...). Using our map view would be ideal -- I'd like to avoid embedding a different map on the page.

There was a developer who previously reached out and was interested in implementing in something very similar, being the UNESCO Wonders of the World. I had discussed that Wikipedia could be used as the source as they index all the UNESCO Wonders and Heritage Sites by country and then have information (and pictures!) for all the sites: http://en.wikipedia.org/wiki/Lists_of_World_Heritage_Sites

Unfortunately if we wanted to show a detailed map view it would require 2 API requests, which we've done previously (e.g. XKCD Spice), but we prefer to avoid that if possible.

We're now working on improving Longtail IA's so you can basically write a parser that will produce a JSON API for you to use -- would you be interested in doing that once we have it working and documented?

**Comment by moollaza** [comment]
I meant to mention that UNESCO has some terms listed on their website with regards to syndication of their data: http://whc.unesco.org/en/syndication/

I think we may have to forego using their internal API because it's likely not intended for public use. If we use Wikipedia as the source, we not have to follow their terms, but it's probably best to reach out to them anyways to let them know what we're thinking.

**Comment by marianosimone** [comment]
@moollaza I also considered using Wikipedia as a source, but the tables that have the name and photo don't expose the lat & lon, so it wouldn't be possible to add a map from there either (unless we parse each site's page... 2nd request, as you said).

I'd love to continue working on this one if the new Longtail IA makes it easier/better. Is there any way I can help to make that happen sooner?

**Comment by marianosimone** [comment]
quick heads up... I've contacted the Unesco to see if there's any problem about using their data this way (and maybe getting more info out of their APIs?)

It's a long shot and I might have to wait for the new parsers to be ready to move this forward... but if they reply, it could be an easy way out ;)

**Comment by moollaza** [comment]
@marianosimone have you heard anything from UNESCO?

**Comment by marianosimone** [comment]
@moollaza unfortunately, nothing yet :(

**Comment by marianosimone** [comment]
I'm closing this as I haven't heard from UNESCO, and the quality of this IA is not good enough to be merged :(

I'm keeping the code in https://github.com/marianosimone/zeroclickinfo-spice/tree/world-heritage-sites for now, but seems like a good implementation should come from using Wikipedia (or other source) instead

**Pull request closed without merging**
