### PR TITLE
IndianRailPnrStatus Spice Instant Answer

### PR DESCRIPTION
**Pull request by jee1mr**
**What does your Instant Answer do?**
It provides the PNR status for Indian Railways

**What problem does your Instant Answer solve (Why is it better than organic links)?**
There aren't any sites currently which provide instant result. Getting PNR status by just searching on a search engine would really be helpful. 

**What is the data source for your Instant Answer? (Provide a link if possible)**
The official API provided by Indian Railways.
http://api.erail.in/

**Why did you choose this data source?**
Because it is official and it is the central source for all other PNR enquiry sites.

**Are there any other alternative (better) data sources?**
No. There are a few but there are some issues with them. Some of them are paid and some of them provide limited usage.

**What are some example queries that trigger this Instant Answer?**
pnr 4101917424
pnr 0123456789
The IA is triggered only if the query is a 10 digit number.

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
Travellers, Passengers, Indian citizens, Tourists, General Public

**Is this Instant Answer connected to a DuckDuckHack Instant Answer idea?**
Yes.
https://duck.co/ideas/idea/4594/pnr-status-for-indian-railways

**Which existing Instant Answers will this one supercede/overlap with?**
None.

**Are you having any problems? Do you need our help with anything?**
Yes. I am having trouble with the test. One of the tests is failing. I couldn't figure out why. 
I have a query regarding the UI and about displaying other data in result.

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**

Valid PNR:
pnr_status_success

Invalid or expired PNR:
pnr_status_fail

**Checklist:**

Please place an 'X' where appropriate.

[X] Added metadata and attribution information
[X] Wrote test file and added to t/ directory
[] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
[] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Linux
        [X] Firefox
   
------

> IA Page: https://duck.co/ia/view/indian_rail_pnr_status

### CODE REVIEW

**Comment by jagtalon** [comment]
@mattr555 What is your professional opinion on this one? :)

**Comment by jagtalon** [comment]
@jee1mr Just requested for an API key from them, then I'll test it out! In the mean time, what are the terms of the API? Do we have to pay in order to get this live?

**Comment by jee1mr** [comment]
@jagtalon It's free.
Here are the limits mentioned in their website:
1. Requests should be made from your server only and not from the clients browser or app.
2. API key is applicable for requests from one IP only
3. Developers should cache the data on their server, following limits apply while making requests between 00:00hr to 23:59 hrs IST
        a) GetStations 10
        b) GetTrains between unique pair of stations 4
4. Max 5 requests per second

But it's not strict, I guess.

**Comment by jagtalon** [comment]
@jee1mr Thanks! I haven't received my API key yet; would you like to share your key with us so that we could test it? You can e-mail it to jagtalon@duckduckgo.com

**Comment by jee1mr** [comment]
@jagtalon Done.

**Comment by jagtalon** [comment]
@jee1mr thank you. Will have a look at it

**Comment by jagtalon** [comment]
@jee1mr currently getting this:

screen shot 2015-01-22 at 6 02 21 pm

Can't seem to make it work at the moment.

**Comment by jee1mr** [comment]
@jagtalon That's correct.  That PNR has expired now. I need to get another valid PNR from someone.

**Comment by jagtalon** [comment]
@jee1mr you mean an API key or an example query? Why do PNRs expire? (Sorry, just trying to understand!)

**Comment by jee1mr** [comment]
@jagtalon No. PNR is a number generated whenever you pre-book a ticket. PNR status is the reservation status of the ticket (Confirmed, Waiting List #, Canceled, etc).  So, it will expire once the journey is completed. There is no sample/example PNR provided which you can use to test. You need an actual live PNR.

**Comment by jagtalon** [comment]
@jee1mr oh I see! Thanks for that--this makes having example queries tricky then. :) Oh please remove caching then since PNRs always update.

Where do you think I could get fresh PNRs for testing?

**Comment by jee1mr** [comment]
@jagtalon Done.
I got one from a friend. I will mail it to you. It might be valid for another week. BTW their server goes down for maintenance between 11:30pm to 00:30 am IST. So, try after an hour. (It's 11:45 here)

**Comment by jagtalon** [comment]
@jee1mr @abeyang up on https://ddh1.duckduckgo.com/?q=pnr+8731622882&ia=pnrenquiry! If it fails, here's a picture:

screen shot 2015-01-30 at 6 06 12 am

@jee1mr what does "CNF" mean? From the JSON output in https://github.com/duckduckgo/zeroclickinfo-spice/pull/1325#issuecomment-67186526, which ones are the most important to you as a traveller?

**Comment by jagtalon** [comment]
@jee1mr tab name should probably be "Status"--we're trying to make them less specific

**Comment by jee1mr** [comment]
@jagtalon CNF means Confirmed. Current Status is obviously the most important. 
"journey": "30-Dec-2014",
"name": "KACHEGUDA EXP",
"from": "SBC",
 "to": "KCG",
"bookingstatus": "S4 35GN" (I think booking status is only shown if the current status is CNF)
could also be shown.

**Comment by jagtalon** [comment]
@jee1mr ah right! Should probably be expanded then from CNF to Confirmed. :) What does "S4 35GN" mean? Is that immediately understood or should that be expanded as well?

**Comment by jagtalon** [comment]
@jee1mr Can we have something like whois for this data? We think that that would be ideal

screen shot 2015-02-20 at 12 53 57 pm

Check out the code in https://github.com/duckduckgo/zeroclickinfo-spice/tree/master/share/spice/whois

**Comment by moollaza** [comment]
ping! @jee1mr are you still interested in finishing this up? If so, would you be able to update the design to use the record template (so it looks like the above screenshot)?

**Comment by jee1mr** [comment]
@moollaza Yes! Sorry, this got too late. I will finish it off soon.

**Comment by jee1mr** [comment]
@moollaza I am out of valid PNRs. Need to find one to finish this off

**Comment by moollaza** [comment]
> I am out of valid PNRs. Need to find one to finish this off

@jee1mr understood. Is this a problem with the API in that it doesn't support PNR's that have been used or is that a problem with the PNR system?

I don't know how we're going to be able to test the API if we always need an active PNR.

Could you possibly ask the API maintainer if he can allow for some static "fake/development" PNR's? That will reliably return an expected result?

**Comment by jee1mr** [comment]
@moollaza I think it's with the PNR system. For previous PNRs it responds as "PNR flushed" or something. It will be impossible to test this IA in future because of that.

I will mail to them to asking about that.

**Comment by jagtalon** [comment]
@jee1mr looking forward to it!

**Comment by jee1mr** [comment]
Mailed them. Waiting for a reply.

**Comment by moollaza** [comment]
>Mailed them. Waiting for a reply.

@jee1mr awesome! I hope they will be able to help us out -- are there any other PNR API's that allow for testing? Can we even get a valid API response from their docs? 

I'm thinking you may be able to use http://www.json-generator.com/ so that you can continue to move forward?

I.e. knowing the required params and their values, you could build a fake response by hand and move along until we have something we can work with.

**Comment by moollaza** [comment]
@jee1mr just checking in again -- anything new?

**Comment by jee1mr** [comment]
@moollaza There are few other APIs. But they are paid. I have used json-generator for now. 
And I haven't got any response from them either. 
I have updated the design to use Record template.

cc /@jagtalon

**Comment by chrismorast** [comment]
@jee1mr , this would actually be a better candidate for the list template. you can see an implementation of it here: https://duckduckgo.com/?q=whois+duckduckgo.com&t=osx&ia=whois

We are in the process of improving the visuals on the record template and merging it with the list template.

**Comment by moollaza** [comment]
@jee1mr sorry for the delay and thanks for using the json-generator. I've been thinking a lot about this IA, and I'm really concerned about the API maintainer's lack of response to you and the inability to use older "expired" PNR's, because it means we're going to have a lot of difficulty testing this should we need to make any adjustments or fix any bugs. As you know, it's already become a problem for you in trying to develop this IA.

Are there any another APIs we can use for this? I really want to be able to use your code, but I'm very skeptical about this API and it's reliability.

**Comment by jee1mr** [comment]
@moollaza There's this: http://railpnrapi.com/. It's very good. They even provide a test account.
But it's not free. :( http://railpnrapi.com/hauth/payment_plans

**Comment by jee1mr** [comment]
@moollaza There's one more free API which went down recently because the domain expired.
I contacted the developer (@sanketsaurav) and he said it will be up soon.
Here's the link to the github repo: 
https://github.com/sanketsaurav/pnrapi

**Comment by moollaza** [comment]
@jee1mr thanks a lot for looking into this -- I really appreciate you sticking around so long!

I'm a little skeptical about the 2nd API given that it's currently down, I'd prefer something a little more official and reliable.

I think it would be best if you reachws out to http://railpnrapi.com/ to ask if they can give us free usage of the API. Many API's have done this for us before, because of the great attribution we provide on the SERP which provides a link back to the provider. I think that API is our best bet, and it also provides a fake number we can use to get test responses.

How does that sound?

**Comment by jee1mr** [comment]
@moollaza Sounds good. I could do that.
But I feel if you mail them as a representative of duckduckgo (ddg email id), we might have a better chance. What do you think?

**Comment by moollaza** [comment]
@jee1mr so I had a quick look at the Disclaimer for railpnrapi.com and a peek at the code for the pnrapi you linked to and I realize now that both of these are skechty at best, given that they're scraping data from the Indian Railway website.

I think it would be best to wait for an official API, now that I understand what railpnrapi is doing, I can't believe they're charging for that...It's quite possibly illegal?

I'm really sorry but I think we should put this on hold until something official comes around. 

Is there something else you'd like to work on?

**Comment by jee1mr** [comment]
@moollaza Yes. I knew that they were scraping. They were made before the official API was out, I guess. 
It's alright. I don't think the official API maintainers are gonna reply. Will try again though.

Help me finish this https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1106? 

And suggest any other IA which needs developer. I've been around for about 6 months with no IA going live :stuck_out_tongue:

**Comment by moollaza** [comment]
>I don't think the official API maintainers are gonna reply. Will try again though.

I don't believe eRail is actually "official" -- they also have a disclaimer saying that they're not affiliated with the railway.

I'll take a look at Lorem Ipsum right now! Very sorry you haven't been able to launch anything months, that's definitely not the experience we're hoping you'll have! If you really want to help out, there's a ton of issues that need tackling like converting existing Goodies to the new templates, or fixing other bugs. If your fix is good, those are likely to get merged much sooner :)

As always, there's many IA ideas on the forum that need someone to implement them. I'd say the surest ones are the ideas where the source (ideally some kind of reliable JSONP API) has been identified and we don't have to worry about being able to test it.

**Pull request closed without merging**
