### PR TITLE
Movies css fix #2470

### LINKED ISSUE #2470: InTheaters: Update detail pane layout
@jagtalon 

Seems that we've had a regression in the layout of the movie information in the detail pane.
Anyone out there open to updating this?

Currently in production:
screen shot 2016-02-02 at 2 11 54 pm

Intended layout:
screen shot 2016-02-02 at 2 10 46 pm

General specifications:
specs

---

IA Page:  http://duck.co/ia/view/in_theaters

### PR DESCRIPTION
**Pull request by Sayanc93**
fix #2470 
http://duck.co/ia/view/in_theaters

### CODE REVIEW

**Comment by daxtheduck** [comment]
@Sayanc93 Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by Sayanc93** [comment]
screen shot 2016-02-21 at 6 46 26 am

also @moollaza any idea why unrelated tests are failing?

**Comment by jagtalon** [comment]
@Sayanc93 thanks! I'd have to test this on multiple devices before I can merge this so hang tight! Also, the Movies spice also shares CSS with InTheaters so you might want to update that as well https://duckduckgo.com/?q=avengers+rotten+tomatoes&ia=movies

**Comment by jdorweiler** [comment]
@jagtalon any updates?

**Pull request closed without merging**
