### PR TITLE
remove console log and update status

### PR DESCRIPTION
**Pull request by jdorweiler**
Removed the console log since this is getting kinda noisy in the console output.
Updated the install status to "success" since we're checking for that when setting the color install flag on line 83.

------
IA Page:  http://duck.co/ia/view/experimentalia
Maintainer: @vikashvverma

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by vikashvverma** [comment]
@jdorweiler Great, looks like earlier it was showing `Installed` for all the IAs even if it was not installed or there was an error.

**Comment by jdorweiler** [comment]
@vikashvverma that's right.  There are still some cases on the beta server back end where an install status might be set to undef even though it is installed.  I'm still trying to track that bug down.

**Comment by jdorweiler** [comment]
@vikashvverma thanks for reviewing.  Any other comments or can I merge?

**Pull request merged**
