### PR TITLE
Forvo: Fix mobile UI and UK Flag

### PR DESCRIPTION
**Pull request by moollaza**
- Fix mobile display with updated CSS and HTML
- Fix UK Flag display with regex replacement

/cc @alexbaforvo 

---
IA Page: https://duck.co/ia/view/forvo

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=pronounce cool)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/forvo_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=pronounce cool)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/forvo_mobile.png)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=pronounce cool)
                
                [Mobile screenshot](https://ia-screenshots.s3.amazonaws.com/forvo_mobile.png)

**Comment by alexbaforvo** [comment]
Sorry for not answering before @moollaza , I was going to push my changes today, but I've seen that you've done before. I see it perfect.

Thank you very much.

**Pull request merged**
