### PR TITLE
Color Picker: Updated the regex to extract 'possible_color_code'  from query string

### LINKED ISSUE #2675: Color Picker:  Inconsistent behavior when searching for "color picker" and "colorpicker"
When you search for "color picker" your search string is populated as the default: https://duckduckgo.com/?q=color+picker+%23af0eff

But when you search for "colorpicker" your search string is ignored and you get a random color: https://duckduckgo.com/?q=colorpicker+%23af0eff&ia=colorpicker

---

IA Page:  http://duck.co/ia/view/color_picker 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @chrisharrill

### PR DESCRIPTION
**Pull request by akanshgulati**
###### Updated the regex to extract 'possible_color_code'  from query string

Choose the most relevant items and use the following title template to name
your Pull Request.

- [ ] Improvement
    - [ ] Bug fix: **`Color Picker: Updated the regex to extract 'possible_color_code'  from query string`**
###### Description of changes

Updated the regex to extract the color code from the query string. The regex now support case-insensitive queries and even work for "color picker" and "colorpicker", i.e. space is optional now.

###### Fix the issue of exact query to open Color Picker with color code

Fixes #2675  - The space is optional now and it can work even without a space like "colorpicker"
Fixed #2721 - It can now add Upper Cases query too. 

###### People to notify @moollaza @jkrobles 

---

Instant Answer Page: https://duck.co/ia/view/color_picker

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mention

### CODE REVIEW

**Comment by daxtheduck** [comment]
@akanshgulati Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by akanshgulati** [comment]
@moollaza @GuiltyDolphin The code has been changed for the IA, so please check for this PR. https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3367

**Comment by moollaza** [comment]
@akanshgulati thanks for this. Please see my comments here: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3367#issuecomment-234713920

This code will be deleted next week as the IA is being converted to a Goodie

**Comment by moollaza** [comment]
I believe this has been addressed in the PR that ports this IA to a Goodie. If not a new Goodie PR will be necessary.

**Pull request closed without merging**
