### PR TITLE
Fix border css

### PR DESCRIPTION
**Pull request by gokul1794**
Border set to transparent #1857

### CODE REVIEW

**Comment by moollaza** [comment]
@gokul1794 thanks! It looks like the first element still has a top border though! Let's make sure that one is transparent as well!

**Comment by moollaza** [comment]
In general, when updating the UI, it's best to take a screenshot so we can quickly assess the changes :)

**Comment by moollaza** [comment]
My mistake, I was looking at the wrong code!

This LGTM :+1:

**Comment by gokul1794** [comment]
Is this IA not live btw?

**Comment by gokul1794** [comment]
Sorry, my mistake I forgot to add the .com while searching

**Pull request merged**
