### PR TITLE
New IPLStandings Spice

### PR DESCRIPTION
**Pull request by Prajithp**
## Description of new Instant Answer, or changes
Show the Indian premier league point table.

## Related Issues and Discussions

Unsolicited PR 

## People to notify

@pjhampton
@moollaza 

---

Instant Answer Page: https://duck.co/ia/view/ipl_standings

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@Prajithp can you explain where the data is coming from? Is this a public API that's meant to be consumed by 3rd parties?

**Comment by Prajithp** [comment]
@moollaza the data is coming from the official iplt20.com website(http://datacdn.iplt20.com/dynamic/data/core/cricket/2012/ipl2017/groupStandings.js) but am not sure whether it is opened for 3rd parties. I will check with them and update here the status.

**Comment by Prajithp** [comment]
@moollaza You can close this as I did not get any update from them. Thanks

**Pull request closed without merging**
