### PR TITLE
WIP: Fix example_queries

### PR DESCRIPTION
**Pull request by MrChrisW**
WIP PR: Fixing the following reported issues surrounding **primary query examples**.

- [X] ~~#1373 - CodeSearch example query doesn't work~~
- [X] ~~#1372 - 
Steam example query doesn't work~~
- [X] ~~#1371 - News example query doesn't work~~
- [X] ~~#1370 - detectLang example query doesn't work~~ - Fixed (a29eccc): Change ["como estas"](http://ws.detectlanguage.com/0.2/detect?q=como+estas&key=demo) to ["cómo estás"](http://ws.detectlanguage.com/0.2/detect?q=c%C3%B3mo%20est%C3%A1s&key=demo) 
- [X] ~~#1368 - hayoo example query doesn't work~~

### CODE REVIEW

**Comment by MrChrisW** [comment]
@jagtalon No problem.

+ I've updated the news queries, surprisingly "obama news" is one of the queries :laughing:
+ I've removed Hayoo, I'm unable to find an alternative at this stage :frowning:

**Comment by jagtalon** [comment]
@MrChrisW Thanks--this looks good! :+1:

**Comment by jdorweiler** [comment]
@MrChrisW Thanks for fixing these!

**Comment by MrChrisW** [comment]
@jdorweiler Happy to help! 
I take it these example queries need to function for the screenshots being used on the [IA page](http://duck.co/ia/) which looks fantastic!

**Pull request merged**
