### PR TITLE
Currency: '=' to trigger 

### PR DESCRIPTION
**Pull request by pjhampton**
## Description of new Instant Answer, or changes

This 2 character change reflects user feedback described here https://github.com/duckduckgo/zeroclickinfo-spice/issues/3137

Fixes: https://github.com/duckduckgo/zeroclickinfo-spice/issues/3137

---

Instant Answer Page: http://duck.co/ia/view/currency

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by bsstoner** [comment]
👍 Looks good to me.

**Comment by pjhampton** [comment]
I will add a test soon. Please hold off from merging [for now]

**Comment by moollaza** [comment]
@pjhampton I added a test, and also handling of the `= ? USD` format (I saw feedback for that + it was already on our tests as something we should eventually handle)

Care to review?

**Comment by pjhampton** [comment]
Nice! Thanks for taking that forward @moollaza. This LGTM

> PR authors can't review their own pull request

Looks like it's over to @bsstoner or @MrChrisW to merge 👍

**Pull request merged**
