### PR TITLE
Timer: Fixes #2315

### LINKED ISSUE #2315: Timer: Start automatically if time was given as search query
If I enter "timer 10 minutes" the timer is set to 10 minutes which is fine. It would be even better if the timer would start automatically if searched for timer with a given time.

______
IA: https://duck.co/ia/view/timer

### PR DESCRIPTION
**Pull request by lerna**
screen shot 2015-12-06 at 11 43 43 am

### CODE REVIEW

**Comment by daxtheduck** [comment]
@lerna Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

While the team and the community review your submission, we'd like to make sure you look good! If you'd like a free DuckDuckGo tshirt, please send over the following info to merch@duckduckgo.com, and be sure to put "Dev Merch" in the subject line:

Name:
Street Address:
City:
State / Province:
Zip Code:
Country:
Phone (Non-US Orders only): 
T-shirt size:
GitHub ID:
Link to this Pull Request:

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by jagtalon** [comment]
:+1: nice!

**Comment by moollaza** [comment]
@lerna the team just noticed that for the query `timer` we're defaulting to a 1 minute timer and auto-starting. 

We should skip the auto-start when the query is just `timer` -- it's a little unexpected since no timer has been specified.

**Comment by moollaza** [comment]
I'm going to make an issue for this, if you'd like to fix it, please comment there!

**Pull request merged**
