### PR TITLE
Nutrition: Add min_score param

### LINKED ISSUE #2419: Nutrition: Triggers on "count calories"
"count calories" shouldn't show this IA because we're not specifying any food:

screen shot 2016-01-18 at 2 06 37 pm

### PR DESCRIPTION
**Pull request by MrChrisW**
Fixes #2419

The score for results mentioned in #2419 are below 1 - see https://duckduckgo.com/js/spice/nutrition/count

~~Using the `min_score=1` param we can limit results to only return above 1. - documentation https://developer.nutritionix.com/docs/v1_1~~

~~Needs to be deployed to beta for testing as unable to test locally without obtaining new API key.~~

_________

https://duck.co/ia/view/nutrition

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@MrChrisW deploying to beta...

**Comment by MrChrisW** [comment]
@moollaza Turns out we can't use the `min_score` param without sending json POST requests to the API :frowning: 

This should do a similar thing - 1aec9410ffac1e3111f35673127d22663df9115a  `max_score` contains the highest relevancy score from all items returned.

**Comment by GuiltyDolphin** [comment]
@moollaza Can we re-deploy this?

**Comment by jagtalon** [comment]
@MrChrisW works well! Thank you! :+1:

**Comment by MrChrisW** [comment]
@jagtalon :+1: :+1:

**Pull request merged**
