### PR TITLE
Initial commit of AQI spice

### PR DESCRIPTION
**Pull request by schluchc**
What does your Instant Answer do?
- Display air quality indices of locations identified by ZIP code (currently only in the US).

What problem does your Instant Answer solve (Why is it better than organic links)?
- It's only one or two relevant numbers, it's a waste of time to follow links to find them.

What is the data source for your Instant Answer? (Provide a link if possible)
- www.airnowapi.org

Why did you choose this data source?
- It is the only one I found until now that provides JSON.

Are there any other alternative (better) data sources?
- I hope so, ideally the instant answer would not just support US locations.

What are some example queries that trigger this Instant Answer?
- aqi 20002

Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)
- everyone living in a city where air quality is a concern (China would have been my idea, but I couldn't find a source providing a JSON API)

Is this Instant Answer connected to a DuckDuckHack Instant Answer idea?
- Yes, I added one: https://duck.co/ideas/idea/4642

Which existing Instant Answers will this one supersede/overlap with?
- I couldn't find anything related to air quality.

Are you having any problems? Do you need our help with anything?
- Finding more sources is most important.
- Authentication to the API (see below)

What are the terms of use for the API? Will DuckDuckGo need specific authorization (e.g. an API key)? Are there any costs associated with API usage?
- It needs an API key, currently it is an account I just created for test purposes and it is hardcoded. I don't know if that key allows duckduckgo to use the API of airnowapi.org productively.

Where did you hear about DuckDuckHack? (For first time contributors)
- news.ycombinator.com

What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)
image

Checklist

Please place an 'X' where appropriate.

[X] Added metadata and attribution information
[] Wrote test file and added to t/ directory
[X] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[X] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
[] Tested cross-browser compatibility (I'm currently having serious problems with my internet connection, I can test more later.)

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 10

    - Windows 7
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 8
        [] IE 9
        [] IE 10

    - Windows XP
        [] IE 7
        [] IE 8

    - Mac OSX
        [X] Google Chrome
        [] Firefox
        [] Opera
        [] Safari

    - iOS (iPhone)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - iOS (iPad)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - Android
        [] Firefox
        [] Native Browser
        [] Google Chrome
        [] Opera

### CODE REVIEW

**Comment by abeyang** [comment]
Hi @schluchc, no problem. LMK what you find. Happy New Year!

**Comment by moollaza** [comment]
ping! @schluchc are you still interested in finishing this?

**Comment by schluchc** [comment]
hey, sorry for long time no activity, I understand it's a bit cumbersome. I've been quite busy recently, but should be able starting from next week to continue and finish the instant answer.

**Comment by jagtalon** [comment]
@schluchc sweet! No rush--please take your time. :)

**Comment by moollaza** [comment]
ping! @schluchc just wanted to check in to see if you're still interested in finishing this up?

**Comment by schluchc** [comment]
Hey, yes, still interested, just having a few very busy weeks. Please give me a few more and it will be done. If anyone else wants to finish it, that's also alright with me, but I'm still motivated to finish it myself.

**Comment by moollaza** [comment]
> but I'm still motivated to finish it myself.

Glad to hear it! There's no rush, I'm just checking to make sure our PR's haven't gone stale :)

Thanks again!

**Comment by schluchc** [comment]
Finally had the chance to look into it again. Now I have another question: The API replies with several objects one for each value of the queried city. So the easiest is to just feed the objects to the template, as I did so far. Since we want to combine the common values, like the city name and time stamp, we don't want to use one info box for each replied object, but rather put all values into one box as @moollaza proposed earlier. Now to do that, do I have to process the data in perl and merge it into one object before I send it to the template, or is there a way to make one box and only use a template to fill the box' list?
I'm not sure if I expressed myself clearly. I guess this screenshot of the current version explains my problem. Obviously, I want the two values within the same box.
screen shot 2015-02-15 at 11 51 54

**Comment by moollaza** [comment]
>do I have to process the data in js and merge it into one object before I send it to the template, or is there a way to make one box and only use a template to fill the box' list?

@schluchc glad to see you had some time to work in this! You can definitely opt for a single "detail" view, rather than a "tile" view. All you need to do is set the `item` template to `false`:

```js
templates: {
    group: 'text',
    item: false
}
```

**Comment by schluchc** [comment]
@moollaza thanks for your help again.
What I still don't understand, independent of the template: From the API I get objects like this {ReportingArea, DateObserved, ParameterName, AQI} (leaving out some irrelevant info), that means for each AQI value, I get the reporting area and time, even though it's always the same reporting area. So if I just iterate through all objects, the reporting area is shown several times, once in each item. But I actually want to show the reporting area and time only once, like this:

ReportingArea (of the first object), DateObserved (of the first object)
AQI (of the first object)
AQI (of the second object)
...
AQI (of the last object)

I was able to achieve that using the meta tags "primaryText" and "secondaryText" to show the reporting area and time and then in the actual items only show the AQIs, leading to this:
screen shot 2015-02-17 at 22 01 34

That's pretty close to what we wanted, I guess, and might even be acceptable, but it's not what you were thinking of, right? So, how is it possible to have just one (detailed) item, set the title of that item just once according to the report area of one of the objects, and then show the AQIs of all the objects within that item?

**Comment by moollaza** [comment]
>So, how is it possible to have just one (detailed) item, set the title of that item just once according to the report area of one of the objects, and then show the AQIs of all the objects within that item?

@schluchc so you're on the right track. There approach would be to show a detail area as you've done, and then, seeing as this is using the `text_detail` template (https://duck.co/duckduckhack/spice_templates_overview#textdetail-template)

You'll need to provide a string for the `title` property (i.e. the name of the location) and a string for `subtitle` (i.e. "Air Quality Index as of ... "). These would be specified in your `normalize()` function.

Then, you'll need to create a handlebars template in `/share/spice/aqi/` named `content.handlebars`
which you give to the `content` property:

```js
templates: {
   ...
    options: {
        content: Spice.aqi.content
    }
}
```

In your handlebars template, you'll probably want to use the `{{#each}}` block helper to iterate over your array (or `{{#keys}}` if it's an object). In each iteration you'll then create the markup (likely an `<li>` that references the properties/values you need from that specific object to produce the content in the mockup. It would look something like this:

```handlebars
<ul>
{{#each aqi_measurements}}
    <li>
        <span class="aqi__circle {{aqi_circle_colour aqi_value}}"></span>
        <span class="aqi__text">
            {{measurement_type}}: {{measurement_score}} {{measurement_rating}}
        </span>
    </li>
{{/each}}
</ul>
```

I didn't check what the data looks like so the variables in there are wrong but I hope this makes it clearer? I suggest you take a look at the GithubStatus, MinecraftStatus and other "status" Spices because they have a very similar look/feel.

Let me know if you need more help!

**Comment by schluchc** [comment]
@moollaza Thanks a lot once again! I think I finally got how to build the list now.
Additionally, I separated the dates of the measurements, as there is no reason to assume that they have all been taken at the same point in time. Also, I added an information link about the different parameters.

Please have a look and tell me what you think. I hope we are finally getting closer to actually getting it merged :)
screen shot 2015-02-22 at 20 33 16

**Comment by schluchc** [comment]
One more thing, the colors of the badges are rather ugly, but I wanted to use the original colors AirNow uses. Do you agree or should we use nicer colors?
If anyone wants to improve anything else regarding the formatting or design, please feel free to do so, or let me know.

**Comment by chrismorast** [comment]
@schluchc , this is looking great. Can you please use the following palette?
aqi color palette


Also, is it possible that we switch this to our list view? https://duckduckgo.com/?q=whois+duckduckgo.com&t=osx&ia=whois
And a screenshot of it...
screen shot 2015-02-23 at 2 41 32 pm

Also, please turn off all link colors. (O3 and PM@.25) should be color #333333 or #666666

Thanks!

**Comment by schluchc** [comment]
@chrismorast Thanks for looking at it. I updated the colors and link styles. For the list view however, I'm having a bit of troubles. So first of all, what do you think would be better when list view is used? Are there any troubles when defining a custom <table>?

Secondly, if I use the 'record' list view, I can only define a key and a value, right? So if I still want the keys to be links (e.g. O3 linking to the O3 info page), then do I need to use the whole <a> tag as key? Or how can I use any self defined templates within the list to show more than just the nude key (e.g. a link based on the key)?
Also, as I see it (I might very well be wrong) list view only allows a table with two columns, but I'd rather have 4, as on the screenshot above. Can that be done using the list view?

I'm lacking the experience here, but I think my data is just not really suitable for the list view. I added a second file aqi_list_test.js that shows my current state, but I'm a bit lost on how to get something similar as I had before with the list view. If anyone could have a look on that, it would be great. Otherwise I would vote for not using the list view, unless there is a good reason to use it.

**Comment by chrismorast** [comment]
Hi @schluchc , 
We're actually in the process of implementing standardized templates for the majority of our instant answers. This way any updates to our UI can be rolled out a lot easier than if we were to have custom implementations on everything. Your IA is a perfect fit for the list view which is now being converted to a template. The template should be available within the next week or 2 and I would love to get your input on the implementation. To address your comments above; additional columns will be available in the template. As far as the unique row linking goes, I'll put in a request for that to be an available option.

Here's an example of the scalability. The CSS is still being worked on so I've left the details out. The template structure at the footer of the page is placeholder content. That is currently being defined and will be available once the template is.

list-table-template - preliminary-01
Considering the proposed flexibility of what you see here do you still feel your IA is not a good fit for this?

**Comment by schluchc** [comment]
@chrismorast Nice question, of course list view would fit perfectly then. But was this information online already? I didn't find anything about the list view other then the 'records' template and similar templates, hence my assumption that it wouldn't really fit. Maybe I looked at the wrong place.
Please give me a hint when the list template is ready then, and I'd be happy to give you some feedback.

**Comment by moollaza** [comment]
> was this information online already? I didn't find anything about the list view other then the 'records' template and similar templates, hence my assumption that it wouldn't really fit. Maybe I looked at the wrong place.

@schluchc no this info isn't public yet. We're in the process or revising and improving our templates to be more flexible and allow for new, different layouts.

We'll be sure to ping you when the new templates are ready, if you don't mind putting this on hold.

**Comment by chrismorast** [comment]
Hi @schluchc , unfortunately this is not available online yet. I apologize for the confusion. Adding @sdougbrown (our front-end magician) to the thread as he is in the middle of merging this template so that it is available to the public. We would love to get your input on implementing it in this case. Perhaps there's  somethings we can improve on.

**Comment by moollaza** [comment]
@schluchc sorry for the delay -- the list template is now live and working! You can use it by adding a `list` object to your data object. It should be an array of objects, each of which will be passed to a `list_content` template as the context so you can render each `<li>` with it's own special content.

I would suggest you wrap the 5 elements of each `<li>` in a span tag an then style them with some CSS to achieve the right layout. We're still working to bring support for multi-column tables but this should suffice for now so we can move things along.

I'm terribly sorry for all the delays, we're constantly trying to improve our process so everything flow much smoother. We also try to identify gaps in our templates so we can build better ones and this PR has helped us to identify the need for improved table/list templates!

Thanks again for contributing, we really appreciate it!

------

Here's a basic example of how you can use the list template:

```js
Spice.add({
    id: 'aqi',
    name: "Air Quality Index",
    data: {
        list: [{
            circle_category: 'good',
            aqi: 11,
            ...
        }, {
            circle_category: 'bad',
            aqi: 2,
            ...
        },
           ...
        }];
    },
    templates:{
        group: 'list',
        options: {
            list_content: Spice.aqi.list_content //refers to /share/spice/aqi/list_content.handlebars
        }
    },
    ...
});
```

**Comment by schluchc** [comment]
@moollaza No problem, I can imagine it's not easy to keep an API that simple and open. Great that the template is now available. I adapted the IA to use it and the only thing still needed to be done is cleaning-up the formatting a bit. Multi-columns would definitely make things even easier, but besides that I think the template is quite straight-forward to use. (Admittedly, it took me a while to get the templates to work at all, but I'm also quite new to both js and perl and the move to the list was really easy.)

I'm glad, this PR was already of some use and still hope we can eventually merge it :)

**Comment by schluchc** [comment]
I added some css to imitate the multi-column now. It's certainly not the nicest code, but I think the outcome looks good enough and the code is bearable until the multi-column layout is available.

**Comment by schluchc** [comment]
@moollaza Is the multi-col template something you wanted to build soon, or do you think we can merge this IA before?

**Comment by moollaza** [comment]
@schluchc apologies for the delay -- the multi-column template isn't ready yet so I think we can move forward with this. I'll put it up on a machine shortly.

/cc @abeyang

**Comment by javathunderman** [comment]
@moollaza Any updates?

**Comment by moollaza** [comment]
@schluchc I'm so sorry this one has gone on so long. It's looking great to me. We unfortunately still don't have support for multi-column tables, but I've re-raised the issue with the team so will work on it a little sooner!

**Comment by schluchc** [comment]
@moollaza cool! thanks for merging. It took indeed a bit long, but I'm glad it got finally merged. I will try to find time for a second IA.

**Comment by moollaza** [comment]
>I will try to find time for a second IA.

@schluchc That's wonderful! Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's & Issues or tackle open GitHub issues!

**Pull request merged**
