### PR TITLE
MetaCPAN Spice fix

### PR DESCRIPTION
**Pull request by digital-carver**
Fixes the broken link mentioned in #1815  

My first duckduckhack, so do let me know if anything's gone gooey (I'm assuming the Pull Request Template would be overkill for this though). The fix was manually verified and the build dzil-tested.

### CODE REVIEW

**Comment by moollaza** [comment]
@digital-carver thanks a lot for contributing! This is pretty great so far, but while we're at it I'd like some other stuff to be fixed, if you're up for it?

1. Please re-indent with soft-tabs (we use 4 spaces instead of hard tabs
2. We now actually have a `list` template group, so let's switch the group, `group: "list",`
3. Let's provide a `title` and a `subtitle`

If you're up for an even bigger challenge, I think we should probably make the effort to re-design this IA so that it looks like the [NPM Spice](https://duckduckgo.com/?q=npm+colors&ia=software). The [code](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/share/spice/npm/npm.js) is pretty straightforward, and could be copied for the most part.

How does that sound?

**Comment by moollaza** [comment]
If you're interested and want to tackle it in another PR just let me know and I'll merge this one :+1:

**Comment by digital-carver** [comment]
> Please re-indent with soft-tabs (we use 4 spaces instead of hard tabs

Gah! Vim's `expandtabs` has spoiled me, and I forgot to configure Codio's Vim before beginning work. Anyway, I've changed that and amended the commit (to keep the log clean), please check it out. 

> If you're interested and want to tackle it in another PR just let me know 

Sure, that sounds best. I'll take a look at the npm code.

**Comment by moollaza** [comment]
>Gah! Vim's expandtabs has spoiled me, and I forgot to configure Codio's Vim before beginning work. Anyway, I've changed that and amended the commit (to keep the log clean), please check it out. 

Hmm I thought it was pre-configured to use spaces, but I'll verify!

>Sure, that sounds best. I'll take a look at the npm code.

Awesome! I look forward to your PR :+1:

**Pull request merged**
