### PR TITLE
Flight Routes: Solved timezone issues

### PR DESCRIPTION
**Pull request by amoraleda**
@moollaza got almost all the work done in his previous commit. 

I just solved the timezone issue by getting the UTC instead of the browser's timezone when calculating flight status. Also, fixed some problems when calculating the progress of the flight and showing the delayed time.

***
IA Page: https://duck.co/ia/view/route

### CODE REVIEW

**Comment by daxtheduck** [comment]
@amoraleda Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by zekiel** [comment]
Not sure where the discrepancy is but Flight Routes and the Flights IA are reporting different status' and takeoff/departure times for the same flight
screen shot 2016-03-22 at 11 05 56 am
screen shot 2016-03-22 at 11 05 52 am

**Comment by amoraleda** [comment]
This would be the result with the new changes I just pushed:

screenshot from 2016-03-22 15 27 04
 
As you can see in the following picture, the arrival tab says that the flight is delayed 11min:

screenshot from 2016-03-22 15 19 09

**Comment by moollaza** [comment]
Thanks! This LGTM :+1:

Some minor bugs have been noted and will be fixed soon.

**Comment by zekiel** [comment]
wow -- it's awesome to see this being addressed. Thank you @amoraleda. Issues here stretch the entire way back to #1736, #2160 and  #2301

**Comment by amoraleda** [comment]
You're welcome, @zekiel! It's a pleasure to be helpful =)

**Pull request merged**
