### PR TITLE
New Spice: Proxy list

### PR DESCRIPTION
**Pull request by puskin**
**What does your Instant Answer do?**
Returns infos about free proxys

**What is the data source for your Instant Answer? (Provide a link if possible)**
www.yasakvar.com

**What are some example queries that trigger this Instant Answer?**
`proxy` or `proxy list`

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
programmers and computer addicted

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
Yep, here https://duck.co/ideas/idea/4662/public-proxy-servers

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**

proxy
## Checklist

Please place an 'X' where appropriate.

```
[X] Added metadata and attribution information
[X] Wrote test file and added to t/ directory
[X] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[X] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
[X] Tested cross-browser compatibility
```

---

IA Page: https://duck.co/ia/view/proxy

### CODE REVIEW

**Comment by puskin94** [comment]
Travis is failing due to `no environment variables set`, It is about `dzil`. Local test is actually working
proxy-2

**Comment by stevenmg** [comment]
I'm glad to see this idea becoming a reality. I'll gladly help out with testing and what not later.

**Comment by jagtalon** [comment]
@puskin94 Looks like the API is down at the moment--will have to wait before I can test it.

- What does the date mean? Is it last updated or when it was last up? It's unclear from the picture.
- It looks sketchy. If I'm looking for proxies and I stumble upon this, I don't think I'd know what to do with them or what their privacy policies are.
- Is this the best source for proxies?

@abeyang is this the best format for this? I don't know what kind of available data that we have either since the service is down, but @puskin94 might be able to fill you in. :)

**Comment by jagtalon** [comment]
@puskin94 unfortunately this IA hasn't been up since. 

8phanft

Do you have an alternate source that you could replace it with? If not we should probably close this.

**Comment by puskin94** [comment]
@jagtalon I made a quick search on the web and I found nothing... It was a valid IA ;(
very_sad

**Comment by moollaza** [comment]
Closing for now. We'll need to find a new source. Will make an IA page so it stays alive :)

**Pull request closed without merging**
