### PR TITLE
CanIUse Spice: Update regex

### PR DESCRIPTION
**Pull request by rasikapohankar**
###### Description of changes

Added anchors in the regular expression to ensure extra words are not allowed. Removed loop from javascript which was unnecessary after adding the anchors and updated the test file.

###### People to notify (@mention interested parties)

@moollaza 

---

Instant Answer Page: https://duck.co/ia/view/caniuse_lists

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @rasikapohankar

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=css browser compatibility)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/caniuse_lists_mobile.png?H8lq4Ly09M)

**Comment by moollaza** [comment]
@rasikapohankar Thanks! This LGTM :+1:

I just thought of a couple more trigger words too:

- browser compatibility list
- browser compatibility reference

Can you please add those in?

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=css browser compatibility)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/caniuse_lists_mobile.png?FzozA2Yhn4)

**Comment by moollaza** [comment]
Thanks! This LGTM :+1:

**Comment by rasikapohankar** [comment]
Thank you @moollaza!

**Pull request merged**
