### PR TITLE
Haxelib: Use newer text layout and include owner, changes and tags in box data

### PR DESCRIPTION
**Pull request by TomBebbington**
# Changes

This PR basically:
+ Adds project tags to the box panel.
+ Adds the project's owner to box panel.
+ Adds the project's website to box panel.
+ Moves the license to the box panel.
+ Adds a changes box to the box panel with the summary of the latest change to the package.

# Screenshots
## Expanded new style

---

Instant Answer Page: https://duck.co/ia/view/haxelib

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@TomBebbington sorry for the delay! It's nice to see you again, this looks great 👍 

Deploying the changes to Beta now...

**Comment by moollaza** [comment]
@TomBebbington Thanks! This LGTM :+1:

**Comment by TomBebbington** [comment]
No problem, it just looked like it needed a polish.

**Pull request merged**
