### PR TITLE
Update Stocks Spice, switch data source

### PR DESCRIPTION
**Pull request by moollaza**
/cc @bsstoner @abeyang @chrismorast @pswam @jagtalon 

2015-04-21_16h56_42

### CODE REVIEW

**Comment by abeyang** [comment]
@moollaza Can we have "Data by Xignite" to be the same color as "More at NASDAQ"?

**Comment by moollaza** [comment]
@abeyang fixed, https://moollaza.duckduckgo.com/?q=stock+quote+nke&ia=stock

**Comment by moollaza** [comment]
Just noticed I need to round the percent change to 2 DP and also add the percent sign.

**Comment by moollaza** [comment]
Updated on https://moollaza.duckduckgo.com/?q=stock+quote+MSFT&ia=stock

**Comment by jagtalon** [comment]
@moollaza there's a deprecation warning in the console.

screen shot 2015-04-22 at 1 51 13 pm

**Comment by moollaza** [comment]
@jagtalon ya I noticed that -- I think it's because of the way I'm parsing the `time` they give us. Unfortunately they give us a time string that can't be parsed by native JS or moment.js "hh:mm:ss A" doesn't follow any standard conventions *which* really sucks. I read the thread they linked and I don't believe we're at risk using moment's parsing ability

**Comment by jagtalon** [comment]
:+1:

**Comment by jagtalon** [comment]
We moved because YCharts is deprecating their API.

**Pull request merged**
