### PR TITLE
currency: Show localised currency conversion result

### PR DESCRIPTION
**Pull request by NaveenKarippai**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.
- [ ] New Instant Answer: **`New {IA Name} Instant Answer`**
- [x] Improvement
  - [x] Bug fix: **`currency: Fix {#2735}`**
  - [ ] Enhancement: **`{IA Name}: {Description of Improvements}`**
- [ ] Non–Instant Answer
  - [ ] Other (Role, Template, Test, Documentation, etc.): **`{SpiceRole/Templates/Tests/Docs}: {Short Description}`**
###### Description of changes

If the user queries for `42 gel`, he should be shown currency
conversion result (localised) according to the region. This could
be done by mapping countries list to currency list, and setting
a fallback to `localised` currency.

Provide an overview of the changes this pull request introduces.
- added yml file with country-currency mapping
- show localised currency conversion results
###### Which issues (if any) does this fix?

See also: #2735

Fixes #NNNN - how specifically does it fix the issue?
###### People to notify (@maslic , @moollaza , @GuiltyDolphin , @mintsoft )

---

Instant Answer Page: https://duck.co/ia/view/currency

[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @MrChrisW

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by NaveenKarippai** [comment]
**ToDo:**

* [ ] Add list of countries and corresponding currency data on yml file

**Comment by NaveenKarippai** [comment]
@MrChrisW could you please review the changes and make sure that it's the right path to proceed further. Thanks!

**Comment by GuiltyDolphin** [comment]
@NaveenKarippai People have already worked pretty hard to standardize this kind of thing - I'd recommend checking out the work done by the great people in the Unicode Consortium - specifically the Unicode Common Locale Data Repository.

**Comment by NaveenKarippai** [comment]
@GuiltyDolphin Sure, I will have a look at Unicode Common Locale Data Repository. Thanks! 

But, again could you please be more specific - are the changes not in the right path to proceed further?

AFAIK, `$loc` gives location related info about the user, what would be another workaround?

**Comment by GuiltyDolphin** [comment]
@NaveenKarippai You can gain access to the locale through `$lang`; there's a bunch of Perl packages for interfacing with CLDR data (and other Locale packages too) which you should be able to plug this into.

I would say just sticking the currencies in a file is ***not*** the right decision - either we should be using specialized Perl packages or attempting to gain more info from the API.

@MrChrisW Might know some more about whether or not the API can provide this information.

**Comment by NaveenKarippai** [comment]
@GuiltyDolphin Thanks! I'm looking forward to @MrChrisW response.

**Comment by MrChrisW** [comment]
@NaveenKarippai @GuiltyDolphin Sorry for the delay on a response. 

>Might know some more about whether or not the API can provide this information.


Unfortunately there's not much information on the API. It may be worth asking Staff for more information on the API docs as they're only available if you've purchased the service. 

@GuiltyDolphin Is correct we should be using a Perl package to convert from the location to currency code.

**Comment by andrey-p** [comment]
Hey guys, just a quick heads up. We've been getting a number of complaints from users about this issue, so I've put together a quick PR here: https://github.com/duckduckgo/zeroclickinfo-spice/pull/3072

I'm afraid I went for the hardcoded list approach. I'm aware it's not perfect, but I'd rather take a solution that may go slightly out of date in a couple of years' time than not having a solution at all.

**Pull request closed without merging**
