### PR TITLE
Movies: Mobile view

### PR DESCRIPTION
**Pull request by MrChrisW**
Attempt at fixing #1407 (Movies: Broken on mobile)
Probably going about this the wrong way, changing the wrong css selectors etc, however thought I'd give it a go :grimacing: 

**Current** - https://duckduckgo.com/?q=rotten+tomatoes+guardians+of+the+galaxy&ia=movies
selection_115

**After Changes**
selection_112

**CC//** @jagtalon

### CODE REVIEW

**Comment by jagtalon** [comment]
@MrChrisW works well for single view, although when there are multiple items, the image is not aligned properly (it's too far off to the left):

screen shot 2015-01-23 at 8 39 25 am
screen shot 2015-01-23 at 8 39 37 am

**Comment by MrChrisW** [comment]
@jagtalon Thanks for testing. Will update to fix multiview.

**Comment by MrChrisW** [comment]
@jagtalon Should be good now, let me know :smile: 

selection_119
selection_118

**Comment by jagtalon** [comment]
:+1:

**Pull request merged**
