### PR TITLE
Adding English to Malayalam Dictionary

### PR DESCRIPTION
**Pull request by EaswareApps**
What does your Instant Answer do? - Translate English Word into Malayalam(ML)

What problem does your Instant Answer solve (Why is it better than organic links)?

What is the data source for your Instant Answer? (Provide a link if possible) Olam http://olam.in

Why did you choose this data source? - It is an opensource dictionary

Are there any other alternative (better) data sources? 

What are some example queries that trigger this Instant Answer? - <word> in malayalam, malayalam meaning of <word>, <word> malayalam meaning, malayalam meaning <word>

Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc) kerala regional users

Is this Instant Answer connected to a DuckDuckHack Instant Answer idea? - No

Which existing Instant Answers will this one supersede/overlap with? - None

Are you having any problems? Do you need our help with anything? No

What are the terms of use for the API? Will DuckDuckGo need specific authorization (e.g. an API key)? Are there any costs associated with API usage? - No special Terms defined(Open Source Dictionary). No API Key needed. Its Free of charge

Where did you hear about DuckDuckHack? (For first time contributors) - From DuckDuckGo 

What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers) - image

Checklist

Please place an 'X' where appropriate.

[X] Added metadata and attribution information
[X] Wrote test file and added to t/ directory
[X] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[X] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
[X] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        [X] Google Chrome
        [X] Firefox
        [X] Opera
        [X] IE 10

    - Windows 7
        [X] Google Chrome
        [X] Firefox
        [X] Opera
        [] IE 8
        [] IE 9
        [] IE 10

    - Windows XP
        [] IE 8

    - Mac OSX
        [] Google Chrome
        [] Firefox
        [] Opera
        [] Safari

    - iOS (iPhone)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - iOS (iPad)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - Android
        [] Firefox
        [X] Native Browser
        [] Google Chrome
        [] Opera

### CODE REVIEW

**Comment by MrChrisW** [comment]
Hi @EaswareApps, thanks for your contribution. 

Do you mind filling out the [pull request template](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/pull_request_template_spice.md) and editing your initial comment, this will allow the community and staff to get a better idea of what your Instant Answer is all about.

We'll review your code shortly and provide feedback :+1:

**Comment by moollaza** [comment]
@EaswareApps thanks a lot for contributing!

We ask that all developers contact us to have their Instant Answer idea approved before making a pull request. This is mostly to ensure your idea is something we can use, so you don't end up wasting your time. Did you happen to miss that part of the documentation, or simply forget to email us? It's totally alright, I'd just like to understand so we can improve the documentation and make sure everything is clear.

**Comment by EaswareApps** [comment]
Using this template will help us better understand your Instant Answer and assist you when necessary. Simply copy and paste the markdown below into the description of your GitHub pull request and complete as appropriate.

What does your Instant Answer do? - Translate English Word into Malayalam(ML)

What problem does your Instant Answer solve (Why is it better than organic links)?

What is the data source for your Instant Answer? (Provide a link if possible) Olam http://olam.in

Why did you choose this data source? - It is an opensource dictionary

Are there any other alternative (better) data sources? 

What are some example queries that trigger this Instant Answer? - <word> in malayalam, malayalam meaning of <word>, <word> malayalam meaning, malayalam meaning <word>

Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc) kerala regional users

Is this Instant Answer connected to a DuckDuckHack Instant Answer idea? - No

Which existing Instant Answers will this one supersede/overlap with? - None

Are you having any problems? Do you need our help with anything? No

What are the terms of use for the API? Will DuckDuckGo need specific authorization (e.g. an API key)? Are there any costs associated with API usage? - No special Terms defined(Open Source Dictionary). No API Key needed. Its Free of charge

Where did you hear about DuckDuckHack? (For first time contributors) - From DuckDuckGo 

What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers) - http://www.easwareapps.com/ddg/screenshot.png

Checklist

Please place an 'X' where appropriate.

[X] Added metadata and attribution information
[X] Wrote test file and added to t/ directory
[X] Verified that instant answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[X] Verified that instant answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
[X] Tested cross-browser compatibility

    Please let us know which browsers/devices you've tested on:
    - Windows 8
        [X] Google Chrome
        [X] Firefox
        [X] Opera
        [X] IE 10

    - Windows 7
        [X] Google Chrome
        [X] Firefox
        [X] Opera
        [] IE 8
        [] IE 9
        [] IE 10

    - Windows XP
        [] IE 8

    - Mac OSX
        [] Google Chrome
        [] Firefox
        [] Opera
        [] Safari

    - iOS (iPhone)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - iOS (iPad)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - Android
        [] Firefox
        [X] Native Browser
        [] Google Chrome
        [] Opera

**Comment by EaswareApps** [comment]
@moollaza Thank you for concern and support. I am just trying study how to build an instant answer. I didn't email because, I was not sure about completing  it.

**Comment by javathunderman** [comment]
@moollaza Seeing as we might go for a more general Translation IA, should this be closed?

**Comment by moollaza** [comment]
@javathunderman ideally a generalized translations IA would be ideal, but I'm not sure if this language is found amongst transaltion API's.

@iambibhas noticed that Yandex offers a translation API which I think we should be able to use. I'm not sure if it supports Malayalam, but if it doesn't then ideally we can close this PR once work begins on a Translation Spice

**Comment by iambibhas** [comment]
@moollaza Yandex doesn't have support for Malayalam.

**Comment by iambibhas** [comment]
@moollaza We could have this one as a submodule of the translate spice. There are services like this that provide translations for a specific language which might not be supported by Yandex. So we could keep Yandex in `Translate::Yandex`, then this one at `Translate::Malayalam` etc.

**Comment by moollaza** [comment]
@EaswareApps are you still interested in working on this?

**Comment by EaswareApps** [comment]
@moollaza. Yes. Sorry for the delay. I was busy for the last 2 weeks

**Comment by zekiel** [comment]
https://duck.co/ia/view/malayalam_dictionary

**Comment by tagawa** [comment]
Re. the "Work in progress" tag, are there further changes needed for this?

**Comment by moollaza** [comment]
@EaswareApps I'm closing this one for now, but if you'd like to finish this up, we'll gladly open it back up for you!

**Comment by javathunderman** [comment]
@moollaza I think that if we were to actually get this IA up and running we should have a full blown IA that handles all translations rather than language by language instant answers.

**Comment by moollaza** [comment]
>@moollaza I think that if we were to actually get this IA up and running we should have a full blown IA that handles all translations rather than language by language instant answers.

@javathunderman I agree -- I don't want per-language translation IAs, but I don't believe any translation service out there handles all languages yet. We've been investigating Bing and Yandex Translation APIs but haven't made any decisions on anything yet.

**Comment by javathunderman** [comment]
@moollaza Ok cool. I think until further notice we can get rid of that "Abandoned" label, seeing as there's not a feasible and elegant way to put this together (well, at the moment :smile:).

**Pull request closed without merging**
