### PR TITLE
RedditSubSearch: Fixes #2514

### LINKED ISSUE #2514: RedditSubSearch: Reign in triggering, remove "r" trigger, require slashes: "/r/"
There are many queries that begin with "r " which are not searches for a subreddit leading to irrelevant  results. e.g. https://duckduckgo.com/?q=R+regex

Autocomplete suggests several more which will trigger the Reddit IA and likely show something unexpected, many of these are related to the programming language, "R". Let's make sure the query has slashes, which very clearly indicate it’s a search related to Reddit: "/r/science" 

drake_at_duckduckgo

------
IA Page:  http://duck.co/ia/view/reddit_sub_search
/cc @MithrandirAgain

### PR DESCRIPTION
**Pull request by swapagarwal**
Update trigger: 'r' -> '/r/'
Migrate to regex triggers
Fixes #2514 
IA Page: https://duck.co/ia/view/reddit_sub_search

### CODE REVIEW

**Comment by daxtheduck** [comment]
@swapagarwal Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@swapagarwal unless regex triggers are required, it's best not to use them for performance reasons. 

The simple fix here is to make the `/`s in the regex required instead of optional.

**Comment by swapagarwal** [comment]
Now, it will still be triggered for "r regex" and we'll be rejecting that in the handle regex.
We can't include `/` in word trigger as it requires a space to separate it from the rest of the query.

**Comment by swapagarwal** [comment]
@moollaza Kindly review.

**Comment by GuiltyDolphin** [comment]
@swapagarwal I've had a play around and it LGTM, thanks! :horse:

**Pull request merged**
