### PR TITLE
Updated Spice wgha with more cities and triggers

### PR DESCRIPTION
**Pull request by bigcurl**
Hi All,

I have updated the Spice wgha with more cities and more trigger words.

Regards
Samuel

### CODE REVIEW

**Comment by moollaza** [comment]
@bigcurl thanks a lot. Can you please add some tests to the existing file to ensure that these work as expectws?

**Comment by bigcurl** [comment]
@moollaza I added a few tests with the new trigger and cities.

**Comment by jagtalon** [comment]
@moollaza should we reserve "events" for GetEvents? 

screen shot 2015-09-14 at 1 16 52 pm

**Comment by moollaza** [comment]
>@moollaza should we reserve "events" for GetEvents? 

@jagtalon sure, this IA has plenty of alternative triggers already.

**Comment by moollaza** [comment]
>@moollaza I added a few tests with the new trigger and cities.

@bigcurl excellent, thanks!

Let's remove the `event(s)` triggers as those belong to another Event Spice that we have, and then this should be good for merge!

**Comment by bigcurl** [comment]
@moollaza Triggers are removed. All good from my side. Please let me know when you plan to deploy.

**Comment by jagtalon** [comment]
:+1:

**Pull request merged**
