### PR TITLE
Forecast: Adds region checking for setting default units

### LINKED ISSUE #3107: Forecast: Default to C for people outside the US
We're defaulting to fahrenheit and get consistent complaints from people outside the US that don't like it. Ideally the default should be based on location.

**sydneys current weather**
[https://duckduckgo.com/?q=sydneys%20current%20weather&kp=1&kad=wt_WT&kl=wt-wt](https://duckduckgo.com/?q=sydneys%20current%20weather&kp=1&kad=wt_WT&kl=wt-wt)
_"In the south pacific we use celsius not fahrenheit"

**nanaimo weather**
[https://duckduckgo.com/?q=nanaimo%20weather&kp=1&kad=wt_WT&kl=wt-wt](https://duckduckgo.com/?q=nanaimo%20weather&kp=1&kad=wt_WT&kl=wt-wt)
_"Why in hell would you give temperature in Fahrenheit by default at a Canadian location? You DO realise that only four countries in the world use Fahrenheit these days, and Canada isn't one of them?"_

**wheather berlin**
[https://duckduckgo.com/?q=wheather%20berlin&kp=1&kad=wt_WT&kl=wt-wt](https://duckduckgo.com/?q=wheather%20berlin&kp=1&kad=wt_WT&kl=wt-wt)
_"Not everyone lives in USA."_

------
IA Page:  http://duck.co/ia/view/forecast 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @himanshu0113

### PR DESCRIPTION
**Pull request by nalinbhardwaj**
## Description of new Instant Answer, or changes

Checks user's region in setting for determining default setting for units.

## Related Issues and Discussions

Fixes #3107 

## People to notify

@himanshu0113 @bsstoner 

---

Instant Answer Page: https://duck.co/ia/view/forecast

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by bsstoner** [comment]
Nice 👍

**Comment by nalinbhardwaj** [comment]
@bsstoner Seems like the travis CI build of the repo is failing after merging this: https://travis-ci.org/duckduckgo/zeroclickinfo-spice

I dont think it's due to this merge though, maybe the build needs to be restarted

**Comment by bsstoner** [comment]
@moollaza @pjhampton any idea why the build would be failing?

**Comment by pjhampton** [comment]
@bsstoner @nalinbhardwaj There was an issue fetching the deps for the CI build. I restarted the 2 failing tests in this repo and they're now passing as expected 👍

**Comment by bsstoner** [comment]
Thanks @pjhampton

**Pull request merged**
