### PR TITLE
added movie to triggers.txt

### LINKED ISSUE #1573: Kwixer: Should trigger on "movies"
Example:
https://duckduckgo.com/?q=adam+sandler+movies
vs
https://duckduckgo.com/?q=movies+with+adam+sandler&ia=movies

We should add "movies" to the triggers.txt file and it looks like we should probably be checking the relevancy of the query against the actor/director returned by the API.

A [relevancy block](https://duck.co/duckduckhack/spice_displaying#relevancy-blocks) would be good.

------
IA Page: https://duck.co/ia/view/kwixer

### PR DESCRIPTION
**Pull request by gokul1794**
Fixes #1573

### CODE REVIEW

**Comment by moollaza** [comment]
@gokul1794 thanks! Let's add a test and a relevancy block :+1:

**Comment by gokul1794** [comment]
@moollaza , this IA doesn't seem to work for directors unless they've starred in the movie too.

**Comment by moollaza** [comment]
@gokul1794 it looks like it works fine for directors? https://duckduckgo.com/?q=movies+directed+by+eli+roth&t=ffab&ia=movies

**Comment by gokul1794** [comment]
@moollaza I just need to compare the Key word with the array of Actors/Directors right?

**Comment by jagtalon** [comment]
@moollaza wait what the bear jew is one of the directors?!

Also, can the `key` be ran against an array or just a string? If not, maybe [`DDG.isRelevant`](https://duck.co/duckduckhack/spice_js_api#isrelevantcandidate-skiparray-minwordlength-strict) will do the trick.

**Comment by jagtalon** [comment]
@gokul1794 ping! :)

**Comment by moollaza** [comment]
@gokul1794 I'm closing this one for now, but if you'd like to finish this up, we'll gladly open it back up for you!

**Comment by amoraleda** [comment]
Hi @moollaza, is it possible to open this issue again? I'd like to finish it up.

Thanks :)

**Comment by moollaza** [comment]
> is it possible to open this issue again? I'd like to finish it up.

@amoraleda done!

**Pull request closed without merging**
