### PR TITLE
Add humidity info to weather IA

### PR DESCRIPTION
**Pull request by vikashvverma**
Fixes https://github.com/duckduckgo/zeroclickinfo-spice/issues/2510

IA Page: http://duck.co/ia/view/forecast
Maintainer: @himanshu0113

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by vikashvverma** [comment]
@moollaza any input?

**Comment by tagawa** [comment]
Hi @vikashvverma. Thank you very much for adding this and sorry for the delay. I've just installed it on the beta server but the IA is not triggering for me: https://beta.duckduckgo.com/?q=weather%20in%20encinitas
I'll take a look and see if I can work out why not.

**Comment by tagawa** [comment]
@vikashvverma I can't see the problem - it's fine for me in Codio - so I've asked an expert colleague to take a look.

**Comment by tagawa** [comment]
@vikashvverma I'm pleased to say the expert (@jdorweiler) fixed it! It looks good on beta now so we'll see if there's any feedback from the community and merge soon.

**Comment by tagawa** [comment]
I forgot to say - @himanshu0113, as maintainer, does this update look OK to you?

**Comment by tagawa** [comment]
I think @himanshu0113 is busy at the moment so let's merge this. It looks good to me and we can create new PRs if there are improvements later.

Thank you for this @vikashvverma - I live in Japan and am always interested in how high the humidity is here (answer: very!).

**Pull request merged**
