### PR TITLE
turbopape's Clojure Documentation from Grimoire Spice

### PR DESCRIPTION
**Pull request by turbopape**
**What does your Instant Answer do?**
This I A fetches, for a clojure symbol, documentation from Grimoire (conj.io) and shows it to the user.

**What problem does your Instant Answer solve (Why is it better than organic links)?**
This IA directly shows the documentation to the developer, hence saving his time.

**What is the data source for your Instant Answer? (Provide a link if possible)**
Grimoire; http://conj.io

**Why did you choose this data source?**
Grimoire is the most comprehensive source of knowledge for Clojure symbols. Cider (IDE on emacs) for instance shows symbols documentation from this source.

**Are there any other alternative (better) data sources?**
As far as I know, no.

**What are some example queries that trigger this Instant Answer?**
clojure doseq (a symbol without a namespace would append 'clojure.core' namespace to the query)
clojure clojure.zip/zippers (would fetch the documentation for this qualified symbol)

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
Clojure learners and developers.

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
Yes. 

**Which existing Instant Answers will this one supersede/overlap with?**
There is on suggestion at https://duck.co/ideas/idea/4464/clojure-functions-replace-clojuredocs-org-with-g . I claimed it, but no other implementation of such an Idea was implemented in live duckduckgo.

**Are you having any problems? Do you need our help with anything?**
No.

**What are the terms of use for the API? Will DuckDuckGo need specific authorization (e.g. an API key)? Are there any costs associated with API usage?**
No. conj.io is free to access.

**Where did you hear about DuckDuckHack? (For first time contributors)**
After adopting duckduckgo as my main search engine, I learned a bit about its mechanics and then discovered duckduckhack.

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
clojure from grimoire

### CODE REVIEW

**Comment by turbopape** [comment]
I might have to add the functions args list in the Spice... will do it shyly.  Please don't merge yet.

**Comment by turbopape** [comment]
Added the args list display. You can merge now !

**Comment by moollaza** [comment]
Hey @turbopape!

I wish I  hadn realized what Instant Answer you were working on earlier so I could have planned this a little better with you!

Ideally, anything that deals with documentation like this should be a Fathead Instant Answer, which parses/scrapes the docs to produce an XML file we convert into a key-value database. The benefit being lookups are super fast as they're stored in a DB on our end.

So my first suggestion is that this should actually be converted to a Fathead.

That being said, we already have an internal ClojureDocs.org Fathead which we should be able to update by executing it's parsing function again. However, I'm not sure what the best source for Clojure docs is, as I don't use Clojure. If ClojureDocs is still the best source, then we should use that. Alternatively, if Grimoire has more, or even clojure.github.io, then we should really create a new Fathead for that source and we can remove the old, internal Clojure Fathead.

Any thoughts?

**Comment by turbopape** [comment]
Hi Zaahir,

Actually grimoire is the best source for clojure documentation as of now.

I understand that Fathead is a better way to handle the doc. I'll look to
see if I can manage some time to work on it if you need to.

Let me know if you need anything from.my side,

Regards

**Comment by turbopape** [comment]
So @moollaza , Do I have to close this PR.

**Comment by moollaza** [comment]
>I understand that Fathead is a better way to handle the doc. I'll look to see if I can manage some time to work on it if you need to.

That would be really appreciated! Sorry about the wasted effort!

>Do I have to close this PR?

I can close it for you :+1: 

Alternatively, is there any kind of Clojure Package API? We have several package lookup Spices like NPM, RubyGems, Hoogle. Perhaps you can save this PR by updating it to use a Clojure Package API?

**Comment by turbopape** [comment]
Yeah. Actually I suggested an instant answer to consult packages from
clojars.org,  the source of clojure packages.

Please feel free to close the PR, I'll try to adapt my work for clojars.org.


Regards,

Rafik

**Pull request closed without merging**
