### PR TITLE
updated regex not to include unrelated integral terms

### PR DESCRIPTION
**Pull request by levaly**
###### What does your Pull Request do (check all that apply)?

Choose the most relevant items and use the following title template to name
your Pull Request.

Bug fix: **`Symbolab: Fix #2708`**

###### Description of changes
Updated the reigger regex not to fire on unrelated queries such as:
'derivative of a vector function' => undef, 
    'integral' 
    'current version plugin gnome shell integration' 
    'continuous integration'
    'integration by parts' 
    'derivative of arctan'
    'line integral'
    'integral calcultor' 
    'derivative of a summation' 
    'integral ad science'
    'derivative of a pmf' 
    'integration vs unit tests' 
Also updated unit tests accordingly.

###### Which issues (if any) does this fix?
Fix #2708

###### People to notify (@mention interested parties)
@moollaza @GuiltyDolphin 

---

Instant Answer Page: https://duck.co/ia/view/symbolab

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
Deploying to Beta...

**Comment by moollaza** [comment]
@levaly thanks! LGTM 👍

**Comment by edgesince84** [comment]
hey @levaly, thank you for your contribution to DuckDuckHack, we really appreciate it! I'm reaching out to let you know that we recently launched a new forum with the initiative of improving programming-related searches, and I hope you'll [join us](https://forum.duckduckhack.com/)!

There are a lot of important tasks up for grabs that we'd like your help with, so feel free to and [jump in](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53).

**Pull request merged**
